enarx/enarx

sgx-types/src/secs.rs, sgx-types/src/tcs.rs
- ~Removed `reserved` fields since we don't need them for alignment/sizing~
- Removed extraneous `bitflags` line
- Changed doc comment to regular comment to fix build error
=> Remove reserved fields

sgx-sys/src/lib.rs, sgx-types/src/attributes.rs, sgx-types/src/lib.rs, sgx-types/src/miscselect.rs, sgx-types/src/secs.rs, sgx-types/src/sigstruct.rs, sgx-types/src/xfrm.rs
Also updated the `enclave_create()` test in `sgx-sys` to use these new types and keep the test from failing.
=> Created types for Xfrm, Attributes, MiscSelect in sgx-types

Cargo.lock, Cargo.toml
Follow-up patch to #71. Resolves #108.
=> Add `sev` to the enarx workspace

iocuddle-sgx/src/lib.rs, sgx-types/src/isv.rs, sgx-types/src/lib.rs, sgx-types/src/secs.rs, sgx-types/src/sig.rs
Fixes #122. Should be rebased on top of #121 when that is merged.
=> Create isv module for SVN and ProdId types

Cargo.lock, Cargo.toml, linux-errno/Cargo.toml, linux-errno/LICENSE, linux-errno/src/lib.rs, linux-errno/src/x86_64.rs, linux-syscall/Cargo.toml, linux-syscall/LICENSE, linux-syscall/src/lib.rs, linux-syscall/src/x86_64.rs
includes no main Cargo.toml and Cargo.lock changes
=> add linux-syscall and linux-errno crate

.github/ISSUE_TEMPLATE/conferences.md
Issue template for conference, automatically adds the 'conference' label.
=> Add conference issue template

sgx-types/src/ssa.rs
=> Add General Protection Fault case in sgx-types/src/ssa.rs

sgx-types/src/lib.rs, sgx-types/src/ti.rs
=> Add Targetinfo struct to sgx-types

iocuddle-sgx/src/lib.rs, sgx-crypto/src/lib.rs, sgx-types/src/secs.rs, sgx-types/src/ti.rs
This PR contains two patches that improve the `Secs` type.
=> SECS improvements

hooks/pre-push.d/eof-newline-test
=> Test for newlines at end of all *.rs and *.toml files

intel-types/Cargo.toml, intel-types/LICENSE, intel-types/src/lib.rs, sgx-types/src/attr.rs, sgx-types/src/lib.rs, sgx-types/src/page.rs, sgx-types/src/secs.rs, sgx-types/src/sig.rs, sgx-types/src/ssa.rs, sgx-types/src/tcs.rs, sgx-types/src/ti.rs, testing/Cargo.toml, testing/LICENSE, testing/src/lib.rs
Based on https://github.com/jsakkine-intel/linux-sgx/blob/master/tools/testing/selftests/x86/sgx/encl_bootstrap.S#L83
Fixes #171 .
=> Add fields to XSave struct

intel-types/src/lib.rs, sgx-types/src/ssa.rs
=> Implement Default for StateSaveArea

intel-types/src/lib.rs, iocuddle-sgx/src/lib.rs, sgx-crypto/src/lib.rs, sgx-types/src/attr.rs, sgx-types/src/isv.rs, sgx-types/src/lib.rs, sgx-types/src/misc.rs, sgx-types/src/secs.rs, sgx-types/src/sig.rs, sgx-types/src/ssa.rs, sgx-types/src/tcs.rs
This is a collection of changes required to merge my SGX keep. It is basically just a bunch of small improvements to existing libraries.
=> Prepraration for SGX keep merge

intel-types/src/lib.rs, sgx-types/src/ssa.rs
=> Add bitflags for Gpr::rflags

README.md
I think Mike and me are not the only mentionable AUTHORS here.
=> README.md: remove explicit list of AUTHORS

.github/workflows/enarx-rust.yml, .github/workflows/enarx-standard.yml
To make all our workflows consistent.
=> Bump actions/checkout to v2

.github/workflows/miscellaneous.yml
=> Don't run tests on containers when not necessary

.github/ISSUE_TEMPLATE/meta.md
Codifying the changes @npmccallum @axelsimon and I discussed when drafting #285.
=> Update meta template w/ guidance on emoji tags

.github/workflows/miscellaneous.yml, .tests/misc-licenses-asm-spdx
=> Test for SPDX ID headers in assembly files

.github/mergeable.yml
Should hopefully fix the issue @npmccallum was having in #303.
=> Add starter Mergeable config to fix bad checks

intel-types/Cargo.toml, intel-types/src/lib.rs, sgx-types/Cargo.toml, sgx-types/src/attr.rs, sgx-types/src/page.rs, sgx-types/src/report.rs, sgx-types/src/secs.rs, sgx-types/src/sig.rs, sgx-types/src/ssa.rs, sgx-types/src/tcs.rs, sgx-types/src/ti.rs
=> Move testing crate to dev-dependencies

.github/ISSUE_TEMPLATE/conferences.md
And turn more things into bullet points.
=> Fix guidance comment formatting in conferences template

iocuddle-sgx/src/lib.rs
I'll need to update some of these, ex. I wasn't sure about `Addpages.count`, `Flags`. But this is a draft.
Fixes #125
=> Add documentation for iocuddle-sgx

sev-show/src/main.rs, sev-show/src/show.rs
=> Fix clippy warnings for sev-show

.github/mergeable.yml
Until we need it for something else.
=> Make Mergeable always pass

.github/workflows/miscellaneous.yml, .tests/misc-lints-clippy-all, .tests/misc-lints-missing-docs, enarx-keep-sgx-shim/src/main.rs, payload/src/main.rs, sev-show/src/main.rs, sev/src/lib.rs, span/src/lib.rs, units/src/lib.rs
=> Test that Rust lints are enabled

enarx-keep-sev-shim/src/lib.rs, enarx-keep-sev-shim/src/main.rs
Just to avoid spuriously failing CI for other PRs.
=> Paper over missing_docs warning for already-merged code

enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs
Filed a debt issue to support multiple threads: #393 
Resolves #394
=> Add preliminary exit_group() syscall handler

enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs
Really not sure how to represent int *, is this the right way ?
(Potentially) resolves #396
=> Stub for set_tid_address

.automation/copy-issue-labels-to-pr
=> Fix labeler bot infinite loop

.github/ISSUE_TEMPLATE/mentorship.md
A quick stab at a mentorship request issue template. I've created a `mentorship` label to go along with it.
Resolves #418.
=> Add mentorship request template

Cargo.toml, memory/Cargo.toml, memory/LICENSE, memory/src/address.rs, memory/src/lib.rs, memory/src/offset.rs, memory/src/page.rs, memory/src/register.rs
This provides various different utility types for managing memory.
=> Add memory crate

enarx-keep-sgx-shim/src/handler.rs
=> Fix use-after-free bug

enarx-keep-sgx/src/builder.rs, enarx-keep-sgx/src/main.rs
We calculate offsets internally where needed. This helps with future
ergonomics.
=> Always take absolute addresses in the enclave builder

sgx-types/src/tcs.rs
Implement Copy/Clone for Tcs. Remove the reserved fields and alignment.
=> Update sgx_types::tcs::Tcs for the new strategy

enarx-keep-sgx-shim/Cargo.toml, enarx-keep-sgx-shim/layout.ld, enarx-keep-sgx-shim/src/entry.rs, enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs, enarx-keep-sgx-shim/src/main.rs, enarx-keep-sgx-shim/src/start.S, enarx-keep-sgx/Cargo.toml, enarx-keep-sgx/src/builder.rs, enarx-keep-sgx/src/component.rs, enarx-keep-sgx/src/layout.rs, enarx-keep-sgx/src/main.rs
We pass a full Layout struct describing the layout of the memory space.
Fixes: #388
=> Rework the SGX loader to pass measured argument

enarx-keep-sgx-shim/src/elf.rs, enarx-keep-sgx-shim/src/entry.rs, enarx-keep-sgx-shim/src/main.rs, enarx-keep-sgx/src/layout.rs, enarx-keep-sgx/src/main.rs
=> Switch to running static-pie binaries

enarx-keep-sgx-shim/Cargo.toml, enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs, enarx-keep-sgx-shim/src/heap.rs, enarx-keep-sgx-shim/src/main.rs, nolibc/src/lib.rs
Fixes: #406
Fixes: #405
Fixes: #82
=> Fix brk(); implement remaining syscalls for payload

enarx-keep-sgx-shim/Cargo.toml, enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs, sgx-types/src/ssa.rs
=> Check for invalid opcode in event()

memory/src/address.rs, memory/src/offset.rs
=> Fix for rust 1.43

sev/src/lib.rs
remove unused import in sev/src/lib.rs
#495
=> remove unused import in src/lib.rs

cc
adds "insert-target-rlib"
link.json:
…
"insert-target-rlib": ["libc"],
…
will add
$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/liblibc-6c4492b949101b15.rlib
as a static library
=> cc: add a specific rlib from the target directory

enarx-keep-sgx-shim/src/event.rs
Addresses Issue #328 
In this commit I define a handful of opcodes as defined in the [Intel® 64 and IA-32 Architectures Software Developer’s Manual](https://software.intel.com/sites/default/files/managed/39/c5/325462-sdm-vol-1-2abcd-3abcd.pdf) in order to enable nicer pattern matching. I'm a new contributor so I am eager for feedback, especially about the following:
1. Opcodes are varying-length, ranging from one to three bytes with additional modifiers that can be added. I found this an interesting design consideration because it seems to me that an enum (using the enumerate macro) would be a good way to incorporate so many opcode constants - but the only way I could figure out to do this was to use an enum of `&[u8]` values, which would have required specifying a lifetime. This seemed …
=> Instruction Pattern Match Constants

enarx-keep-sgx/src/builder.rs
https://lkml.org/lkml/2020/5/7/1652
=> Use a private, anonymous mapping per LKML advice

sev-show/src/main.rs
=> Remove Allow lint attr. from sev-show

containers/fedora-test/Dockerfile, containers/fedora/Dockerfile
This will allow us to consolidate our (generally pretty light) container repos into one place.
=> Move Enarx dev/test containers to main repo

containers/fedora/Dockerfile
=> Install diff in dev/test container

.github/workflows/automation-label.yml, .github/workflows/automation-pr.yml, .github/workflows/cargo.yml, .github/workflows/miscellaneous.yml
=> Update tests to use merged Enarx dev container

crt0stack/src/lib.rs
Make use of `slice::copy_within()` to support small stack sizes.
Guard against OutOfSpace situations with checked integer arithmetic.
Align the final stack to `const STACK_ALIGNMENT = 16`.
=> Stack alignment, safe guards and small stacks

enarx-keep-sgx/src/builder.rs, iocuddle-sgx/src/lib.rs, sgx-types/src/sig.rs
Resolves: #565 
I had to close the previous pull request as I made multiple commits.
=> Simplify SIGSTRUCT

enarx-keep-sgx-shim/src/handler.rs
I noticed this TODO was still here even though #337 has been closed. It didn't make sense to remove this comment as part of another PR.
=> Remove TODO that has been fixed in handler.rs

crt0stack/src/lib.rs
=> Add crt0 stack alignment test

enarx-keep-sgx/src/component.rs
Closes #529
Signed-off-by: Ziyi Yan <ziyi.yan@foxmail.com>
=> use mmap to load ELF file for parsing

Makefile.toml, enarx-keep-sev/Cargo.toml, enarx-keep-sev/src/main.rs, enarx-keep-sev/src/vm/builder.rs, enarx-keep-sev/src/vm/mem.rs, enarx-keep-sev/src/vm/mod.rs, enarx-keep-sgx/Cargo.toml, enarx-keep-sgx/src/builder.rs, enarx-keep-sgx/src/main.rs, loader/Cargo.toml, loader/LICENSE, loader/src/lib.rs, loader/src/segment.rs
Related: #313 
Unfortunately we can't execute the code that this PR is loading into the guest but PRs that build on top of this one will get us all the way there.
=> Load the SEV shim into the guest address space

enarx-keep-sgx/Cargo.toml, iocuddle-sgx/Cargo.toml, memory/src/page.rs, sev/Cargo.toml, sgx-crypto/Cargo.toml
=> memory: add conf fn Page::zeroed()

sev/.gitignore
Closes #503 
Signed-off-by: Adam Baxter <ambaxter@users.noreply.github.com>
=> Removed unnecessary .gitignore in sev

enarx-keep-sev-shim/src/gdt.rs, enarx-keep-sev-shim/src/main.rs
If the kernel stack later gets changed, we want no allocated objects on the old stack.
=> Make TSS and GDT part of .data rather than allocate on the stack

enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs
=> sgx-shim: Add support for the getrandom() syscall

sev/src/firmware/linux/ioctl.rs, sev/src/firmware/linux/mod.rs, sev/src/firmware/types.rs, sev/tests/api.rs
Closes #112 
My redemption arc
=> Move SEV ioctls over to iocuddle

enarx-keep-sgx-shim/src/handler.rs
=> Use syscall proxy for exit

enarx-keep-sev-shim/src/usermode.S
Just set it... doesn't hurt, if it is not globally enabled
=> usermode: set interrupt enable flag

enarx-keep-sgx-shim/src/handler.rs
=> Update exit_group syscall to use proxy

memory/src/register.rs
I realized that const conversions to and from Register are safe
precisely because pointer casts are safe. The only thing that is unsafe
is dereferencing a pointer. Therefore, I implemented const pointer and
reference casts.
Likewise, I added a utility for converting a Register to a slice. This
operation is, however, unsafe and is marked as such. It is merely a
convenience function around slice::from_raw_parts().
=> Even more conversions for Register

enarx-keep-sgx-shim/src/handler.rs
=> Update write syscall to use proxy

enarx-keep-sgx-shim/src/heap.rs
This adds a couple of unit tests that exercise the methods (mmap, munmap, and brk) of Heap to ensure that the object state is properly updated.  This also fixes an issue that munmap returns an error if the mapped memory ends with the last page in the heap.
=> sgx-shim: Add unit tests for Heap

enarx-keep-sgx-shim/src/handler.rs, sallyport/src/lib.rs
Resolves #705 
@npmccallum This doesn't have tests yet. But I am wondering if it's in the general direction of what you're thinking. Also: making the `Block.buf` field private would mean we can't check whether the input / output is longer than the available buffer in the `handler`.
=> Add Cursor to sallyport Block

.github/workflows/cargo.yml, Makefile.toml
Closes #646
Signed-off-by: Adam Baxter <ambaxter@users.noreply.github.com>
=> Separate project ci and per-crate ci tasks

integration-tests/src/bin/write_stderr.rs, integration-tests/src/bin/write_stdout.rs, integration-tests/tests/common/mod.rs, integration-tests/tests/syscall_exit.rs, integration-tests/tests/syscall_write.rs
=> Add a test for Write system call

enarx-keep-sev-shim/src/hostcall.rs, enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs, enarx-keep-sgx-shim/src/heap.rs, memory/src/register.rs, sallyport/src/lib.rs
This work will probably conflict with @lkatalin 's work. So we should merge her PRs first and then rebase.
=> Various cleanups

integration-tests/src/bin/read.rs, integration-tests/tests/syscall_read.rs
=> Add a test for Read system call

sev/src/certs/ca/cert/v1.rs
=> Add missing conditional compile guards for OpenSSL bits

enarx-keep-sgx/src/enclave.S
=> Let the vDSO preserve %rbx

containers/fedora/Dockerfile
=> Update the compiler to nightly

keep-runtime/Cargo.toml
=> keep-runtime: update to wasmtime 0.19

enarx-keep-sgx/src/main.rs, sgx/src/enclave/builder.rs, sgx/src/enclave/enclave.rs, sgx/src/types/page.rs, vdso/src/lib.rs
This should help with porting to `enarx-keep`.
=> Split Enclave into Enclave and Thread objects

sgx/Cargo.toml, sgx/Makefile.toml, sgx/examples/generate_report.rs, sgx/src/attestation_types/report.rs, sgx/src/attestation_types/ti.rs, sgx/src/lib.rs
=> Generate a REPORT by populating TARGETINFO with default values

enarx-keep/shims/shim-sev/.cargo/config, enarx-keep/shims/shim-sgx/.cargo/config
reduce the size of the shims
See https://github.com/rust-lang/rust/issues/75524
=> enarx-keep/shims/*: link-args=-Wl,--sort-section=alignment

units/src/lib.rs
=> Add docs to units

sgx/src/attestation_types/ti.rs
There are no functionality changes.
=> Minor cleanup of TargetInfo::get_report()

sevctl/src/main.rs
This could be a helpful way to cache the entire chain somewhere. It can
be easily decoded with the 'sev' crate.
sevctl export --full $HOME/$(hostname).chain
Fix a quick typo while we're in there.
=> Extend export command to optionally export the entire certificate chain

mmap/src/lib.rs
In particular, we define a new error type that wraps `std::io::Error`
and conveys ownership of an object. This allows us to return the
old mapping along with an error condition without breaking the try
operator.
=> Improve the new mmap crate interface

enarx-keep/tests/bin/clock_gettime.c, enarx-keep/tests/bin/exit_one.c, enarx-keep/tests/bin/exit_zero.c, enarx-keep/tests/bin/libc.h, enarx-keep/tests/bin/write_emsgsize.c, enarx-keep/tests/bin/write_stderr.c, enarx-keep/tests/bin/write_stdout.c, enarx-keep/tests/integration_tests.rs
=> various integration test improvements

enarx-keep/src/main.rs
This allows us to pass this configuration parameter across intermediary
commands (such as `cargo test`).
=> Use env `ENARX_BACKEND` instead of arg `--keep`

README.md
A quick update of the README, closes #172.
Signed-off-by: axelsimon <github@axelsimon.net>
=> Update the description of Enarx goals in the README

FUNDING.md
Provide information with regards to Enarx's current funding situation.
Signed-off-by: axelsimon <github@axelsimon.net>
=> Add a FUNDING.md file

FUNDING.md
Signed-off-by: MikeCamel <mike@p2ptrust.org>
Minor change.
=> Minor change around funding

.github/workflows/lint.yml, .github/workflows/test.yml, BUILD.md, Cargo.lock, Cargo.toml, README.md, README.tpl, internal/shim-sgx/src/handler/enarx.rs, src/main.rs, tests/integration_tests.rs
=> Rename `enarx-keepldr` to `enarx`

STYLE.md
Thanks to Jarkko Sakkinen for proding me to do this.
[Rendered](https://github.com/npmccallum/enarx/blob/style/STYLE.md).
=> Add the beginnings of a code style guide

internal/shim-sev/src/snp/ghcb.rs
=> fix(shim-sev): unwrap all test code lines.

internal/shim-sev/src/idt.rs
Remove more copypasta from idt.rs.
=> fix(shim-sev): reduce `idt.rs` even more

.github/CODEOWNERS
=> Add @wgwoods to CODEOWNERS

internal/shim-sev/src/gdb.rs, internal/shim-sev/src/snp/secrets_page.rs, internal/shim-sev/src/syscall.rs, internal/shim-sgx/src/handler/gdb.rs, src/backend/sev/builder.rs, src/backend/sev/cpuid_page.rs
=> fix: add more code documentation

internal/shim-sev/src/main.rs
=> fix(shim-sev): beautify startup assembly

rust-toolchain.toml
This works around a recent compiler bug.
Fixes: #1209
=> Pin to an older nightly

build.rs
=> Recompile C unit tests when the source code changes

.github/workflows/lint.yml, .github/workflows/test.yml, rust-toolchain.toml
Nightly issue https://github.com/enarx/enarx/issues/1209 fixed
=> Use unpinned nightly again

.github/CODEOWNERS
=> chore: cleanup CODEOWNERS

STYLE.md
The issue is described in #1263. The PR fixes also couple of typos.
=> STYLE.md: Clarify the definition of an use-statement group 

build.rs, src/backend/sev/builder.rs, src/backend/sev/mod.rs, src/backend/sev/snp/launch/linux.rs, src/backend/sev/snp/launch/mod.rs
The first one migrates to kvm_enc_region and other one fixes a compilation issues in Arch Linux.
=> Enarx updates

tests/common/mod.rs, tests/integration_tests.rs, tests/wasmldr_tests.rs
=> Serialize tests again

internal/wasmldr/src/main.rs
Signed-off-by: Deepanshu <deepansharora27@gmail.com>
Closes #1098
=> Fixing CLI Log Issue

src/backend/sev/data.rs
SNP is needed, so better check for it.
Fixes: https://github.com/enarx/enarx/issues/1317
=> fix(sev): check for SEV-SNP rather than only for SEV

src/backend/kvm/builder.rs, src/backend/sev/builder.rs, src/backend/sev/cpuid_page.rs, src/backend/sgx/builder.rs
This adds to the user experience. Instead of just displaying `Error: I/O Error`, the user gets a more detailed description where and why the code failed.
See #1315
Fixes: #1277
Fixes: #726
=> fix(enarx): add more `context()` to `anyhow::Result` returns

internal/wasmldr/Cargo.lock, internal/wasmldr/Cargo.toml
=> fix(wasmldr): update to wasmtime 0.34.0

Cargo.lock, internal/shim-sev/Cargo.lock, internal/shim-sev/Cargo.toml, internal/shim-sgx/Cargo.lock, internal/shim-sgx/Cargo.toml
=> Update xsave to 2.0.2

src/cli/info.rs
Closes Issue #1208
Enarx version is printed whenever `enarx info` or `enarx info --json` is run on terminal.
Made changes in src/cli/info.rs
Made a struct Info, which is used when the `--json` flag is true. It prints the version no. and the backend.
When `--json` is not used, version no. is printed using `env!("CARGO_PKG_VERSION")`.
=> Enarx info enarx version

.github/CODEOWNERS
=> chore: Add @rvolosatovs to CODEOWNERS

internal/shim-sev/README.md
Some documentation about SEV-SNP and this shim.
=> feat(shim-sev): add README.md

build.rs, src/backend/sgx/attestation.rs
Check that SGX is enabled before running the test.
Closes: https://github.com/enarx/enarx/issues/1402
=> fix[sgx]: attestation test

.github/workflows/lint.yml, .github/workflows/test.yml
=> test: make apt more resilient against network failures

.github/workflows/pr.yml
=> test: enable automerge on pull requests

.github/workflows/pr.yml
=> test: clean up auto-merge feature

src/backend/sgx/ioctls.rs
=> feat(sgx): SGX_IOC_ENCLAVE_{RELAX,RESTRICT}_PERMISSIONS

.github/workflows/dependabot.yml
=> build(deps): enable auto-approve Dependabot pull-request

.github/workflows/pr.yml
=> chore(gh-actions): disable automerge on draft PRs

src/backend/kvm/mod.rs, src/backend/sev/mod.rs, src/backend/sgx/mod.rs, src/cli/mod.rs
And error out with a message to run `enarx info` to prevent users from
getting strange error messages later.
=> fix(backend): require all checks to pass

helper/test-enarx.sh
=> fix(helper/test-enarx.sh): require bash

Cargo.lock, internal/wasmldr/Cargo.lock
- chore(deps): update internal crate dependencies
- chore(deps): update Enarx dependencies
=> chore(deps): update Enarx dependencies

.github/workflows/test.yml, .github/workflows/toolchain-update-test.yml
=> chore(deps): temporarily disable nix tests

internal/wasmldr/Cargo.lock, internal/wasmldr/Cargo.toml, internal/wasmldr/src/main.rs, internal/wasmldr/src/wasi/mod.rs, internal/wasmldr/src/wasi/preview_0.rs, internal/wasmldr/src/wasi/preview_1.rs, internal/wasmldr/src/workload.rs
This will be required for #1156 #1480 
Closes #1489 
@npmccallum @haraldh please look through the interface and point out calls we can immediately error out on
=> feat(wasmldr): override `WasiCtx`

internal/shim-sev/src/syscall.rs
Debugging it, will intermix debugging output with real and debugging output.
=> fix(shim-sev): don't debug syscall SYS_write

.github/workflows/lint.yml, .github/workflows/test.yml
Re-enable SEV tests after Milan connectivity workaround has been applied.
Ref #1508
=> chore(ci): re-enable SEV tests

internal/shim-sev/src/exec.rs, internal/shim-sev/src/gdt.rs, internal/shim-sev/src/hostcall.rs, internal/shim-sev/src/main.rs, internal/shim-sev/src/random.rs
Fixes: https://github.com/enarx/enarx/issues/1468
=> feat(shim-kvm): support old CPUs in KVM mode

Cargo.lock
=> build(deps): bump vdso

Cargo.lock, Cargo.toml, internal/shim-sev/Cargo.lock, internal/shim-sev/Cargo.toml, internal/shim-sgx/Cargo.lock, internal/shim-sgx/Cargo.toml, tests/sev_attestation/Cargo.toml
=> build(deps): update sallyport

Cargo.toml, src/cli/mod.rs, src/cli/sgx.rs, src/main.rs
=> feat(sgx): add `enarx sgx register` command

.github/workflows/lint.yml, .github/workflows/test.yml, flake.nix, rust-toolchain.toml
Fix inconsistent Rust toolchain version and broken nix flake introduced by https://github.com/enarx/enarx/pull/1530
=> build(deps): update rust toolchain

internal/shim-sgx/src/handler/mod.rs
```
Transcript of the compilation error:
error[E0308]: mismatched types
--> src/handler/mod.rs:197:21
|
197 |         if let Some(ExceptionVector::InvalidOpcode) = ssa.vector() {
|                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ------------ this expression has type `Option<Vector>`
|                     |
|                     expected enum `Vector`, found enum `ExceptionVector`
|
= note: perhaps two different versions of crate `x86_64` are being used?
error[E0308]: mismatched types
--> src/handler/mod.rs:213:18
|
212 |         match h.ssa.vector() {
|               -------------- this expression has type `Option<Vector>`
213 |             Some(ExceptionVector::InvalidOpcode) => {
|                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `Vector`, found enum `ExceptionVector` …
```
=> fix(sgx): a compilation error in shim-sgx

internal/wasmldr/src/loader/compiled/tls.rs
=> fix(wasmldr): make examples/tcp_server work with TLS

flake.lock
Just a regular dependency update
=> build(deps): update nix flake

internal/shim-sgx/layout.ld, internal/shim-sgx/src/handler/gdb.rs, internal/shim-sgx/src/handler/mod.rs, internal/shim-sgx/src/lib.rs, internal/shim-sgx/src/main.rs
=> feat(sgx): shim_address() for normal and naked functions

.github/workflows/sbom_manifest_action.yml, .github/workflows/sbom_manifest_check.yml
Use CycloneDX to generate the BOM manifest artifact [JSON] with this
workflow
Resolves issue #1448
Signed-off-by: abhinandanudupa <67597710+abhinandanudupa@users.noreply.github.com>
=> chore(ci): add workflow to generate SBOM

internal/wasmldr/Cargo.lock, internal/wasmldr/Cargo.toml, internal/wasmldr/src/loader/configured/mod.rs
=> feat: wasmldr attestation

Cargo.lock, internal/shim-sgx/Cargo.lock, internal/shim-sgx/Cargo.toml, internal/shim-sgx/src/heap.rs
feat(shim-sgx): maintain `Heap` state with `mmledger::Ledger` 
=> feat(shim-sgx): enable `mmledger::Ledger`

src/backend/sgx/ioctls.rs
=> fix: CI after kernel update

Cargo.lock, Cargo.toml, internal/shim-kvm/Cargo.lock, internal/shim-kvm/Cargo.toml, internal/shim-sgx/Cargo.lock, internal/shim-sgx/Cargo.toml, tests/sev_attestation/Cargo.toml
simple version with copying to a new location
Fixes: #1638
Fixes: #1637
=> feat: add mremap() via sallyport update

Cargo.lock, internal/shim-kvm/Cargo.lock, internal/shim-sgx/Cargo.lock
=> chore(deps): update cargo dependencies

.github/labeler.yml, .github/workflows/labeler.yml
Signed-off by Paul Pietkiewicz [paul@profian.com](mailto:paul@profian.com)
Rebased version of @shravi24's PR #1066
Closes #62
=> chore: automatically apply labels to PRs based on files modified

.github/workflows/cargo-update.yml
=> chore(deps): add workflow to automatically update enarx dependencies

.github/CODEOWNERS
=> chore: add bstrie to codeowners

Cargo.lock, Cargo.toml, src/bin/shim-kvm/Cargo.toml, src/bin/shim-sgx/Cargo.toml, tests/sev_attestation/Cargo.toml
=> chore: bump sallyport to 0.4

.vscode/settings.json, Cargo.lock, Cargo.toml, src/backend/sgx/builder.rs, src/backend/sgx/config.rs, src/backend/sgx/ioctls.rs, src/bin/shim-sgx/Cargo.toml
Two commits in preparation for release.
=> chore: prepare for release

src/bin/shim-kvm/Cargo.toml, src/bin/shim-sgx/Cargo.toml
The description field is mandatory for publishing on crates.io.
=> fix(shim): add description to Cargo.toml

Cargo.lock, Cargo.toml, crates/sallyport/Cargo.toml, src/bin/exec-wasmtime/Cargo.toml, src/bin/shim-kvm/Cargo.toml, src/bin/shim-sgx/Cargo.toml
Part of https://github.com/enarx/enarx/issues/1563 .
=> chore: remove unused dependencies from all crates

.github/workflows/coverage.yml
=> ci: add coverage

Cargo.toml, crates/exec-wasmtime/Cargo.toml, crates/sallyport/Cargo.toml, crates/sallyport/README.md, crates/shim-kvm/Cargo.toml, crates/shim-sgx/Cargo.toml, examples/tcp_server/Cargo.toml, tests/rust_exec_tests/Cargo.toml, tests/rust_syscall_tests/Cargo.toml, tests/sev_attestation/Cargo.toml, tests/wasm/wasm_rust_tests/Cargo.toml
This updates sallyport's Cargo.toml as part of https://github.com/enarx/enarx/issues/1713 . While we're at it this also cleans up, reorganizes, and regularizes the contents of all the Cargo.toml files in the repo.
=> chore: fix links and style in toml files

.github/workflows/coverage.yml
=>  ci: switch using codecov for coverage 

.codecov.yml, .github/workflows/coverage.yml
=> ci: add codecov.yml

.codecov.yml, Cargo.lock, crates/exec-wasmtime/Cargo.toml, crates/exec-wasmtime/src/loader/acquired.rs, crates/exec-wasmtime/src/loader/compiled/mod.rs, crates/exec-wasmtime/src/loader/compiled/null.rs, crates/exec-wasmtime/src/loader/compiled/tls.rs
also wasmtime-wasi, wasi-common and wiggle.
Fixes: #1772
=> build(deps): update wasmtime requirement from 0.35.2 to 0.36.0

.codecov.yml
=> ci: fix the paths

src/backend/sgx/thread.rs
=> feat(sgx): display full exception information

docs/Install.md
Move "testable" documentation to live alongside code.
=> docs(versioned): add versioned documentation

.github/workflows/test-docs.yml, helper/md-test.sh
=> test(docs): add script to test markdown documentation

Cargo.toml, build.rs, src/backend/binary.rs, src/backend/mod.rs, src/main.rs
Saves a lot of compile time and energy!
=> fix: make a lot of crates optional

.github/workflows/test.yml, Cargo.lock, Cargo.toml, crates/exec-wasmtime/Cargo.toml, crates/exec-wasmtime/src/loader/configured/platform.rs, crates/exec-wasmtime/src/loader/requested.rs
Fixes: #1790 
```
❯ uname -a
Darwin MacBook-Pro-3.fritz.box 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
❯ cargo test --no-default-features --features=backend-nil --test wasmldr_tests
Finished test [unoptimized + debuginfo] target(s) in 0.38s
Running tests/wasmldr_tests.rs (target/debug/deps/wasmldr_tests-6c8348af9ae6e231)
running 9 tests
test memspike ... ok
test check_tcp ... ok
test return_1 ... ok
test hello_wasi_snapshot1 ... ok
test memory_stress_test ... ok
test wasi_snapshot1 ... ok
Error: default export in '' is not a function
test no_export ... ok
test echo ... ok
test zerooneone ... ok
test result: ok. 9 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 24.14s
```
Signed-off-by: Harald Hoyer …
=> feat: MacOS support with the nil backend

Cargo.lock, examples/tcp_server/Cargo.toml
=> chore(deps): bump dependency versions

.github/workflows/sbom_manifest_action.yml, docs/Install.md, rust-toolchain.toml
=> chore(deps): bump toolchain to 2022-05-03

Cargo.lock, crates/shim-kvm/Cargo.toml, crates/shim-sgx/Cargo.toml, tests/rust_syscall_tests/Cargo.toml
=> build(deps): update rcrt1 requirement from 1.0.0 to 2.2.0

docs/Install.md
=> docs(revert): revert toolchain to nightly-2022-04-11 for 0.4.0 release

helper/release_enarx.sh
=> chore(release): add release script

examples/tcp_server/.cargo/config, examples/tcp_server/rust-toolchain.toml, tests/crates/enarx_exec_tests/.cargo/config, tests/crates/enarx_exec_tests/rust-toolchain.toml, tests/crates/enarx_wasm_tests/.cargo/config, tests/crates/enarx_wasm_tests/rust-toolchain.toml, tests/crates/sev_attestation/.cargo/config, tests/crates/sev_attestation/rust-toolchain.toml
=> refactor: remove unused Cargo config and rust-toolchain files

tests/wasm/mod.rs
Only test `deploy` of `zerooneone` and `check_tcp`
=> test: trim the testing matrix

docs/Install.md
Fixes: #1805
Fixes: #1806
Fixes: #1807
=> docs: update docs/Install.md

crates/sallyport/src/guest/call/enarxcall/passthrough.rs, crates/sallyport/src/guest/handler.rs, crates/sallyport/src/item/enarxcall/mod.rs, crates/sallyport/tests/enarxcall/mod.rs, crates/shim-sgx/src/handler/mod.rs, src/backend/sgx/builder.rs, src/backend/sgx/thread.rs
=> feat(sgx): host side mm-handlers

helper/release_enarx.sh
- Remove `enarx-exec-wasmtime-bin` dependency
- Allow passing user's enarx fork URL
- Remove hardcoded crates lists
- Adjust permissions for mock registry
- Update to use the latest published test images
=> refactor(test): remove exec-wasmtime-bin and refactor code

.github/workflows/release.yml
=> build(release): prune duplicate binaries and tests for macos

.github/workflows/coverage.yml, crates/shim-kvm/src/debug.rs, crates/shim-kvm/src/gdt.rs, crates/shim-kvm/src/interrupts.rs, crates/shim-kvm/src/lib.rs, crates/shim-kvm/src/main.rs, crates/shim-kvm/src/snp/ghcb.rs, crates/shim-kvm/src/snp/mod.rs, crates/shim-kvm/src/sse.rs, crates/shim-kvm/src/syscall.rs, crates/shim-kvm/src/usermode.rs
As suggested in https://github.com/enarx/enarx/pull/1901#discussion_r880553241 .
=> ci(coverage): use published coverage tool and update coverage exclusions

README-DEBUG.md
Link: https://github.com/enarx/enarx/issues/1930
=> fix(documentation): reburnish KVM / SNP in README-DEBUG.md

.github/workflows/release.yml
=> ci(gha): disable jobs for M1 Darwin

docs/Install.md
=> docs: install documentation update

.github/workflows/nix.yml, Cargo.lock, crates/exec-wasmtime/Cargo.toml
=> build(deps): cargo update and wasmtime 0.38

docs/Enarx_toml.md
[Rendered](https://github.com/enarx/enarx/blob/02cb7a977dcde965ad72c26c41a44caddef1ebc0/docs/Enarx_toml.md)
=> docs: add Enarx_toml.md

flake.lock, flake.nix
=> build(nix): update flake lock

docs/Enarx_toml.md
=> docs: add reference to Enarx_toml.md

docs/Quickstart.mdx
=> docs: bump version in Quickstart to 0.6.0

crates/enarx-config/src/lib.rs
=> feat: add Serialize to enarx-config

src/backend/kvm/mod.rs, src/backend/mod.rs, src/backend/nil.rs, src/backend/sev/mod.rs, src/backend/sgx/mod.rs, src/cli/mod.rs, src/cli/platform/info.rs
Fixes: https://github.com/enarx/enarx/issues/2042
Output for nil backend only machine:
```
Enarx version 0.6.0
System Info: Darwin 21.5.0 Darwin […]
✗ Backend: sgx
✗ Backend: sev
✗ Backend: kvm
✔ Backend: nil
```
This enables more detailed backend name error messages:
```
❯ enarx run --backend=foo ~/hello_wasi_snapshot1.wasm
Error: Keep backend identifier "foo" is unknown.
❯ enarx run --backend=sgx ~/hello_wasi_snapshot1.wasm
Error: Keep backend "sgx" is not available on this platform.
```
or even:
```
❯ enarx run --backend=sgx ~/hello_wasi_snapshot1.wasm
Error: Keep backend "sgx" is available on this platform, but the machine is misconfigured. Please check with `enarx platform info`.
❯ enarx platform info
Enarx version 0.6.0
System Info: Linux 5.16.0-sgx4 #1 SMP PREEMPT Thu Apr 14 …
```
=> feat(backend): register well-known backend names

docs/Running/Publish.md
=> docs: document publishing and deploying via CLI

crates/enarx-config/Enarx_toml.md, docs/Enarx_toml.md, helper/release_enarx.sh
- Ensure the approved title is used for `Enarx_toml.md`
- Add `Publish.md`
- Remove unused `docs/Enarx_toml.md` symlink
- Ensure that Enarx version is properly bumped in `Quickstart.mdx` during release
=> docs: update Quickstart.mdx, cleanup

src/cli/package/publish.rs, tests/client/mod.rs
=> fix(cli): forbid publish of malformed packages

crates/exec-wasmtime/src/loader/connected.rs
Closes #2094 
Fixes https://github.com/enarx/codex/issues/15
=> feat: treat 0 exit code as success

crates/shim-kvm/src/snp/mod.rs, src/backend/sev/snp/launch/linux.rs
=> fix: bool::into() for 0 and 1

.github/workflows/release.yml
=> chore(windows): update wix to 0.3.3

Cargo.lock
=> build: update chrono from 0.4.19 to 0.4.20

Cargo.lock, Cargo.toml, crates/exec-wasmtime/Cargo.toml, crates/exec-wasmtime/src/lib.rs, crates/exec-wasmtime/src/loader/requested.rs, src/cli/deploy.rs
Closes #2033
Closes #1854 
Blocked by https://github.com/profianinc/drawbridge/pull/246
=> feat: validate workload digests

.github/workflows/nix.yml, flake.lock, flake.nix, shell.nix
Update the flake lock, the flake syntax and set up a formatter. Validate formatting on CI.
Refs https://github.com/profianinc/drawbridge/pull/216
=> build(nix): update flake

Cargo.lock, crates/exec-wasmtime/Cargo.toml
=> build: update wasmtime

.github/workflows/release.yml, release/linux/deb/control, release/linux/rpm/enarx.spec
=> feat: add rpm and debian packages to release

Cargo.lock, Cargo.toml, crates/sallyport/Cargo.toml
=> build: update serial_test dependency to 0.9

.github/workflows/release.yml, release/linux/rpm/enarx.spec
=> ci(release): add keep signatures to released artifacts

.github/workflows/test-docs.yml, README.md, docs/Install.md, helper/release_enarx.sh
=> chore(release): disable publishing to crates

docs/Quickstart.mdx
=> fix(docs): add whitespace for Quickstart RPM install

crates/shim-kvm/src/snp/ghcb.rs
Use the SnpReportRequest struct to request attestation reports from the SEV-SNP PSP firmware.
Previously the get_attestation call failed spuriously, if there were non-zero bytes following the user data in the uninialized memory, which then causes the PSP firmware to return `report.status = 0x16`.
=> fix(shim-kvm): use SnpReportRequest struct

crates/shim-sgx/src/handler/mod.rs
Some methods were in a separate block.
=> chore(shim-sgx): merge `impl Handler` sections

Cargo.lock, Cargo.toml, src/backend/sgx/builder.rs, src/cli/mod.rs
This gives better output in a threaded environment and more features.
=> feat(backend): use `tracing` instead of `log` for logging

crates/sallyport/src/guest/call/enarxcall/types/result.rs, crates/sallyport/src/guest/call/gdbcall/types/result.rs
=> style: use unbounded ranges in patterns

crates/exec-wasmtime/src/loader/compiled/mod.rs, crates/exec-wasmtime/src/loader/compiled/tls.rs
A few commits extracted from https://github.com/enarx/enarx/pull/2174 to simplify review
=> refactor(exec-wasmtime): minor improvements

crates/enarx-config/src/lib.rs, crates/exec-wasmtime/src/loader/compiled/mod.rs
This lets us provide more meaningful file variant defaults and account for e.g. TCP and TLS socket differences
Extracted from #2174 
=> feat(config): introduce file types

crates/enarx-config/src/lib.rs
Currently arbitrary string can be turned into a file name, that should not be allowed
~Blocked by #2197~
=> fix(config): disallow invalid file names

Cargo.lock
=> build: bump linked_list_allocator to 0.10.3

crates/exec-wasmtime/src/workload.rs
=> fix: parse `Config`, not `Option<Config>`

.github/workflows/coverage.yml, .github/workflows/sbom_manifest_action.yml, .github/workflows/test.yml, Cargo.lock, build.rs, crates/exec-wasmtime/Cargo.toml, crates/shim-sgx/src/handler/mod.rs, flake.lock, flake.nix, rust-toolchain.toml, src/cli/key/sgx/digest.rs, src/cli/sign.rs
Closes https://github.com/enarx/enarx/pull/2130
~Blocked by #2231~
=> build: update dependencies

.github/workflows/commisery.yml
=> ci: update commisery-action

Cargo.lock, Cargo.toml, src/cli/mod.rs, src/drawbridge.rs
=> build: upgrade clap to 4.0

.github/workflows/release.yml
Push OCI manifest list to GitHub packages.
=> build: push to GitHub Packages

flake.lock, flake.nix
Closes #2304 
Blocking https://github.com/enarx/enarx/pull/2303
=> build(nix): pin `nixify` and update dependencies

build.rs
Fixes: https://github.com/enarx/enarx/issues/2235
=> ci(sgx): test for SGX2 before setting `cfg(host_can_test_sgx)`

Cargo.lock, Cargo.toml, tests/client/util.rs
This will become important as we expand the integration tests.
=> test: parse CLI properly in integration test

Cargo.lock, Cargo.toml, crates/shim-kvm/Cargo.toml, crates/shim-kvm/src/interrupts.rs, crates/shim-kvm/src/lib.rs, crates/shim-kvm/src/main.rs, crates/shim-kvm/src/syscall.rs, crates/shim-sgx/src/lib.rs, crates/shim-sgx/src/main.rs, tests/crates/enarx_syscall_tests/src/bin/exit_one.rs, tests/crates/enarx_syscall_tests/src/bin/exit_zero.rs, tests/crates/enarx_syscall_tests/src/bin/get_att.rs, tests/crates/enarx_syscall_tests/src/bin/read.rs, tests/crates/enarx_syscall_tests/src/bin/read_udp.rs, tests/crates/enarx_syscall_tests/src/bin/readv.rs, tests/crates/enarx_syscall_tests/src/bin/sgx_get_att_quote.rs, tests/crates/enarx_syscall_tests/src/bin/tests.rs, tests/crates/enarx_syscall_tests/src/bin/write_emsgsize.rs, tests/crates/enarx_syscall_tests/src/bin/write_stderr.rs, tests/crates/enarx_syscall_tests/src/bin/write_stdout.rs, tests/crates/enarx_syscall_tests/src/lib.rs
=> feat: remove naked functions

tests/wasm/mod.rs
Also use the signature for the `enarx_deploy` function, so that the tests don't fail, if someone has installed the enarx package and has a signature file at the defined install location.
Before:
test result: ok. 35 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 53.40s
After:
test result: ok. 35 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 44.34s
=> ci: only generate test signature once

src/cli/platform/caching.rs, src/cli/platform/mod.rs, src/cli/platform/sgx/crl.rs, src/cli/platform/sgx/mod.rs, src/cli/platform/snp/crl.rs, src/cli/platform/snp/mod.rs
Refs https://github.com/enarx/enarx/issues/2389
Signed-off-by: Richard Zak <richard@profian.com>
=> feat: crl caching

Cargo.lock, Cargo.toml, crates/shim-sgx/src/handler/gdb.rs, crates/shim-sgx/src/handler/mod.rs, crates/shim-sgx/src/heap.rs
and add the `Access::MMAPPED` flag.
=> feat(sgx): use new mmledger API

.github/workflows/coverage.yml, .github/workflows/sbom_manifest_action.yml, .github/workflows/test.yml, build.rs, crates/shim-kvm/src/debug.rs, crates/shim-kvm/src/main.rs, rust-toolchain.toml, src/backend/mod.rs, src/backend/probe/x86_64.rs, src/backend/sev/data.rs, src/backend/sev/snp/firmware/mod.rs, src/backend/sev/snp/mod.rs, src/backend/sgx/data.rs, src/backend/sgx/ioctls.rs, src/cli/platform/info.rs, src/cli/platform/snp/vcek.rs, src/drawbridge.rs, tests/integration.rs, tests/wasm/mod.rs
=> build: rust toolchain to 2022-12-14

crates/shim-sgx/src/heap.rs
previously userspace could issue `brk` with a very low address and then raise the limit and get memory mapped in that region.
Fixes: https://github.com/enarx/enarx/issues/2403
=> fix(sgx): check `brk` region for lower limit

Cargo.lock, Cargo.toml, src/cli/mod.rs, tests/client/mod.rs, tests/crates/enarx_syscall_tests/Cargo.toml
=> chore: update a couple of deps and remove env_logger

.github/workflows/coverage.yml
=> ci: update cargo-llvm-cov used in coverage

.github/workflows/nix-update.yml
=> ci: enable contents write for nix-update

.github/workflows/nix-update.yml
=> ci: add pull-requests permission to nix-update

crates/shim-kvm/src/main.rs, crates/shim-sgx/src/main.rs
Same attributes, comments, etc.
=> chore(shims): cleanup shim main.rs

flake.lock
=> build: update flake lock 2023-01-03

tests/integration.rs, tests/wasm/mod.rs
This addresses local test deadlock caused by https://github.com/enarx/enarx/pull/2374
See commit message for explanation
=> fix: rework on-disk signature file locking

crates/exec-wasmtime/src/lib.rs, src/cli/mod.rs
=> feat: only log `enarx` workspace events

src/cli/mod.rs
We already have `ENARX_LOG` env variable for verbosity level
=> refactor: remove `-v` argument

Cargo.lock, src/backend/sev/data.rs, src/backend/sev/mod.rs, src/backend/sev/snp/vcek.rs, tests/crates/enarx_exec_tests/Cargo.toml, tests/crates/enarx_exec_tests/src/bin/sev_attestation.rs
Refs:
* SNP companion to https://github.com/enarx/enarx/pull/2393
* https://github.com/enarx/enarx/issues/2389
Signed-off-by: Richard Zak <richard@profian.com>
=> feat: snp backend sends CRL for attestation

tests/client/util.rs
```
$ cargo test --test integration client::full
```
Before: `finished in 60.61s`
After: `finished in 0.72s`
=> test: fix client/full test

crates/exec-wasmtime/src/runtime/mod.rs, crates/shim-kvm/src/allocator.rs, crates/shim-kvm/src/gdt.rs, crates/shim-kvm/src/hostcall.rs, crates/shim-kvm/src/interrupts.rs, crates/shim-kvm/src/start.rs
=> feat(sev): add lazy memory mapping

Cargo.lock, Cargo.toml
=> build(deps): update mmledger, vdso and rcrt1

.github/workflows/release.yml
=> build: bump softprops/action-gh-release workflow version

.github/workflows/release.yml
Signed-off-by: Dmitri Pal <dmitri@profian.com>
=> build: restore softprops/action-gh-release workflow version and set permissions

.codecov.yml, Cargo.lock, Cargo.toml, crates/shared/Cargo.toml, crates/shared/src/lib.rs, crates/shared/src/no_std/cpuid_page.rs, crates/shared/src/no_std/mod.rs, crates/shared/src/std/cpuid_page.rs, crates/shared/src/std/mod.rs, crates/shim-kvm/Cargo.toml, crates/shim-kvm/src/lib.rs, crates/shim-kvm/src/snp/cpuid_page.rs, src/backend/sev/builder.rs, src/backend/sev/cpuid_page.rs
=> feat: factor out cpuidpage to a shared crate

helper/release_enarx.sh
=> fix: bring release helper script up to date

src/cli/platform/sgx/crl.rs, src/cli/platform/snp/crl.rs
=> chore: use atomic rename for CRLs

crates/shim-kvm/src/exec.rs, crates/shim-kvm/src/gdt.rs, crates/shim-kvm/src/lib.rs
=> feat(shim-kvm): move consts to lib.rs

src/backend/kvm/mem.rs
=> chore(backend/kvm): remove underscore

crates/shim-kvm/src/allocator.rs, crates/shim-kvm/src/gdt.rs, crates/shim-kvm/src/lib.rs, crates/shim-kvm/src/start.rs
- introduce a global allocator
- reorganize GDT init
* drop global variables
* use Box
* stack pointer as argument
=> feat(shim-kvm): global alloc and gdt changes

tests/crates/enarx_wasm_tests/src/bin/connect.rs, tests/crates/enarx_wasm_tests/src/bin/listen.rs
=> test: remove wasi_ext feature

Cargo.lock, src/backend/mod.rs, src/cli/platform/info.rs
Formatted the CPU info output for the json option.
Fixes: https://github.com/enarx/enarx/issues/1962
=> feat(cli): Regularize enarx cpu info output

src/backend/mod.rs, src/backend/sev/data.rs, src/backend/sgx/data.rs, src/caching.rs, src/cli/mod.rs, src/cli/platform/mod.rs, src/cli/platform/sgx/crl.rs, src/cli/platform/sgx/mod.rs, src/cli/platform/sgx/register.rs, src/cli/platform/sgx/tcb.rs, src/cli/platform/snp/crl.rs, src/cli/platform/snp/mod.rs, src/cli/platform/snp/update.rs
=> feat: improve CLI usability relating to cache updating

flake.lock, flake.nix
=> chore: nix fixup

crates/sallyport/src/guest/alloc/phase_alloc.rs, crates/sallyport/src/lib.rs, flake.lock, flake.nix, rust-toolchain.toml
=> build: bump Rust toolchain to nightly-2023-04-15

.github/workflows/coverage.yml, .github/workflows/sbom_manifest_action.yml, .github/workflows/test.yml
=> build: sync workflow files to current rust-toolchain

flake.lock, flake.nix
=> build: nixify repo moved

docs/Install.md
Fixes https://github.com/enarx/website/issues/140
=> Add KVM device permissions to Install guide

tests/exec/mod.rs
=> test: disable exec tests on nil backend

Cargo.lock, Cargo.toml, crates/exec-wasmtime/src/runtime/identity/mod.rs, crates/exec-wasmtime/src/runtime/identity/pki.rs, src/backend/sev/data.rs, src/backend/sev/mod.rs, src/backend/sgx/attestation.rs, src/backend/sgx/mod.rs, src/caching.rs, src/cli/key/sev/create.rs, src/cli/key/sev/sign.rs, src/cli/key/sgx/digest.rs, src/cli/platform/sgx/tcb.rs, src/cli/sign.rs, tests/crates/enarx_exec_tests/src/bin/sev_attestation.rs, tests/crates/enarx_exec_tests/src/bin/sgx_attestation.rs, tests/crates/enarx_exec_tests/src/lib.rs
Attempting to update some Rust Crypto dependencies separately since https://github.com/enarx/enarx/pull/2560 didn't go so well.
=> chore(deps): update some rust crypto dependencies
