.travis.yml
`enarx/enarx` now has a Travis config! Resolves #3.
Tagging @npmccallum for review.
=> Add existing CI tests from other Enarx repos

sgx-types/src/secs.rs
These tests are outdated now that the `paging` crate exists.
=> Remove outdated alignment and size tests in sgx-types/secs.rs

sgx-types/src/lib.rs
This makes it both clearer what testaso!() does and it provides separate
output for each kind of test during test execution.
=> Split testaso!() into three test functions

sgx-sys/src/lib.rs, sgx-traits/src/lib.rs, sgx-types/src/lib.rs
This removes the lifetime enforcement I thought we could make work, but realized we can't.
=> Clean up Offset type

sgx-sys/src/lib.rs
This surfaces the errors when tests fail.
=> Use .unwrap() in tests instead of assert!(.is_ok())

.travis.yml
=> Speed up Travis tests by splitting cargo audit into its own task

sgx-crypto/src/lib.rs, sgx-types/src/attr.rs, sgx-types/src/isv.rs, sgx-types/src/lib.rs, sgx-types/src/misc.rs, sgx-types/src/page.rs, sgx-types/src/secs.rs, sgx-types/src/sig.rs, sgx-types/src/ssa.rs, sgx-types/src/tcs.rs
Fixes #28 and fixes #58 for `sgx-types` and `sgx-crypto` crates (no other crates were modified). 
Added `#![deny(missing_docs)]` to these crates, so it is possible that the requirements are too verbose at this point, for example in `pub struct Gpr` in `sgx-types/src/ssa.rs` where all registers have to be labeled. 
Edit: Also added the licensing info to each file in these two crates.
=> Add documentation for SGX in sgx-crypto and sgx-types.

CONTRIBUTING.md
Moving things around so we eventually have:
enarx/enarx.github.io/CONTRIBUTING.md --> https://github.com/enarx/enarx/wiki/How-to-contribute
enarx/enarx/CONTRIBUTING.md --> https://github.com/enarx/enarx/wiki/How-to-contribute
Companion PR to https://github.com/enarx/enarx.github.io/pull/23.
=> Update CONTRIBUTING.md to point to the How to contribute page

.travis.yml, hooks/pre-push, hooks/pre-push.d/cargo-audit, hooks/pre-push.d/cargo-fmt, hooks/pre-push.d/cargo-test
This PR moves all the tests we were previously running in Travis to shell scripts within the `hooks` folder. This allows us to run these tests before push time, ensuring that _every_ commit passes tests locally before being pushed remotely.
Since the tests now exist in their own file, Travis has also been updated to call that file (for organization). To add new tests, we should only need to add a new shell script to `hooks/pre-push.d`, and they will run both pre-push and on Travis.
Resolves #43.
=> Implement Travis tests as git pre-push hooks

.github/ISSUE_TEMPLATE/conferences.md, .github/ISSUE_TEMPLATE/questions.md, .github/ISSUE_TEMPLATE/technical.md
Create basic templates for asking questions and submitting technical issues. For now, there's little structure enforced, but this can change as we recognize potential automation opportunities.
For Tech issues, I've included some boilerplate reminders about project organization. These can be removed if we find a better solution -- I was thinking it would make sense to link to an "Issue etiquette" section of the wiki from the issue creation screen. See #155 for more.
The PR also includes a small formatting/description fix to make the Conferences template feel consistent with the rest.
Resolves #38.
=> Implement issue templates for "Tech" and "Questions"

iocuddle-sgx/src/lib.rs, sgx-types/src/secs.rs
I had to remove the `pub const SIZE_MAX`, since you can't assign the result of a function to a `const`. I checked the results of the function with what `sgx-show` produces for `SgxCaps` for 64bit and it was correct.
Fixes #116.
=> Query CPUID to get enclave max size in sgx-types/src/secs.rs

.cargo/config, .travis.yml, README.md, iocuddle-sgx/Cargo.toml, sev/Cargo.toml, sgx-crypto/Cargo.toml
for openssl, turn on the vendored feature, which propagated to
openssl-sys
Fixes https://github.com/enarx/enarx/issues/6
=> use musl as default build target via .cargo/config

README.md
Update README, using the one initially created for the enarx.github.io repo.
Closes #137.
There's also a PR to update the README in the other repo, enarx/enarx.github.io#25.
=> Update README using the one from the enarx.github.io repo

README.md
This pull request is accompanied by a corresponding change to the Enarx wiki page titled ["How to contribute"](https://github.com/enarx/enarx/wiki/How-to-contribute). Since setting up a development environment is now covered by that wiki page change (see below), let's remove the duplicated information recorded in the README so we only maintain it in one place (the wiki) and have the README point readers to that wiki page.
This closes #173
**Before merging this if accepted**: since it doesn't look like we can submit pull requests against the wiki, here is a diff of my changes to that wiki page for review in the form of a git patch: https://pastebin.com/9Xy9uATh
If all is accepted, that patch can be downloaded like this:
```bash
$ cd ~/src/enarx-wiki
$ curl https://pastebin.com/raw/9Xy9uATh …
```
=> Guide readers to "How to contribute" on the wiki

.travis.yml, hooks/pre-push.d/cargo-clippy, linux-errno/src/lib.rs, linux-syscall/src/lib.rs, sev/src/certs/ca/cert/v1.rs, sev/src/certs/ca/mod.rs, sev/src/certs/mod.rs, sev/src/certs/sev/mod.rs, sev/src/certs/util.rs, sev/src/firmware/linux.rs, sev/src/lib.rs, sgx-show/src/data/cpuid.rs, sgx-show/src/exec.rs, sgx-show/src/main.rs
This addresses one part of https://github.com/enarx/enarx/issues/153 . It doesn't turn on `#![deny(missing_docs)]` because I don't have the necessary context to add all the missing docs.
=> Add clippy hook

enarx-keepmgr/Cargo.toml, enarx-keepmgr/src/access.rs, enarx-keepmgr/src/binary.rs, enarx-keepmgr/src/drivers/debug.rs, enarx-keepmgr/src/drivers/mod.rs, enarx-keepmgr/src/main.rs, enarx-keepmgr/src/span.rs
This is a stab at a high-level interface for bridging both SGX and SEV keeps. I know I'm missing stuff. And I'm sure I've gotten stuff wrong. But this is enough to start talking about.
In particular, this doesn't handle the multi-threaded case at all. Ideally, we will start a keep with a single thread and it can add more. We don't currently have a facility to handle multiple threads with this API.
Comments welcome!
=> First pass on traits

.travis.yml, hooks/pre-push.d/cargo-edition-test
Resolves #161.
An extension of the `Cargo.toml` license test from #162. If that changes upon merge, changes from it should be echoed here.
=> Test all Cargo.toml files for edition = "2018"

iocuddle-sgx/src/lib.rs, sgx-types/src/secs.rs
This function is technically unsafe because it does not check if the
instruction is available before issuing it. This could result in a crash
on some very old CPUs. However, the only modern context where it could
crash is environments like SGX or some virtualized CPUs. But even in
these contexts, it is common to trap and emulate the instruction.
Therefore, it is common practice to ignore the test to see if the
instruction is available and just issue it anyway. For this reason, we
are marking this function as safe. For more background to the state of
CPUID in Rust, see:
https://github.com/rust-lang/rust/issues/60123
=> Mark secs::Spec::max_enc_size() as safe

sgx-types/src/secs.rs, sgx-types/src/ssa.rs
Fixes #200 
@npmccallum Let me know what you think of this or if further changes are needed. 
I added the 4096 alignment requirement to `SSA` because the documentation says that the end of the `GPR` section (the last section in `SSA`) must be aligned to the end of a page. For this reason, if the size of `SSA` is not a multiple of 4096, `SSA::frame_size()` returns `None`.
I wasn't sure whether we want a `secs::Spec::ssa_size()` function, so I added one that just calls the one from `SSA`.
I also didn't see any code that uses the SSA frame size and explicitly expects it to be in bytes; if I missed any of these that you know of, please let me know and I'll update them. [This line](https://github.com/enarx/enarx/blob/master/iocuddle-sgx/src/lib.rs#L140) in `iocuddle-sgx/src/lib.rs` might be …
=> Measure SSA frame size in 4k pages

hooks/pre-push.d/crate-license-test
First, use the top-level LICENCE file as the canonical license. This
avoids network access during tests.
Second, use diff instead of shell equality to test for differences in
the texts. This allows us to ignore whitespace and newline changes. It
also has the advantage of showing the actual differences during a
failure.
Third, shorten the error message. Not much more needs to be said because
we dump the actual file diff to the screen.
=> Improve the per-crate license test

LICENSE, enarx-keepmgr/LICENSE, intel-types/LICENSE, iocuddle-sgx/LICENSE, iocuddle/LICENSE, linux-errno/LICENSE, linux-syscall/LICENSE, sev/LICENSE, sgx-crypto/LICENSE, sgx-show/LICENSE, sgx-types/LICENSE, testing/LICENSE, vmsyscall/LICENSE
The original crate-level license test was designed to ensure our license files matched the reference copy found at http://www.apache.org/licenses/LICENSE-2.0.txt.
However, we've since changed that test to only check against the top-level project license in #220. Additionally, as highlighted in #219, the `apache.org` reference version doesn't match the Github-provided Apache 2.0 on whitespace. This means that any Github-generated files will fail the test unnecessarily.
Since we're no longer checking against the reference license on `apache.org`, I've changed all our license files to match the one Github provides. This should mean any Github-generated Apache licenses shouldn't cause the test to fail.
Resolves #219.
=> Replace LICENSE files w/ Github-provided version

.cargo/config, Cargo.toml, hooks/pre-push.d/cargo-audit, hooks/pre-push.d/cargo-clippy, hooks/pre-push.d/cargo-edition-test, hooks/pre-push.d/cargo-fmt, hooks/pre-push.d/cargo-test, hooks/pre-push.d/toml-license-field-test, iocuddle-sgx/Cargo.toml, sev/Cargo.toml, sgx-crypto/Cargo.toml
I've come up with a way to link a binary with custom entry point on musl
libc. So I think I've solved our linking problems for now. This means we
can have the workspace back and cargo should work out of the box like
normal.
=> Long live the workspace!

.github/workflows/enarx-standard.yml
This PR enables Github Actions by adding a basic workflow. For now, it runs two steps that succeed and fail, respectively (with the failure allowed). This is designed to sanity-check Actions' behavior before we begin migrating our full test suite over.
Resolves #235.
=> Enable and sanity-check Github Actions

.github/ISSUE_TEMPLATE/meta.md
This goes along with a new `meta` label.
Please pay _close_ attention to the `To do` section. We should be on the same page about the list formatting.
Resolves #199.
=> Implement a template for meta issues

sgx-types/src/lib.rs, sgx-types/src/report.rs
Here is the basic memory layout for Report. I can add functionality as needed.
=> Add report module to sgx-types

.github/workflows/enarx-rust.yml, hooks/pre-push.d/cargo-fmt, hooks/pre-push.d/cargo-test
This PR holds our first substantive migration of CI testing from Travis to Github Actions. The `enarx-rust.yml` workflow will hold all our Rust testing; currently, it runs `cargo fmt` and `cargo test`. Those same tests have been removed from Travis' testing loadout.
@npmccallum and I have also written and deployed a testing container to [quay.io](https://quay.io/repository/enarx/fedora-test) that this config makes use of. All tests are run inside the container.
Part of the point of this PR is to understand how Actions behaves when dealing with our contribution workflow: making a pull request from a personal fork. Have a look around and see how the tests behave!
Resolves #244 and resolves #245.
=> Implement Rust testing in a container on Github Actions

hooks/pre-push, hooks/pre-push.d/cargo-edition-test, hooks/pre-push.d/crate-license-test, hooks/pre-push.d/eof-newline-test, hooks/pre-push.d/rs-spdx-license-test, hooks/pre-push.d/toml-license-field-test
- harden against whitespaces in path names
- fixed eof-newline check
- run all tests in `pre-push`
- set -o pipefail
Still fails for newline in path names, but that is crazy. :-P
=> Fix shell scripts

hooks/pre-push.d/eof-newline-test, hooks/pre-push.d/rs-spdx-license-test
Tryting to run the hooks in a local development repository yielded
errors for dependency crates which reside in the individual crate's
target directory. This change makes the hook prune these directories.
=> hooks/pre-push: ignore all target directories

.github/workflows/enarx-rust.yml, .travis.yml, hooks/pre-push.d/cargo-audit
Checks off `cargo-audit` in #246.
=> Migrate cargo-audit testing to GH Actions

.github/workflows/enarx-rust.yml, .travis.yml
Adds another step to GHA's Rust build-test step with SEV-specific features.
Related: #246
=> Run cargo test with SEV-specific features

.github/workflows/enarx-rust.yml, .travis.yml, hooks/pre-push.d/cargo-clippy
Checks off `cargo clippy` in #246.
=> Migrate rust-clippy test to GH Actions

.github/workflows/miscellaneous.yml, .tests/misc-diagrams, docs/attestation/Makefile
Closes #256 
This pull request adds a test to our GitHub Actions suite to confirm that the diagrams in a pull request are always up-to-date.
This ended up being a little more complex than I initially thought, due to how certain approaches made the test quite brittle.
**Idea:** just compare the (c/m)times of the files
**Why doesn't it work:** Git doesn't necessarily track this ([and after Googling why](https://stackoverflow.com/questions/1964470/whats-the-equivalent-of-use-commit-times-for-git/1964508#1964508), I tend to agree with that decision). So, when our CI clones the repo to check out the files, the (c/m)times are simply the time of the clone, and if all the times are the same, then this test wouldn't make sense.
**Idea:** force `make` to regenerate the diagrams, and if the binary …
=> Ensure diagrams are always up-to-date

Cargo.toml, sev-show/Cargo.toml, sev-show/LICENSE, sev-show/src/main.rs, sev-show/src/show.rs
Closes #205.
Although it's likely this kind of platform discovery will be consolidated in the future, we should have something like `sgx-show` for SEV.
I believe I captured all of the SEV-related information described in the AMD Developer's Manual, but if I've missed some I will go back and add them.
Quick example:
```
✔ AMD CPU
✔ Processor is known to have microcode that supports SEV: AMD EPYC 7251 8-Core Processor                 
✔ SME support
✔ Physical address bit reduction: 5
✔ C-bit location in page table entry: 15
✔ SEV support
✔ Number of encrypted guests supported simultaneously: 15
✔ Minimum ASID value for SEV-enabled, SEV-ES disabled guest: 1
✔ SEV-ES support
✔ Page Flush MSR available
✔ /dev/sev device special file exists
✔ File is readable by user
✔ File is writable by user …
```
=> Implement an interim sev-show

sev/Cargo.toml, sev/tests/api.rs
Resolves #288. Checks off appropriate task in #105.
This feature is intended to be used for testing the SEV hardware platform only.
=> Create a Cargo feature enabling dangerous SEV hardware tests

sev/tests/api.rs
The bad syntax didn't fail when not on SEV (so our CI didn't catch it), but things started acting up when on SEV hardware. This should fix it.
=> Fix conditional compilation of dangerous tests

Cargo.toml, crt0stack/examples/reader.rs, crt0stack/src/lib.rs, vdso/Cargo.toml, vdso/LICENSE, vdso/src/lib.rs
Most of the preparatory work goes into the `crt0stack` crate. We need the ability to instantiate the `crt0stack::Reader` from the POSIX `environ` pointer. Then we can use it to find the vDSO and search it for symbols.
=> Add the vdso crate

Cargo.toml, sev-types/Cargo.toml, sev-types/LICENSE, sev-types/src/lib.rs, sev-types/src/platform.rs
We have a lot of SEV work in flight that would benefit from a centrally shared, iteratively developed package full of type-safe SEV types.
Let's add one to avoid duplicating types across SEV work items.
Just for inspiration of how things can be arranged as people add to this: I'm currently sitting on a much larger branch full of other types to merge, but my module structure is organized like this (this can be subject to change as types are added):
```
src/
├── command
│   ├── buffer.rs
│   └── mod.rs
├── guest.rs
├── lib.rs
└── platform
├── mod.rs
└── x86.rs
```
=> Create sev-types crate

sev-show/Cargo.toml, sev-show/src/main.rs, sgx-show/Cargo.toml, sgx-show/src/exec.rs
Resolves #315. #297's dependency license check should be unblocked after this merge.
=> Replace `colored` with MIT-licensed `colorful`

.github/workflows/cargo.yml, deny.toml
Resolves #211. Requires https://github.com/enarx/docker-fedora-test/pull/6 to be merged and built on quay.io.
=> Test dependencies for Apache 2.0-compatible licenses

cc, enarx-keep-sgx/src/main.rs
Fedora now ships the naked python command in a separate package. We'll just
name the version explicitly.
=> Fix build in the container

sev-types/Cargo.toml, sev-types/src/command/code.rs, sev-types/src/command/mod.rs, sev-types/src/lib.rs
These are embedded in the command struct that the SEV API expects so that the firmware can know what action to take and how it should interpret the contents of the command buffer.
`src/command/mod.rs` is basically empty but will contain types and other submodules in a future patch set.
These will be particularly useful for a future PR that I want to base `iocuddle-sev` on.
=> Add SEV API command codes (AKA command IDs)

enarx-keep-sgx/Cargo.toml, enarx-keep-sgx/src/builder.rs, enarx-keep-sgx/src/map.rs
Before this, libc did not export these flags for musl. Starting with libc 0.2.68 these flags are now exported.
Also, all I had to do to get these changes was run `cargo update` but I was expecting to see something change in a Cargo.lock... anyone have any thoughts? Otherwise people with this repo already checked out may need to run `cargo update` manually and if I had no background knowledge of this commit getting merged I would probably be confused.
Closes #239 
Closes #339
=> Use upstream libc mmap flags

sev/Cargo.toml, sev/src/certs/sev/cert/v1/body/mod.rs, sev/src/firmware/linux.rs, sev/src/launch.rs, sev/src/lib.rs, sev/src/session/mod.rs, sev/tests/api.rs
The first type that went into `sev-types` was the firmware version struct and so a debt issue was filed to update `sev` to use the definition exported by `sev-types`.
Closes #323.
=> Use the new Version struct exported by sev-types

enarx-keep-sgx-shim/link.json
Otherwise the test suite will segfault and there's no real way to skip this since the shim presents itself as *the* entry point, even for `cargo test`
On non-Intel hardware:
Before the patch:
```bash
bash-5.0# cargo test
Finished test [unoptimized + debuginfo] target(s) in 0.02s
Running /root/enarx/target/x86_64-unknown-linux-musl/debug/deps/enarx_keep_sgx_shim-328c79c1e5d7f125
error: test failed, to rerun pass '--bin enarx-keep-sgx-shim'
Caused by:
process didn't exit successfully: `/root/enarx/target/x86_64-unknown-linux-musl/debug/deps/enarx_keep_sgx_shim-328c79c1e5d7f125` (signal: 11, SIGSEGV: invalid memory reference)
```
After the patch:
```bash
bash-5.0# cargo test
Compiling enarx-keep-sgx-shim v0.1.0 (/root/enarx/enarx-keep-sgx-shim)
Finished test [unoptimized + debuginfo] …
```
=> Conditionally remove SGX shim entry point if not on SGX-enabled hardware

sgx-types/src/ssa.rs
This will allow us to transmute it to a different type when we need to.
Fixes #355
=> Make reserved field public in SSA

.automation/copy-issue-labels-to-pr, .github/mergeable.yml, .github/workflows/automation-pr.yml
This pull request implements a bot that automatically copies labels to a pull request from a linked issue. It is meant to be the first step into a much larger automation framework for Enarx.
It uses the [`PyGithub`](https://github.com/PyGithub/PyGithub) library for the bulk of its logic. Scripts are run inside Enarx's testing container, and it uses the ephemeral [`GITHUB_TOKEN`](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token) to make authenticated API v3 calls.
It will only mirror an approved subset of the labels present on the linked issue; currently, I've proposed this set as `["amd sev","documentation","ibm pef","infrastructure","intel sgx","wasm"]`. Comments welcome.
You can see an example run of the bot …
=> Sorting Hat: Copy labels to pull requests from linked issues

vmsyscall/Cargo.toml, vmsyscall/src/bootinfo.rs, vmsyscall/src/lib.rs, vmsyscall/src/memory_map.rs
This will allow us to more easily parallelize our efforts to porting in Harald's work. There will be two projects consuming this common core:
* 'vmrun' AKA enarx-keep-sev
* 'kernel' AKA enarx-keep-sev-shim
=> Add common code that is shared between SEV keep and shim

.cargo/config, Cargo.toml, crt0stack/examples/reader.rs, crt0stack/src/lib.rs, payload/Cargo.toml, payload/LICENSE, payload/link.json, payload/src/main.rs, vdso/src/lib.rs
This PR contains the intended payload for a SEV/SGX demo. In the long term it will be replaced with our WASM runtime. But here's enough for a demo.
=> Add a target payload

enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs, nolibc/src/lib.rs
This is a draft. In particular, it needs some help with casting pointers in a safe and correct way.
Resolves #375 and resolves #376
=> Add readv and writev syscalls for SGX

enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs
Here's a first stab, not really sure if this is the right approach... Here are some notes:
1. Assuming that the array is a heap, all I am doing is incrementing index and keeping track of where we are. The index of the array is the *address* that the program is requesting but while incrementing the index, I am not rounding it to the nearest page size. Also, there's no state maintained to give memory back to the heap.
2. I am not sure if I am using size_hint() correctly - it actually returns the same value for upper and lower limit probably because HEAP is static ? It does solve my purpose of finding the upper bound though.
3. The function returns u64 but that probably ok for now since the call in the demo app won't fail ? (The man page says it should return -1)
=> Implement a rudimentary brk

.automation/add-to-project-when-labeled, .github/workflows/automation-label.yml
This action expands on the groundwork laid in #360. It acts on the `labeled` event (currently only for `issues`) and adds to a project based on the label added. Here's the mapping I've proposed:
```
"infrastructure": "Infrastructure",
"amd sev": "SEV",
"intel sgx": "SGX",
"wasm": "WebAssembly",
```
This is related to #377, but it doesn't implement this functionality on PRs yet (currently blocked by the `GITHUB_TOKEN` behavior on PR events). When that's done, #377 can be considered closed.
=> Add issues to projects when labeled

.github/workflows/miscellaneous.yml, .tests/misc-consistent-linked-issues
Github currently does not link issues when referred to in commit messages, even if it uses the same [closing keyword syntax](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) as in a PR description.
To ensure all issues that a PR's author meant to be linked get linked, this test ensures that any issues linked to in commits are also linked in the PR description. If there are any missing, it'll tell the author how to link them.
Resolves: #428
=> Test consistency of linked issues between commits and PR

enarx-keep-sgx-shim/src/handler.rs
Fixes #337 
By definition, resolves the odd situation described in the issue above in which a proxy of the exit syscall returns. Anything else that triggers `handler.attacked()` will also call this exit loop.
=> Ensure no enclave re-entry after sys_exit

span/src/lib.rs, span/src/line.rs, span/src/span.rs
This type is similar to core::ops::Range, but is not an iterator and
therefore can implement Copy. Additionally, we make sure all exported
items are documented.
Fixes: #348
=> Add Line type to the span crate

sgx-crypto/src/lib.rs, sgx-types/src/page.rs, sgx-types/src/ssa.rs, sgx-types/src/tcs.rs
We are going to move to a strategy of copying structs into page-aligned,
paged-size data types before loading. This means that we don't need to
serialize the types directly.
=> Remove AsRef implementations

crt0stack/examples/reader.rs, crt0stack/src/lib.rs
The test assumed the test has no arguments.
Check against the actual number of arguments.
```console
❯ cargo -v test -p crt0stack reader_real -- --nocapture --test-threads=1
Fresh enumerate v0.1.0 (/home/harald/git/enarx/enarx/enumerate)
Fresh crt0stack v0.6.0 (/home/harald/git/enarx/enarx/crt0stack)
Finished test [unoptimized + debuginfo] target(s) in 0.02s
Running `/home/harald/git/enarx/enarx/target/x86_64-unknown-linux-musl/debug/deps/crt0stack-0ca48c4154260701 reader_real --nocapture --test-threads=1`
running 1 test
test tests::reader_real ... thread 'main' panicked at 'assertion failed: `(left == right)`
left: `4`,
right: `1`', crt0stack/src/lib.rs:877:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
FAILED
failures:
failures:
tests::reader_real
test …
```
=> crt0stack/src/lib.rs: fix `reader_real()` test

sev-types/src/lib.rs, sev-types/src/platform.rs, sev/src/lib.rs, sev/tests/api.rs
Move Build struct from 'sev' into 'sev-types' 
Closes #446
=> move Build struct to sev-types

.automation/add-to-project-when-labeled
There were two small `KeyError` bugs with the project automation bot raised in #483:
- The bot didn't know what to do if an issue was labeled with a label it didn't recognize
- The bot was grabbing the wrong project due to a typo
Looking at those, I also noticed a third one:
- If a user manually added an issue to both the project and its corresponding label at the same time, the bot would fail due to Github's API returning that the card was already in the project.
This PR resolves all the above bugs by improving the bot's error handling.
Resolves: #483
=> Better error handling for project automation bot

sev/src/firmware/linux.rs
otherwise pek_csr fails
```
[pid 101835] openat(AT_FDCWD, "/dev/sev", O_RDONLY|O_CLOEXEC) = 3
[pid 101835] ioctl(3, SEV_ISSUE_CMD, 0x7f7d0c8f5fc0) = -1 EPERM (Operation not permitted)
```
=> sev/src/firmware/linux.rs: open("/dev/sev") RW

Makefile.toml, enarx-keep-sev/Cargo.toml, enarx-keep-sev/LICENSE, enarx-keep-sev/src/main.rs
If this PR is too fine-grained let me know. I think this is as far as I can get without duplicating code from #416.
This just adds the crate as a basis for the rest of the code that is transitioning off of `demo2020`. The keep is pretty much a "stub" for now, but following PRs will add more functionality.
=> Introduce enarx-keep-sev

Makefile.toml, enarx-keep-sev-shim/.cargo/config, enarx-keep-sev-shim/Cargo.toml, enarx-keep-sev-shim/LICENSE, enarx-keep-sev-shim/asm/rcrt1.c, enarx-keep-sev-shim/asm/start.S, enarx-keep-sev-shim/asm/utils.s, enarx-keep-sev-shim/build.rs, enarx-keep-sev-shim/link.json, enarx-keep-sev-shim/src/asm.rs, enarx-keep-sev-shim/src/main.rs, enarx-keep-sev-shim/src/no_std.rs
Boot to rust in kernel virtual address space with the important
registers initialized.
This just adds the crate as a basis for the rest of the code that is transitioning off of demo2020. The keep is pretty much a "stub" for now, but following PRs will add more functionality.
=> Create enarx-keep-sev-shim binary crate

sallyport/src/lib.rs
Useful, if you want to precalculate stuff without having a Block
instance.
=> sallyport: add a const fn to get the Block.buf size

enarx-keep-sev-shim/Cargo.toml, enarx-keep-sgx-shim/Cargo.toml
Minimize the code size and maximize optimization for the shims.
enarx-keep-sgx-shim:
Binary size before (stripped): 316704
Binary size after  (stripped):  22112
=> Turn on LTO for the shims

enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs, sgx-types/Cargo.toml, sgx-types/src/ssa.rs
This relates to #423 (though more changes may be needed to fully resolve that issue - @npmccallum were you thinking we should make additional changes in SGX based on the `memory` crate?).
=> Use memory::register::Register to wrap register types

enarx-keep-sev-shim/build.rs
also, there is no more layout.ld linker script
=> enarx-keep-sev-shim: rebuild on link.json changes

enarx-keep-sgx-shim/src/handler.rs
Fixes #552
```
[connorkuehl@coffeelake enarx-keep-sgx]$ cargo run -- --shim ../enarx-keep-sgx-shim/target/x86_64-unknown-linux-musl/debug/enarx-keep-sgx-shim --code ../payload/target/x86_64-unknown-linux-musl/debug/payload
Finished dev [unoptimized + debuginfo] target(s) in 0.01s
Running `target/debug/enarx-keep-sgx --shim ../enarx-keep-sgx-shim/target/x86_64-unknown-linux-musl/debug/enarx-keep-sgx-shim --code ../payload/target/x86_64-unknown-linux-musl/debug/payload`
arg: "/init"
env: "LANG=C"
aux: ExecFilename("/init")
aux: Platform("x86_64")
aux: Uid(1000)
aux: EUid(1000)
aux: Gid(1000)
aux: EGid(1000)
aux: PageSize(4096)
aux: Secure(false)
aux: ClockTick(100)
aux: Flags(0)
aux: HwCap(0)
aux: HwCap2(0)
aux: PHdr(35184376283200)
aux: PHent(56)
aux: PHnum(10)
aux: Random([4, 251, 33, …
```
=> Don't negate syscall arguments

enarx-keep-sev/src/vm.rs
Foiled by my own hubris! I should have tested for this in my KVM PR after I switched up how the code called `mmap`.
MAP_PRIVATE or MAP_SHARED must be included in the mmap() flags otherwise it will return EINVAL.
We need at least PROT_WRITE to write the page tables into the mmap'd memory region.
=> Fix mmap flags for enarx-keep-sev

Makefile.toml, deny.toml, keep-runtime/.cargo/config, keep-runtime/Cargo.toml, keep-runtime/LICENSE, keep-runtime/fixtures/no_export.wat, keep-runtime/fixtures/return_1.wat, keep-runtime/fixtures/wasi_snapshot1.wat, keep-runtime/link.json, keep-runtime/src/main.rs, keep-runtime/src/workload.rs
This is my attempt to follow up on #139. Besides the tooling updates and minor enhancements, I changed the workload format to be simpler (b6f7ce91ac127f7848ed3ab7042a3475e84c99f9), which might need some discussion around enarx/rfcs#17. Currently I am thinking to include the following in a workload package:
- a Wasm module
- command-line arguments
- environment variables
- assets that are stored in a fixed directory (within a Keep), which can be [preopened](https://docs.rs/wasmtime-wasi/0.16.0/wasmtime_wasi/struct.WasiCtxBuilder.html#method.preopened_dir) before calling the module
=> wasm: update keep-libruntime and keep-runtime

enarx-keep-sgx-shim/src/start.S
This relates to #334 , but the xCPU state will also need to be saved and restored before that issue can be closed. This is a preliminary PR to #427 , which I'll rebase onto this if this can be merged.
=> Clear extended CPU state on enclave entry and exit

enarx-keep-sev/Cargo.toml, enarx-keep-sev/src/main.rs, enarx-keep-sev/src/vm.rs, enarx-keep-sev/src/x86_64.rs
In doing so, we can avoid returning a `Result` whose `Err` type is a heap-allocated trait object.
This PR also updates some of the guest physical address constants to being `PhysAddr` types so we don't have to `try_new`/`try_from` them with the possibility of an Error.
While we're in there, acknowledge some compiler warnings about unused variables. They'll be used in future PRs.
Closes #556
=> Map kvm_ioctl::Errors into io::Errors

attestation-types/Cargo.toml, attestation-types/LICENSE, attestation-types/src/lib.rs, attestation-types/src/quote.rs, attestation-types/src/report.rs, attestation-types/src/ti.rs
A few notes about the tricky parts of implementing the `Quote` struct:
- According to the documentation ([A.4, Table 8](https://download.01.org/intel-sgx/dcap-1.0/docs/SGX_ECDSA_QuoteGenReference_DCAP_API_Linux_1.0.pdf)),The `QEAuth` portion has 1) a `size` field and 2) a `data` [field](https://github.com/enarx/enarx/compare/master...lkatalin:quote-type?expand=1#diff-e7fe996c9d1d239623aac2a380efaa54R38) whose size is determined by the `size` field. I couldn't find a way to do this without making the size a `const`. Currently it's set to `0`, a valid value. 
- Maybe the `data` field should be a vector, with a method that checks that the length of the vector matches the `size` field?
- It's clear that the `vendor ID` used in this `Quote` struct (`939A7233F79C4CA9940A0DB3957F0607` for Intel) …
=> Add quote module to sgx-types

Makefile.toml, integration-tests/Cargo.toml, integration-tests/LICENSE, integration-tests/Makefile.toml, integration-tests/build.rs, integration-tests/src/main.rs, integration-tests/tests/sgx_payload.rs
It runs when ~~`cargo make test`~~ `cargo make integration` or ~~`cargo make ci-flow`~~ `cargo make integration-ci` are invoked.
Resolves #522 .
This PR does the following:
- Creates a new ~~`tests/`~~ `integration-tests/` crate for top-level tests for our emulated workspace. Currently there is one file included `sgx_payload.rs`, which checks for correct binary paths and runs the SGX payload.
- Adds new tasks to `Makefile.toml` to ensure that crates are built before the tests in ~~`tests/`~~ `integration-tests/` are run. Currently this means *all* tests run after all builds, as per [this discussion](https://github.com/sagiegurari/cargo-make/issues/429). ~~Some default `cargo make` tasks are overwritten here to ensure that `cargo make test` and `cargo make ci-flow` actually call our …
=> Add running SGX payload to test suite

keep-runtime/Cargo.toml, keep-runtime/build.rs, keep-runtime/src/main.rs, keep-runtime/src/workload.rs
The new API no longer transparently handles the text format (.wat) WebAssembly files.  This converts the .wat files in our examples to the binary format (.wasm) at build time.
See also #570.
=> keep-runtime: update to wasmtime 0.18 API

sevctl/src/main.rs
`⮤` looks nice, but is not included in many fonts, yet.
`⬑` seems to be included in way more fonts.
This patch also adds a legend and a `slash-through` for invalid
signatures (for the color blinded).
Fixes: https://github.com/enarx/enarx/issues/525
=> sevctl: better output for `verify`

enarx-keep-sgx-shim/src/entry.rs, enarx-keep-sgx-shim/src/start.S
The stack was properly aligned. However, Rust presumed that the stack
was aligned before the call instruction was issued. Because we were
using jmp instead of call, this meant that the output from Rust made
incorrect assumptions about the stack alignment, leading to crashes
later. We solve this by using call rather than jmp so that the Rust
assumptions are correct. This removes the need for a manually aligned
crt0stack which worked around this issue.
There are still some other issues in the crt0stack that need to be
resolved (Harald has fixes for them). However, they don't currently
trigger crashes.
Fixes: #385
=> Fix a crasher

sev/Cargo.toml, sev/src/firmware/linux/ioctl.rs, sev/src/firmware/linux/mod.rs, sev/src/firmware/mod.rs, sev/src/firmware/types.rs, sev/tests/api.rs
Related: #281
Related: #112 
This PR establishes a basis for additional types and ioctls to be implemented for SEV, with feedback addressed from #202 where applicable.
Tested on Rome:
```
[connorkuehl@rome sev]$ cargo test --all-features
Compiling sev v0.1.0 (/home/connorkuehl/enarx/sev)
Finished test [unoptimized + debuginfo] target(s) in 1.14s
Running target/debug/deps/sev-ec0941895888abe8
running 4 tests
test session::key::mac ... ok
test session::key::derive ... ok
test session::initialized::verify ... ok
test session::initialized::session ... ok
test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Running target/debug/deps/api-4f359a7b11ad1be5
running 8 tests
test get_identifer ... ok
test pdh_generate ... ok
test pdh_cert_export ... ok
test pek_generate ... ok …
```
=> Implement PLATFORM_STATUS as an iocuddle ioctl

enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs, enarx-keep-sgx-shim/src/main.rs
This lets us dump the janky Print trait that I made. This is more Rust ergonomic.
Fixes: #469
=> Implement core::fmt::Write for Handler

enarx-keep-sev-shim/src/lib.rs
The IDE refactor rename didn't catch the release version of `ALIGN_SECTION`.
=> enarx-keep-sev-shim: fix const `ALIGN_SECTION` for release

containers/fedora/Dockerfile, enarx-keep-sgx/Cargo.toml, iocuddle-sgx/Cargo.toml, sev/Cargo.toml, sgx-crypto/Cargo.toml
Because openssl is compiled multiple times, this will speed up the CI.
=> containers/fedora: add ccache

Makefile.toml
`git` command and `.git` directory will not be required for building enarx.
Resolves #599
Signed-off-by: Ziyi Yan <ziyi.yan@foxmail.com>
After trying and reading `cargo-make` documentation, I found out that `CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY` is the one we need to replace the original `CARGO_WORKSPACE_ROOT`, which is the directory containing the `Makefile.toml`.
=> Use cargo-make global envs as root dir instead of git root directory

Cargo.toml, build.rs, src/main.rs
Display a quick error message whenever `cargo build`, `cargo test` or similar is invoked. Links back to the `cargo-make` repo and lists a few basic `cargo make` commands.
Resolves #598.
=> Inform users of `cargo make` when `cargo build/test` is used

Makefile.toml
i looked at the workspace emulation usage and saw few things that can be improved in the makefile.
* bool env vars can be just true/false, no need to make them strings
* new env var for test scripts dir location, so make tasks smaller and more readable.
* removed ```install_crate = "cargo-deny"``` as cargo make knows that automatically 
* replaced shell script 
```install_script = [''' which toml || cargo install toml-cli ''']```
with toml
```toml
install_crate = { crate_name = "toml-cli", binary = "toml", test_arg = "--help" }
```
which is multi platform
=> makefile changes

enarx-keep-sgx/src/main.rs
This is needed for running code generated by wasmtime JIT at run time.
=> enarx-keep-sgx: Mark heap as executable

enarx-keep-sgx-shim/Cargo.toml, enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs, enarx-keep-sgx/Cargo.toml, enarx-keep-sgx/src/main.rs, sallyport/src/lib.rs
This series of commits:
- Passes a sallyport Block into the enclave and shim's handler
- Creates a new syscall proxy function that reads arguments out of the handler's Block, but otherwise works the same way as the previous function
Related to #614
=> Prepare for using Sallyport in SGX

memory/src/address.rs
Let the Address have the correct type for alignment.
Instead of the type of the pointer,  let it have the type it's pointing to.
=> Memory address cast

enarx-keep-sgx-shim/src/heap.rs, keep-runtime/src/workload.rs
By default, wasmtime internally allocates 4GiB of memory once at the startup, which does not fit well in our SGX heap.  This configures wasmtime to only do dynamic memory allocation.
Related to #636.
=> keep-runtime: Prefer dynamic memory allocation in wasmtime

enarx-keep-sgx-shim/src/handler.rs
Related to #614 
I'm planning to pull the match statement in an upcoming PR after porting all the syscalls (because they all need to return the same value in `event()`, which right now is `u64` and later can be the `Result` type).
=> Update getuid syscall to use proxy

enarx-keep-sev-shim/src/hostcall.rs, enarx-keep-sgx-shim/src/handler.rs, enarx-keep-sgx-shim/src/heap.rs, memory/src/register.rs, sallyport/src/lib.rs
Note that we only convert `mut` pointers and references to `Register` to avoid discarding `const`, which would be unsafe. If we need a conversion for this in the future, we can add one.
=> Ease creation of Register and Request objects

enarx-keep-sev/Cargo.toml, enarx-keep-sev/src/main.rs, enarx-keep-sev/src/vm/builder.rs, enarx-keep-sev/src/vm/cpu.rs, enarx-keep-sev/src/vm/mod.rs, enarx-keep-sev/src/x86_64.rs
Related: #313 
Proxying the write syscall will be in the next PR once this lands.
This PR adds a type-state machine builder pattern to cleanly separate VM construction stages and to make sure all operations are performed in the correct order at compile time. It also performs the necessary setup to allow the shim to run :-)
```
$  ./enarx-keep-sev/target/debug/enarx-keep-sev \
--shim ./enarx-keep-sev-shim/target/x86_64-unknown-linux-musl/debug/enarx-keep-sev-shim \
--code ./payload/target/x86_64-unknown-linux-musl/debug/payload
IoOut: received 2 bytes from port 255
IoOut: received 2 bytes from port 255
IoOut: received 2 bytes from port 255
IoOut: received 2 bytes from port 255
IoOut: received 2 bytes from port 255
IoOut: received 2 bytes from port 255
IoOut: received 2 bytes from port 255 …
```
=> Run the shim

.gitignore, containers/fedora/Dockerfile
I spent some time today setting up development environment on my Mac, which using VS Code Remote to [connect to a linux container in Docker](https://code.visualstudio.com/docs/remote/containers). I used [this Dockerfile](https://github.com/enarx/enarx/blob/7dd05db8415039ca4678bc26ccce9f95b0610572/containers/fedora/Dockerfile) as the dev container and I added `rust-src` components for `rust-analyzer` setup. Here is the commit (https://github.com/ziyi-yan/enarx/commit/890eef53411319fa80c6a39930dd95e6086efcca).
But, I’m not sure whether we need to add this configuration files into our repo (Although I’m glad to write a tutorial for Mac dev environment setup :smile:). If that’s not the case, I want to merge this PR for ignoring these configs and add `rust-src` in dev container, which …
=> Ignore VSCode configs and add rust-src for local development

enarx-keep/Cargo.toml, enarx-keep/src/backend/kvm.rs, enarx-keep/src/backend/mod.rs, enarx-keep/src/main.rs
I intend to port the enarx-keep-sev "bare" VMM implementation onto this backend. The actual SEV-enabled VMM implementation will extend this backend with the SEV API, of course.
I've left this unlabeled since it's not _technically_ SEV but it is the groundwork for that.
=> Add KVM backend detection (kvm-show)

enarx-keep-sev-shim/src/hostcall.rs, sallyport/src/lib.rs
=> Use sallyport::Cursor for buf allocations

containers/bot/Dockerfile, containers/bot/github.conf
This new container deploys nginx to cache responses from GitHub. This means
that we use fewer API hits per hour.
=> Add a new container for our bot

enarx-keep-sgx-shim/src/handler.rs, sallyport/src/lib.rs
I hope for this PR to add the required functionality in the least intrusive way to the rest of the codebase. Whether that's achievable, I guess we'll see, but that's my goal anyhow. Also, since one way or another, we'll probably need to use an unsafe primitive to store the buffer of memory in, we'll need to be careful about the abstraction on top of it to be safe avoiding potential use-after-free, or aliasing, etc. Either way, any and all input @npmccallum and @lkatalin is most welcome here! Oh, and feel free to push to this branch as well if you feel the need!
TODO:
---
@npmccallum & @lkatalin I think this is ready for review. Here's the break up of the changes:
* `Cursor` now stores the mutable reference to the `Block`'s internal buffer inside an `UnsafeCell` to allow for interior …
=> Allow multiple Cursors::alloc's in the same block

.github/ISSUE_TEMPLATE/mentorship.md, .github/ISSUE_TEMPLATE/meta.md, .github/ISSUE_TEMPLATE/questions.md, .github/ISSUE_TEMPLATE/technical.md
- Use Markdown comments to cut down on boilerplate accidentally making it through
- Include a brief welcome message explaining that new issues will be triaged at the next standup, and include a link for more information
- Remove guidance on issue tagging/assignment (no longer needed with triage)
=> Make issue templates more consistent with sprints

enarx-keep-sev-shim/src/hostcall.rs, enarx-keep-sev-shim/src/main.rs
Recent changes to `sallyport::Cursor` mean that it no longer needs to be mutable.
I didn't dig into why, but having a `use x86_64::instructions::hlt;` at the top emits a warning, but removing it results in a compiler error because then the compiler doesn't know what `hlt()` is. Using the fully resolved name at the call site removes the warning.
=> Fix compiler warnings

enarx-keep-sgx-shim/src/handler.rs
Related to #614 .
Not sure if we still need `ret <= ERRNO_BASE` since `proxy()` now returns an `Ok()` or `Err`?
Edit: I thought about it more and the `ERRNO` check doesn't make sense, so I removed it.
=> Update read syscall to use proxy

enarx-keep-sev/Cargo.toml
Otherwise
```console
error[E0432]: unresolved import `kvm_bindings::KVM_MAX_CPUID_ENTRIES`
--> src/vm/mod.rs:10:5
|
10 | use kvm_bindings::KVM_MAX_CPUID_ENTRIES;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `KVM_MAX_CPUID_ENTRIES` in the root
error[E0308]: mismatched types
--> src/vm/builder.rs:125:39
|
125 |             fd.set_user_memory_region(region)?;
|                                       ^^^^^^ expected struct `kvm_bindings::x86::bindings_v4_20_0::kvm_userspace_memory_region`, found a different struct `kvm_bindings::x86::bindings_v4_20_0::kvm_userspace_memory_region`
|
= note: perhaps two different versions of crate `kvm_bindings` are being used?
error[E0308]: mismatched types
--> src/vm/cpu.rs:41:16
|
41 |     sregs.cs = cs;
|                ^^ expected struct …
```
=> sev: update kvm-bindings

enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs, integration-tests/src/bin/clock_gettime.rs, integration-tests/tests/syscall_clock_gettime.rs
Closes #664
I implemented syscall `clock_gettime` according to the [Usage section](https://github.com/enarx/enarx/tree/master/sallyport#usage) from sallyport. I used `self.block.cursor()` to allocate a buffer memory for host to write the result and then copy it back to the address in enclave.
=> Add syscall clock_gettime

integration-tests/tests/common/mod.rs
This commit tweaks the standard `assert_eq`s in `integration-tests`
so that instead of only dumping the raw bytes when asserting equality
between expected and given stdio outputs, it now also prints the
mismatch converted to a UTF8 string for easier debugging. The conversion
is lossy so that invalid UTF8 don't trigger false positives in our
testing harness.
=> Add better failure reporting in integration tests

enarx-keep-sgx-shim/src/handler.rs
When libc does its own internal initialization, it calls mmap(). It assumes
this mmap() will succeed and crashes if it fails. The reason that mmap() was
failing was because libc passed -1 as the file descriptor.  However, our
attempt to use a TryInto conversion would fail because it required truncation.
This caused mmap() to return EINVAL.
=> Fix a crasher in SGX

enarx-keep-sgx/src/builder.rs
Sometimes GCC will produce ELF binaries that have a segment with no pages.
These can be ignored. However, the previous version of this code was trying to
mprotect() on that memory region, which caused errors. Therefore, we should
explicitly skip them.
=> Ignore segments with no pages

.github/workflows/packet.yml
This adds a workflow that triggers on pull requests that runs `cargo make integration-ci` on each technology supported by our Packet.com servers: SEV and SGX1.
Resolves #736.
=> Run hardware tests on Enarx's Packet.com runners

enarx-keep-sev-shim/src/lib.rs, enarx-keep-sev/Cargo.toml, enarx-keep-sev/src/main.rs, enarx-keep-sev/src/vm/builder.rs, enarx-keep-sev/src/vm/mem.rs, enarx-keep-sev/src/vm/mod.rs, enarx-keep-sev/src/x86_64.rs
This way a CPU's sallyport block can be indexed into with its processor ID. This should allow me to remove the special-case construction of cpu0 in my other PR #722, so I will rebase that one on top of this one.
=> Expand setup area to accommodate CPU hotplug

.github/workflows/cargo.yml, .github/workflows/packet.yml, Makefile.toml, sev/Makefile.toml
Closes #768 
Closes #719 
This pull request unifies our CI tasks meaning that the entire suite can once again be ran anywhere with `cargo make ci` (new difference: this now includes running the integration tests).
It also adds another target that mainly wraps the `ci` target but turns on many of the hardware specific tests. `cargo make deep-ci` is used for this purpose. It is suitable for CI runners. This is explicitly a separate target in case there are those who want to run the tests on their specific hardware but don't want the tests to manipulate their platform state (i.e., SEV reset).
There's also bit a little bit of work to the `integration` target to build *only* the required crates needed to run the integration tests and now the task is no longer coupled with the `ci-flow`.
=> Tidy up makefile

enarx-keep-sev-shim/src/addr.rs, enarx-keep-sev-shim/src/frame_allocator.rs, enarx-keep-sev-shim/src/gdt.rs, enarx-keep-sev-shim/src/main.rs, enarx-keep-sev-shim/src/paging.rs, enarx-keep-sev-shim/src/shim_stack.rs
Allocate memory and map it to a given virtual address for the shim stack.
=> sev-shim: Implement `allocate_and_map_memory()` and allocate the shim stack

enarx-keep-sgx-shim/src/event.rs, enarx-keep-sgx-shim/src/handler.rs, enarx-keep-sgx/src/enclave.S, enarx-keep-sgx/src/enclave.rs, enarx-keep-sgx/src/main.rs
This change removes the `handle()` function passed to the VDSO, instead
handling the process flow in the Keep's `main()`. It also transitions to
using the `sallyport::Block` to proxy system calls.
Related to #614
=> Use sallyport for SGX syscall proxying

enarx-keep-sgx-shim/src/handler.rs, enarx-keep-sgx-shim/src/start.S
Related to #614 
This should pass CI when rebased onto #761 .
With #761 , we no longer rely on individual arguments passed in to `syscall()` to proxy a system call. Instead, we [write](https://github.com/lkatalin/enarx/blob/sally/enarx-keep-sgx-shim/src/handler.rs#L88) these arguments (ex. syscall number, `%rdi`, `%rsi` as detailed [here](http://blog.rchapman.org/posts/Linux_System_Call_Table_for_x86_64/)) into an untrusted memory [block](https://github.com/enarx/enarx/blob/master/sallyport/src/lib.rs#L152) and read them from that same block on the host side to properly invoke a system call. 
This means that the only arguments our `syscall()` function still needs are the ones that are not passed in the block. Those are `aex` (a [struct](https://github.com/enarx/enarx/blob/master/sgx/src/ty …
=> Remove unnecessary syscall() args

Makefile.toml
The keep functionality that was outlined in 'enarx-keep-sev' has since
moved into 'enarx-keep'
=> Remove old crate name

.tests/misc-lints-clippy-all, .tests/misc-lints-missing-docs
Use a '--' to separate paths from revisions, otherwise:
[cargo-make][1] INFO - Project: enarx-keep-sev-shim
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: misc-lints-missing-docs
[cargo-make][1] INFO - Profile: development
[cargo-make][1] INFO - Running Task: misc-lints-missing-docs
[cargo-make][1] INFO - Execute Command: "/home/harald/git/enarx/enarx/.tests/misc-lints-missing-docs"
The following files do not #![deny(missing_docs)]:
fatal: ambiguous argument 'src/lib.rs
src/main.rs': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
=> .tests/misc-lints-missing-*: fix ambigous arguments

enarx-keep-sev-shim/src/addr.rs, enarx-keep-sev-shim/src/hostcall.rs, enarx-keep-sev-shim/src/lib.rs, enarx-keep/src/backend/kvm/vm/builder.rs, enarx-keep/src/backend/kvm/vm/cpu.rs
This simplifies the code path in the loader.
=> Let the sev/kvm do the address translation for the loader

enarx-keep-sev-shim/src/start.S, enarx-keep-sgx-shim/src/start.S
This was introduced with the static-pie rcrt1 dynamic symbol correction,
copying the behaviour of the musl lib rcrt1.o. Apparently it is not
necessary to use the indirection, as the code base is not big enough
yet, that it exceeds the maximum relative jmp/call distance.
If that is ever the case, we should revert this patch.
=> shim sev/sgx: remove the indirection of the inital function rust call

enarx-keep-sev-shim/Cargo.toml, enarx-keep-sev-shim/src/addr.rs, enarx-keep-sev-shim/src/asm.rs, enarx-keep-sev-shim/src/asm.s, enarx-keep-sev-shim/src/main.rs, enarx-keep-sev-shim/src/payload.rs, enarx-keep-sev-shim/src/random.rs, enarx-keep-sev-shim/src/shim_stack.rs, enarx-keep-sev-shim/src/syscall.rs
Fixes: https://github.com/enarx/enarx/issues/72
Fixes: https://github.com/enarx/enarx/issues/77
Related: https://github.com/enarx/enarx/issues/309
With the wasmtime keep-runtime we get:
/home/harald/.cargo/bin/cargo run --color=always --package enarx-keep-sev-shim --bin enarx-keep-sev-shim
Finished dev [unoptimized + debuginfo] target(s) in 0.03s
Running `/home/harald/git/enarx/enarx/enarx-keep-sev-shim/../enarx-keep-sev-test/target/debug/enarx-keep-sev --code ../keep-runtime/target/x86_64-unknown-linux-musl/debug/keep-runtime --shim target/x86_64-unknown-linux-musl/debug/enarx-keep-sev-shim`
SC> mmap(0x0, 1808, …) = 0x0000555500000000
SC> arch_prctl(ARCH_SET_FS, 0x555500000620) = 0
SC> set_tid_address(…) = 337046
SC> rt_sigaction(…) = 0
SC> rt_sigaction(…) = 0
SC> rt_sigprocmask(…) = 0 …
=> Implement payload loading and syscall handling

intel-types/Cargo.toml, intel-types/src/lib.rs, sgx/Cargo.toml, sgx/src/lib.rs
Although the current version works, it is unsound. Leverage the work of
the memoffset crate, to someday provide a sound way of calculating the
offset.
This also prevents others from copying unsound code.
=> testaso: use memoffset::offset_of!()

containers/fedora/Dockerfile
Using nightly rustfmt will cause CI errors all the time, when rustfmt
changes.
Also all components should build with stable by default and only
selected components should switch to nightly.
Additionally the `--channel=nightly` argument for `rustup.sh` did not
work for me.
```console
error: error: Found argument '--channel' which wasn't expected, or isn't valid in this context
```
=> Make rustfmt and clippy non-nightly

containers/fedora/Dockerfile
`cargo ci-flow` runs clippy and clippy errors out on `#[feature()]`
```
error[E0554]: `#![feature]` may not be used on the stable release channel
```
=> containers/fedora: install nightly clippy

Makefile.toml
Signed-off-by: Adam Baxter <ambaxter@users.noreply.github.com>
=> Add dist-clean script to clean Cargo.lock files

crt0stack/Cargo.toml, crt0stack/examples/reader.rs, crt0stack/src/lib.rs, vdso/Cargo.toml, vdso/src/lib.rs
Basically, the only use of `from_environ()` is going to be using the `environ`
POSIX variable which is always available on `std`. Therefore, we don't force
the caller to provide this variable. This allows us to make the function safe.
=> crt0stack: internalize `environ` behind a `std` flag

.github/workflows/cargo.yml
We switched to using a root-level task, "ci", to orchestrate the CI
flows. ci-flow is one of the subordinate tasks, but is no longer the
proper primary CI task to invoke. Fix this just for consistency and to
avoid any ambiguity.
Users should run "cargo make ci"
=> Rename cargo-make-ci-flow -> cargo-make-ci

keep-runtime/fixtures/no_export.wat, keep-runtime/src/workload.rs
The [wasmtime::Linker](https://docs.rs/wasmtime/0.19.0/wasmtime/struct.Linker.html) interface transparently performs name resolution which we currently do by our own.
=> keep-runtime: Port to using wasmtime's Linker interface

enarx-keep-sev-shim/src/print.rs, enarx-keep-sev-shim/src/syscall.rs, integration-tests/build.rs, integration-tests/src/bin/clock_gettime.rs, integration-tests/tests/common/mod.rs, integration-tests/tests/syscall_clock_gettime.rs, integration-tests/tests/syscall_exit.rs, integration-tests/tests/syscall_read.rs, integration-tests/tests/syscall_write.rs
- turn off sev-shim debug output
- implement `SYS_clock_gettime` for sev-shim
- enable `integration-tests` for kvm
- fixed `clock_gettime` to check for seconds != 0
Fixes: https://github.com/enarx/enarx/issues/836
Fixes: https://github.com/enarx/enarx/issues/821
=> add kvm integration test

sgx/src/attestation_types/ti.rs
otherwise we always get:
```console
Compiling enarx-keep v0.1.0 (/home/harald/git/enarx/enarx/enarx-keep)
warning: unused import: `crate::attestation_types::report`
--> /home/harald/git/enarx/enarx/sgx/src/attestation_types/ti.rs:7:5
|
7 | use crate::attestation_types::report;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
```
=> mv `use crate::attestation_types::report` in feature gated function

enarx-keep/build.rs
This reduces size, and we cannot use gdb anyway (yet).
`-C debuginfo=0` could have been used also, but:
a) it does result in a bigger binary
b) I find myself disassembling the shims quite often and without
debuginfo, that is not parseable anymore
=> build.rs: run `strip` on the shims before including them in enarx-keep

enarx-keep/src/backend/kvm.rs, enarx-keep/src/backend/mod.rs, enarx-keep/src/backend/sev.rs, enarx-keep/src/backend/sgx/mod.rs, enarx-keep/src/main.rs
Some technologies, like SEV, SEV-ES and PEF, do attestation during the creation of the keep rather than afterwards. These technologies need a way to talk to a client during the keep build process. The general expectation is that if no socket is specified and the technology does preattestation, it should bring up the backend either without attestation or with simulated attestation.
=> Add a socket for preattestation

sgx/examples/generate_report.rs
If the "asm" feature is disabled, we get an error during `cargo test`.
=> Fix EREPORT example

sev/Cargo.toml, sgx/Cargo.toml, sgx/src/crypto.rs, sgx/src/enclave/builder.rs, sgx/src/enclave/ioctls.rs, sgx/src/types/sig.rs
Since we have combined sgx-types and sgx-crypto into a single crate, the
artificial extension trait is no longer needed. Instead, we just implement
`sign()` on `Measurement` directly.
Additionally, remove the dependency on the patched version of openssl. If
upstream decides to merge my patches, then we can rebase on top of those. Until
then, we'll use the current inefficient conversions that upstream has.
=> Move SGX signing code into the types module

enarx-keep/Cargo.toml
```console
❯ cargo tree -i -p openssl
openssl v0.10.30
└── sgx v0.1.0 (/home/harald/git/enarx/enarx/sgx)
└── enarx-keep v0.1.0 (/home/harald/git/enarx/enarx/enarx-keep)
```
=> enarx-keep: remove openssl crates.io patch

enarx-keep/shims/shim-sev/src/payload.rs, enarx-keep/shims/shim-sev/src/syscall.rs
Implement
- `uname()`
- fake `readlink("/proc/self/exe")`
- fake `fstat(0|1|2, …)`
- fake `fcntl(0|1|2, F_GETFL)`
- fix brk() for unaligned requests.
This lets us run a glibc compiled static-pie.
```C
int main() {
puts("Hello World!");
return 0;
}
```
as well as the `keep-runtime`.
=> shim-sev: implement syscalls for glibc and keep-runtime Hello World

enarx-keep/shims/shim-sev/src/addr.rs, enarx-keep/shims/shim-sev/src/frame_allocator.rs, enarx-keep/shims/shim-sev/src/hostcall.rs, enarx-keep/shims/shim-sev/src/hostlib.rs, enarx-keep/shims/shim-sev/src/main.rs, enarx-keep/src/backend/kvm.rs, enarx-keep/src/backend/kvm/vm.rs, enarx-keep/src/backend/kvm/vm/builder.rs, enarx-keep/src/backend/kvm/vm/cpu.rs, enarx-keep/src/backend/kvm/vm/mem.rs, enarx-keep/src/backend/mod.rs, enarx-keep/src/main.rs
Start with basically no free memory and request additional memory regions from the host on demand.
The amount of memory is doubled every time, trying to reach the maximum memory size with the available slots.
Fixes: https://github.com/enarx/enarx/issues/823
=> KVM ballooning

enarx-keep/src/backend/kvm/vm.rs
The bounds split merged before a PR that held a reference to bounds:: in
one of its diffs. I suspect the CI had no reason to re-run the PR since
a rebase wasn't necessary and therefore this snuck through once the PR
was approved.
=> Replace errant bounds:: with lset::

enarx-keep/shims/shim-sev/src/gdt.rs, enarx-keep/shims/shim-sev/src/payload.rs, enarx-keep/shims/shim-sev/src/shim_stack.rs, enarx-keep/shims/shim-sev/src/start.S
- factor out `init_stack_with_guard` to be used by the shim and payload
- dynamically allocate the exception stacks with page guards
=> Allocate the exception stacks with page guards

sev/src/firmware/linux/ioctl.rs, sev/src/lib.rs, sev/src/util.rs
Moving this into a util module will help with expressing other ioctl
structs that follow the pattern of having a command identifier encoded
into the structure that is sent into the kernel.
Furthermore, the new macro structure allows the consumer to name the
marker trait, its visibility, as well as the type of constant
expression; rather than imposing these choices upon client code. This
adds a better degree of usability to this mechanism.
No functional changes.
=> Evolve code! macro into impl_const_id!

enarx-keep/src/backend/sev.rs
This is needed to have some CI tests behave correctly.
=> Default to not using SEV backend for now

enarx-keep/src/backend/kvm/vm.rs, enarx-keep/src/backend/kvm/vm/builder.rs, enarx-keep/src/backend/kvm/vm/cpu.rs, enarx-keep/src/backend/kvm/vm/mem.rs, enarx-keep/src/binary/component.rs, enarx-keep/src/binary/segment.rs, mmap/Cargo.toml, mmap/src/lib.rs, sgx/src/enclave/builder.rs, sgx/src/enclave/enclave.rs
This is a new take on the mmap crate. It doesn't currently support all mmap
features. But it does support a lot of them. Most operations are safe.
Ownership of a map is implicitly tracked and `munmap()` is automatically
called. Additionally, we get compile-time validation of memory permissions.
=> A new mmap implementation

sev/src/firmware/linux/mod.rs
The KVM-SEV ioctls require cooperation with a file descriptor to
/dev/sev. Since Firmware encapsulates a file descriptor to /dev/sev and
since some of its functions will be used during the launch process, it
seems reasonable to share Firmware's fd rather than opening another fd
to /dev/sev.
=> impl AsRawFd for Firmware

sev/src/firmware/linux/ioctl.rs
Just for clarity's sake since indeed both structs and both headers are
relevant to this crate :-)
This file corresponds to ioctls that are called only on /dev/sev,
meaning the correct header and struct are sev_issue_cmd and psp-sev.h,
respectively.
A different module will be responsible for dealing with the SEV ioctls
that are called on /dev/kvm. Those ioctls will use struct kvm_sev_cmd
and include/uapi/linux/kvm.h.
=> Refer to correct struct and kernel header

enarx-keep/Cargo.toml, enarx-keep/build.rs, enarx-keep/tests/bin/clock_gettime.c, enarx-keep/tests/bin/exit_one.c, enarx-keep/tests/bin/exit_zero.c, enarx-keep/tests/bin/write_stderr.c, enarx-keep/tests/bin/write_stdout.c, enarx-keep/tests/integration_tests.rs
=> Move integration tests into enarx-keep

enarx-keep/build.rs
- throw meaningful `expect`
- get rid of duplicate paths
=> enarx_keep: refine `build_tests()`

.github/workflows/packet.yml
We have adapted the packet.com runners to match the behavior of the
`ubuntu-latest` cloud runner.
=> Unbreak the CI

enarx-keep/internal/rcrt1/src/lib.rs
Use `#![no_builtins]`, just in case, although it still doesn't work for
`opt-level = 0`. But better be safe than sorry. At least we tried :-)
https://doc.rust-lang.org/nightly/reference/attributes/codegen.html#the-no_builtins-attribute
=> enarx_keep/rcrt1: use `#![no_builtins]`

enarx-keep/internal/shim-sev/src/frame_allocator.rs
Using `impl` in arguments prevents using the turbofish at the caller.
=> shim-sev: don't use `impl` in arguments

enarx-keep/internal/shim-sev/Cargo.toml, enarx-keep/internal/shim-sev/src/main.rs, enarx-keep/internal/shim-sev/src/syscall.rs
memoffset does not update to a working crates.io package for nightly.
memoffset needs additional nightly features.
Also we only use 2 offsets, which don't change ever and can be easily
calculated.
=> shim-sev: remove memoffset crate dependency

enarx-keep/internal/shim-sev/src/main.rs
Per SysV ABI (rip % 16) must be 8.
=> shim-sev: Correct the stack pointer

README.md
This repo isn't used for building anything at the moment and
furthermore doesn't depend on cargo-make anyway.
Packet rebranded to Equinix Metal.
=> Freshen up stale readme

internal/shim-sev/src/payload.rs, internal/shim-sgx/src/entry.rs, internal/wasmldr/README.md, internal/wasmldr/src/main.rs, internal/wasmldr/src/workload.rs, tests/integration_tests.rs
We don't yet have a well-defined way to pass runtime configuration from the frontend/CLI into the keep. For v0.1.0 we've decided to just hardcode a default configuration, as follows:
* the .wasm module is open on fd3 and gets no arguments or env vars
* stdin, stdout, and stderr are enabled and should go to fd 0,1,2
* logging should be turned on at "debug" level
So these two patches turn on logging (by adding the RUST_LOG environment variable to the keep environment in both shims), and also document how/where we're applying our hardcoded default configuration.
All the code with a `KEEP-CONFIG HACK` comment above it is intended to be replaced/removed immediately after our first release. This is all temporary, but at least now it's explicit - and we know what we need to fix.
=> Turn on logging & document hardcoded keep config

internal/wasmldr/Cargo.toml
Very minor tweak - everything else is v0.1.0, so make wasmldr match
that. Also, while we're here, pull in wasmparser 0.81.
Signed-off-by: Will Woods <will@profian.com>
=> wasmldr: change version to 0.1.0, bump wasmparser dep

internal/shim-sev/src/payload.rs
Use the same size as the SGX backend for the code stack size.
=> fix(shim-sev): reduce the code stack size

.vscode/settings.json
`rust-analyzer` is pretty awesome, but its crate autodetection only
looks one level deep for Cargo.toml files. This is good enough to find
anything that's mentioned in the toplevel Cargo.toml (like the crates in
`integration/`), but the crates in `internal/` aren't listed because
(for the moment) we have to do special custom stuff to build them.
This commit adds a `.vscode/settings.json` that tells rust-analyzer to
examine the toplevel Cargo.toml and the internal crates (shim-sev,
shim-sgx, and wasmldr. And now rust-analyzer works for those crates.
Hooray!
Signed-off-by: Will Woods <will@profian.com>
=> Tell rust-analyzer vscode plugin about our crate layout

internal/shim-sev/src/lib.rs, internal/shim-sev/src/main.rs, internal/shim-sgx/src/main.rs
Apparently the `asm` feature split into more fine grained features.
=> fix: activate new asm features

internal/shim-sev/src/lib.rs, internal/shim-sev/src/main.rs, internal/shim-sgx/src/main.rs, internal/wasmldr/src/workload.rs
Disable `config.dynamic_memory_reserved_for_growth`.
Different values for `config.dynamic_memory_reserved_for_growth` produce
different results:
0..=260KiB: works
261..=268KiB: fails with ud2
269..=272KiB: fails with:
```
panicked at 'assertion failed: `(left == right)`
left: `true`,
right: `false`: cannot recursively acquire mutex', library/std/src/sys/wasi/../unsupported/mutex.rs:23:9
panicked after panic::always_abort(), aborting.
```
273..unknown: fails with ud2
1MiB: fails with ud2
2MiB: works
etc..
Requires/Includes: https://github.com/enarx/enarx/pull/1089
=> fix(wasmldr): make zerooneone work

.github/workflows/lint.yml, Cargo.lock, Cargo.toml, integration/sev_attestation/Cargo.toml, integration/simple/Cargo.toml, internal/shim-sev/Cargo.lock, internal/shim-sgx/Cargo.lock, tests/integration_tests.rs
instead of unmaintained `tempdir` crate.
Also:
- cargo update for more recent packages to counter `cargo deny` failures
- cargo deny for the whole workspace
=> fix: use `tempfile` crate

internal/shim-sgx/src/handler/mod.rs, internal/shim-sgx/src/lib.rs, internal/wasmldr/.cargo/config
**Pre-Requires**: https://github.com/enarx/enarx/pull/1102
This gives us a nice stack trace for the zerooneone issue, with
```
config.dynamic_memory_reserved_for_growth(bytes![1; MiB]);
```
We can pipe stderr through `./helper/parse-trace.sh` to get all the
file, function names and line numbers resolved.
```
$ cargo run -- run zerooneone.wasm \
|& ./helper/parse-trace.sh \
target/debug/build/enarx-*/out/internal/shim-sgx/x86_64-unknown-linux-musl/debug/shim-sgx \
target/debug/build/enarx-*/out/internal/wasmldr/x86_64-unknown-linux-musl/debug/wasmldr
[…]
TRACE:
Shim: 0x000000000fee6c3b: ENARX_HEAP_START at :?
[…]
Payl: 0x000000000026e6ec: wasmtime::func::Func::call_impl::{{closure}} at wasmtime-0.30.0/src/func.rs:746
Payl: 0x00000000002c0b1c: …
```
=> feat(shim-sgx): add stack trace

internal/shim-sev/Cargo.lock, internal/shim-sev/Cargo.toml, internal/shim-sev/src/interrupts.rs
Using an inner function enables the removal of the paste crate.
=> feat(shim-sev): get rid of paste! macro

internal/shim-sev/src/main.rs
vscode does not like it otherwise
=> fix(shim-sev): guard custom panic with "not(test)"

internal/shim-sev/src/allocator.rs, internal/shim-sev/src/gdb.rs, internal/shim-sev/src/interrupts.rs, internal/shim-sev/src/lib.rs, internal/shim-sev/src/main.rs, internal/shim-sev/src/print.rs, internal/shim-sev/src/spin.rs, internal/shim-sev/src/syscall.rs, internal/shim-sgx/src/handler/base.rs, internal/shim-sgx/src/handler/enarx.rs, internal/shim-sgx/src/handler/file.rs, internal/shim-sgx/src/handler/gdb.rs, internal/shim-sgx/src/handler/memory.rs, internal/shim-sgx/src/lib.rs, internal/shim-sgx/src/main.rs, internal/wasmldr/src/main.rs, src/backend/binary.rs, src/backend/kvm/config.rs, src/backend/kvm/thread.rs, src/backend/mod.rs, src/backend/sev/snp/firmware/linux.rs, src/backend/sev/snp/firmware/mod.rs, src/backend/sev/snp/launch/linux.rs, src/backend/sev/snp/launch/mod.rs, src/backend/sev/snp/mod.rs, src/backend/sgx/config.rs, src/backend/sgx/ioctls.rs, src/backend/sgx/thread.rs, src/main.rs
and add clippy warnings `#[warn(rust_2018_idioms)]`
=> fix: cargo fix --edition-idioms

Cargo.lock, Cargo.toml, internal/shim-sev/Cargo.lock, internal/shim-sev/Cargo.toml, internal/shim-sgx/Cargo.lock, internal/shim-sgx/Cargo.toml, internal/shim-sgx/layout.ld, internal/shim-sgx/src/handler/gdb.rs, internal/shim-sgx/src/handler/memory.rs, internal/shim-sgx/src/handler/mod.rs, internal/shim-sgx/src/heap.rs, internal/shim-sgx/src/lib.rs, internal/shim-sgx/src/main.rs, internal/wasmldr/Cargo.lock
The heap is now allocated from within Rust. It is also now a global protected by a lock. This means we can reference it directly from any code. This is useful preparation before landing allocators.
=> Rework the existing heap implementation

.github/workflows/lint.yml, .github/workflows/test.yml, Cargo.lock, Cargo.toml, build.rs, internal/shim-sev/src/lib.rs, internal/shim-sev/src/main.rs, internal/shim-sgx/src/main.rs, rust-toolchain.toml
Tie the enarx build process to a stable, officially released version.
To be installed with:
```
$ rustup component add rustfmt --toolchain 1.57-x86_64-unknown-linux-gnu
$ RUSTC_BOOTSTRAP=1 cargo +1.57 install --bin enarx -- enarx
```
Fixes: https://github.com/enarx/enarx/issues/1096
=> Release enarx 0.1.3 tied to rust 1.57

Cargo.lock, Cargo.toml, integration/sev_attestation/src/main.rs, internal/shim-sev/Cargo.lock, internal/shim-sev/Cargo.toml, internal/shim-sev/src/debug.rs, internal/shim-sev/src/exec.rs, internal/shim-sev/src/gdb.rs, internal/shim-sev/src/interrupts.rs, internal/shim-sev/src/lib.rs, internal/shim-sev/src/main.rs, internal/shim-sev/src/snp/ghcb.rs, internal/shim-sev/src/snp/mod.rs, internal/shim-sev/src/sse.rs, internal/shim-sev/src/syscall.rs, internal/shim-sev/src/usermode.rs, internal/shim-sgx/Cargo.lock, internal/shim-sgx/Cargo.toml, internal/shim-sgx/src/entry.rs, internal/shim-sgx/src/handler/base.rs, internal/shim-sgx/src/handler/gdb.rs, internal/shim-sgx/src/handler/mod.rs, internal/shim-sgx/src/lib.rs, internal/shim-sgx/src/main.rs, internal/wasmldr/Cargo.lock, internal/wasmldr/Cargo.toml, internal/wasmldr/src/workload.rs, src/backend/sgx/thread.rs, src/main.rs
- update wasmtime
- patch a fixed version of rustix needed by multiple wasmtime crates
- patch wasmldr for new wasmtime version
- use fixed crate versions for the stable asm feature
- patch all code for the stable asm feature
=> Fix the project to compile on nightly

Cargo.lock, Cargo.toml, internal/shim-sev/Cargo.lock, internal/shim-sev/Cargo.toml, internal/shim-sgx/Cargo.lock, internal/shim-sgx/Cargo.toml
commit 6ea4aefabb590ea37da32b4648ffee7d3d3e09ae specified a sallyport
version on a distinct branch without the `v2` subcrate, because
`version` was not used and I thought cargo was confused.
With `version` specified cargo does the right thing and selects the
sallyport version from the main directory.
=> fix: sallyport dependency

internal/wasmldr/src/workload.rs
Also works with https://github.com/MikeCamel/zerooneone/
Reason still unknown...
Maybe needs proper guard pages and memory permissions.
Fixes: https://github.com/enarx/enarx/issues/1229
=> fix(wasmldr): make rust Hello World work again

Cargo.lock, Cargo.toml, src/backend/binary.rs, src/backend/mod.rs, src/cli/info.rs
Running `enarx info --json` now yields the following:
```
[
{
"backend": "sgx",
"data": [
{
"name": "Driver",
"pass": true,
"info": "/dev/sgx_enclave",
"mesg": null
},
{
"name": "CPU Manufacturer",
"pass": true,
"info": "GenuineIntel",
"mesg": null
},
{
"name": " SGX Support",
"pass": true,
"info": null,
"mesg": null
},
{
"name": "  Version 1",
"pass": true,
"info": null,
"mesg": null
},
{
"name": "  Version 2",
"pass": true,
"info": null,
"mesg": null
},
{
"name": "  FLC Support",
"pass": true,
"info": null,
"mesg": null
},
{
"name": "  Max Size (32-bit)",
"pass": true,
"info": "2 GiB",
"mesg": null
},
{
"name": "  Max Size (64-bit)",
"pass": true,
"info": "64 PiB",
"mesg": null
},
{
"name": "  MiscSelect",
"pass": true,
"info": "EXINFO",
"mesg": null
},
{
"name": "  Features",
"pass": …
```
=> Add --json flag to `enarx info`

.github/workflows/test.yml, Cargo.lock, Cargo.toml, helper/test-enarx-wasm.sh, integration/simple/.cargo/config, integration/wasm/.cargo/config, integration/wasm/Cargo.toml, integration/wasm/rust-toolchain.toml, integration/wasm/src/echo.rs, integration/wasm/src/memory_stress_test.rs, integration/wasm/src/memspike.rs, integration/wasm/src/zerooneone.rs, rust-toolchain.toml, tests/common/mod.rs, tests/integration_tests.rs, tests/wasmldr_tests.rs
Similar to the `integration/simple` tests, use a cargo runner script, to
simply add integration tests.
=> ci: Add wasm integration tests

internal/shim-sgx/src/lib.rs
Support setting `RUSTFLAGS='-C target-cpu=x86-64-v4'` and passing all
tests.
SGX masks the XCR0 register with the `xfrm` mask, so any non set bit
feature is not allowed.
Fixes: https://github.com/enarx/enarx/issues/1190
=> feat(shim-sgx): enable AVX2 and AVX512 usage in the enclave

src/backend/kvm/mod.rs, src/backend/probe/common.rs, src/backend/probe/mod.rs, src/backend/sev/mod.rs, src/backend/sgx/mod.rs
- Uses the `uname` syscall to retrieve the system info.
- Adds a `errno` dependency for displaying errors nicely.
Closes #1206
=> Display system info using `uname` in `enarx info`.

README.md, src/backend/sgx/ioctls.rs, src/cli/exec.rs, src/main.rs
- Use code blocks for shell commands.
- Display a URL correctly.
- Use backticks to prevent `argv[0]` from looking like an intra-doc link.
Closes #1308
=> Fix `cargo doc` warnings.

internal/shim-sgx/src/lib.rs, internal/shim-sgx/src/uarch.rs
Define a SGX REPORT representation as a Rust data structure but use Intel
SDM naming conventions and explicitly do not enforce documentation. It
makes the whole thing more convoluted, e.g. when comparing your definition
to the Intel SDM. Use only primitive types (integers, arrays) for field
because it is the most portable way to define these structs. This is not
the place to be over the top with Rust idioms :-)
Collect all uarch structs to a single file called sgx_uarch.rs, which
will be located for the moment in the root source directory of shim_sgx,
but will be eventually probably moved to some more "generic" location.
Link: #1212
Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@iki.fi>
=> shim-sgx: Introduce REPORT microarchitectural data structure

.github/workflows/lint.yml
=> ci: also allow MIT SPDX license headers

Cargo.toml
Define paths more specific:
* /foo matches any file or directory with the name foo only in the root of the package.
* ! prefix negates a pattern.
See: https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields
=> fix: be more specific about Cargo `includes`

internal/shim-sev/src/interrupts.rs
With debug_assertions, otherwise `cargo build --release` will give a
warning.
=> fix(shim-sev): guard unused `use`

internal/shim-sev/src/sse.rs
Migrated MxCsr type from xsave crate to x86_64 crate. 
Closes #1291
=> shim-sev: migrated MxCsr type from crate xsave to x86_64

internal/wasmldr/Cargo.lock, internal/wasmldr/Cargo.toml, internal/wasmldr/src/cli.rs, internal/wasmldr/src/config.rs, internal/wasmldr/src/main.rs, internal/wasmldr/src/workload.rs, src/cli/mod.rs, src/main.rs, tests/common/mod.rs, tests/rust_integration_tests.rs, tests/wasm/rust-tests/Cargo.toml, tests/wasm/rust-tests/src/check_listen_fd.rs, tests/wasmldr_tests.rs
To make use of `socket_accept`, the git version has to be used.
These custom arguments `ARGS` are appended as `cargo run .... -- [ARGS]`
for the `run_crate` tests.
The `--wasmcfgfile <FILE>` for the `enarx run` command specifies a
configuration file, which is currently provided as file descriptor 4
for the executable in the keep (wasmldr).
This dynamic keep configuration, is later downloaded by the keep via
network directly to the keep executable after attestation along with the
wasm bytecode.
This patch adds handling of runtime configuration specified in toml
format. Currently the data is read from filedescriptor 4, but in the
future this configuration data is received along with the wasm byte code
after attestation.
In the current configuration file format, the pre-opened files and …
=> Sockets and preopened config file for wasmldr

.github/dependabot.yml
somehow wasmldr was never checked
=> chore: add wasmldr to dependabot

internal/wasmldr/src/workload.rs, tests/wasmldr_tests.rs
The `addr` field was not taken into account and `127.0.0.1` was used hard coded.
Additional commits:
* small nitpick fixes for @bstrie 
* ci(wasmldr): harden wasmldr_tests::check_listen_fd
=> fix(wasmldr): handle `addr` field for `tcp_listen` config

.github/workflows/lint.yml, .github/workflows/test.yml, flake.lock, flake.nix, rust-toolchain.toml
Closes https://github.com/enarx/enarx/issues/1347
Closes https://github.com/enarx/enarx/issues/1357
- Switch to https://github.com/nix-community/fenix Rust overlay, because
https://github.com/oxalica/rust-overlay was causing glibc-related compilation errors.
- Limit the nix development environment to Linux, because of lack of musl
support for other platforms.
=> Update Nix flake and pin nightly to fix CI

tests/c-tests/sgx_get_att_quote.c, tests/c-tests/sgx_get_att_quote_size.c
sgx_get_att_quote_size was not using `buffer length == 0` to request the
real needed buffer length and therefore `EINVAL` was returned.
sgx_get_att_quote was using the wrong nonce length != 64 and therefore
`EINVAL` was returned.
=> ci(sgx): fix sgx_get_att* tests

.gitignore
The file is already checked in since f7f5bb9
Although, it was (mistakenly?) added to `.gitignore` in 5f6a17b, which had no effect.
In any case, since we provide a compiled binary, rather than a library external parties can depend on, we *should* check-in our lock file.
=> Remove `Cargo.lock` from `.gitignore`

examples/tcp_server/README.md, examples/tcp_server/src/main.rs
The original `OpenBSD netcat` version does not issue
`shutdown(_, SHUT_WR)`, when the input pipe is closed.
Therefore the tcp_server input loop is never ended and nothing is echo'd
back.
To end with `netcat` the README.md is updated accordingly.
=> fix(examples/tcp_server): promptly echo back input

build.rs, src/backend/sgx/attestation.rs, tests/rust_integration_tests.rs
To indicate that the configuration flag is only for testing rename  `has_sgx` to `host_can_test_sgx`.
Also add `host_can_test_sev` for SEV.
Also use the configuration flags to mark tests with `#[ignore]` to show that the tests exist, but were ignored.
=> Rename `has_sgx` to `host_can_test_sgx` and add `host_can_test_sev`

internal/shim-sev/src/hostcall.rs, internal/shim-sev/src/lib.rs, internal/shim-sev/src/pagetables.rs, internal/shim-sev/src/snp/ghcb.rs, internal/shim-sev/src/snp/secrets_page.rs, internal/shim-sev/src/spin.rs
See https://github.com/rust-lang/rust/issues/53639#issuecomment-888435728
Related: https://github.com/enarx/enarx/issues/1405
=> fix(shim-sev): Turn all `static mut` globals into `RacyCell`

tests/c-tests/libc.h
See accept4(2) for details: https://linux.die.net/man/2/accept
Signed-off-by: Vincent Haupert <mail@vincent-haupert.de>
=> fix(tests): remove `const` modifier for `accept4`

internal/shim-sgx/src/uarch.rs
=> fix[sgx]: Document xchg usage in uarch.rs

helper/parse-trace.sh, helper/test-enarx-wasm.sh, helper/test-enarx.sh
On NixOS, neither `/bin/sh` nor `/usr/bin/bash` exists. This means, when
developing on NixOS with the given `flake.nix`, calling `cargo test`
partly fails as the given path in the helper scripts' shebang does not
exist.
For some compatibility, NixOS offers `/usr/bin/env`. Therefore, this
commit uses `/usr/bin/env` to call `sh` and `bash` relative to `PATH`.
Signed-off-by: Vincent Haupert <mail@vincent-haupert.de>
=> fix(test): use `/usr/bin/env` shebang

.github/workflows/test.yml, flake.lock, flake.nix, helper/test-enarx-wasm.sh, rust-toolchain.toml
- Fix Nix development environment
- Run `cargo build` via Nix on CI to test the development environment
- Update rust nightly
- Update Nix flake
Switched to using a custom Nix Rust tooling fork until https://github.com/nix-community/fenix/issues/67 is fixed (https://github.com/nix-community/fenix/pull/68 PR filed)
=> build(deps): nightly toolchain update, nix fixes, CI test

src/backend/kvm/thread.rs
When the shim causes an unhandled exception, the error message was very
cryptic. At least display where it was coming from.
=> feat(backend-kvm): be more verbose on KVM errors

.github/workflows/commisery.yml, .github/workflows/lint.yml, .github/workflows/test.yml
=> ci: cancel old workflows, if PR is updated

helper/test-enarx.sh
For manual testing of rust crates, search for an enarx binary in more
locations before doing a cargo build.
=> fix: helper/test-enarx.sh

.github/workflows/test.yml, flake.lock, flake.nix
This PR adds a package `enarx` to the project's flake. It allows building `enarx` with full 
Nix sandboxing and gives strong reproducibility guarantees. Also, it makes it easy to use the `enarx` binary on Nix-enabled systems.
The following command builds the package through Nix and brings the `enarx` binary into scope:
```ShellSession
...
Version 0.2.1 starting up
Backend: sgx
✔ System Info: Linux sgx-cont 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 (none)
✔ Driver: /dev/sgx_enclave
✔ CPU: Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz | GenuineIntel
✔  SGX Support
✔   Version 1
✗   Version 2
✔   FLC Support
✔   Max Size (32-bit): 2 GiB
✔   Max Size (64-bit): 64 GiB
✔   MiscSelect: (empty)
✔   Features: DEBUG | MODE64BIT | PROVISIONING_KEY | EINIT_KEY
✔   Xfrm: X87 | SSE …
```
=> build(nix): add `enarx` package

.github/workflows/lint.yml, .github/workflows/test.yml
Disable tests on SEV-SNP hardware until connectivity restored.
Ref #1508
=> chore(ci): temporarily disable SEV tests in CI

internal/shim-sev/src/snp/ghcb.rs, internal/shim-sev/src/snp/secrets_page.rs, internal/shim-sev/src/syscall.rs
`RwLocked::read()` for a mutable borrow is equal to `RwLocked::write()`,
so don't do that and use a Mutex with `Locked`.
=> fix(shim-kvm): change `RwLocked<&mut T>` to `Locked<&mut T>`

internal/shim-sev/src/syscall.rs
Some imports are only used in `feature = dbg`.
=> fix(shim-sev): guard unused imports with `cfg`

build.rs, src/backend/sgx/attestation.rs, tests/c_integration_tests.rs
```
feat: enable SGX attestation tests only if AESMD is running
Attestation tests require attestation infrastructure in place, which is
not always the situation in your developer platform. Having them enabled
by default weakens the contributor experience because it makes cargo
test usage tedious. Improve this by disabling attestation tests only if
AESMD is running. Completely ignore two ioctl tests, as they are
unstable, and the functionality will migrate to the sgx crate.
Closes: #1524
```
=> feat: enable SGX attestation tests only if AESMD is running

rust-toolchain.toml
We'll need this for upcoming sallyport changes.
=> chore: bump Rust toolchain version

Cargo.lock, Cargo.toml, internal/shim-kvm/Cargo.lock, internal/shim-kvm/Cargo.toml, internal/shim-sgx/Cargo.lock, internal/shim-sgx/Cargo.toml, internal/shim-sgx/src/handler/mod.rs, src/backend/sgx/attestation.rs, src/backend/sgx/thread.rs, tests/c-tests/get_att.c, tests/c-tests/sgx_get_att_quote.c, tests/c-tests/sgx_get_att_quote_size.c, tests/sev_attestation/Cargo.toml
The quote size is not a constant, so use the GetQuoteSizeEx protobuf
protocol to get the quote size.
Fixes: https://github.com/enarx/enarx/issues/1534
=> fix(sgx): instead of constant for quote size, use get_quote_size()

internal/shim-kvm/Cargo.lock, internal/shim-kvm/Cargo.toml, internal/shim-kvm/src/gdb.rs, internal/shim-kvm/src/hostcall.rs, internal/shim-kvm/src/lib.rs, internal/shim-kvm/src/print.rs, internal/shim-kvm/src/snp/ghcb.rs, internal/shim-kvm/src/syscall.rs, internal/shim-sgx/Cargo.lock, internal/shim-sgx/Cargo.toml, internal/shim-sgx/src/entry.rs, internal/shim-sgx/src/handler/gdb.rs, internal/shim-sgx/src/handler/mod.rs, internal/shim-sgx/src/handler/usermem.rs, internal/shim-sgx/src/heap.rs, internal/shim-sgx/src/lib.rs
As a step towards porting the shims to x84_64-unknown-none, remove the libc dependency in favor of the vendored libc definitions exported by sallyport.
=> refactor(shims): replace libc crate with vendored libc

internal/wasmldr/src/loader/configured/mod.rs, internal/wasmldr/src/loader/configured/platform.rs
This exposes the `get_attestation()` syscall to wasmldr. It will be used
by our future attestations.
cc @rjzak @definitelynobody
=> feat(wasmldr): add Platform API

src/cli/snp.rs, tests/c-tests/sgx_get_att_quote.c
In the github CI it seems the root directory is writable.
Change the test directory, which should not be able to be created to
`/proc/…`.
```
/runner/_work/enarx/enarx/tests/c-tests/sgx_get_att_quote.c: In function 'main':
/runner/_work/enarx/enarx/tests/c-tests/sgx_get_att_quote.c:33:14: warning: comparison of integer expressions of different signedness: 'ssize_t' {aka 'long int'} and 'long unsigned int' [-Wsign-compare]
33 |     if (size > sizeof(buf))
|
```
=> ci: make it pass again

Cargo.lock, Cargo.toml, internal/shim-kvm/Cargo.lock, internal/shim-kvm/Cargo.toml, internal/shim-kvm/src/hostcall.rs, internal/shim-kvm/src/snp/attestation.rs, internal/shim-kvm/src/snp/mod.rs, internal/shim-sgx/Cargo.lock, internal/shim-sgx/Cargo.toml, src/backend/kvm/mod.rs, src/backend/kvm/thread.rs, src/backend/sev/mod.rs, tests/sev_attestation/Cargo.toml, tests/sev_attestation/src/main.rs
Chain the SNP report with the vcek in ASN.1 format, in a format the steward can use right away.
For simplicity the length fields are all u32 encoded, regardless of the actual size.
See also `tests/sev_attestation/src/main.rs`.
Fixes: https://github.com/enarx/sallyport/issues/136
=> feat: SNP attestation with VCEK key

Cargo.lock, Cargo.toml, src/cli/exec.rs, src/cli/info.rs, src/cli/log.rs, src/cli/mod.rs, src/cli/run.rs, src/cli/sgx.rs, src/cli/snp.rs, src/main.rs
In addition to being a desired upgrade, this is necessary in order to work around a bug in the forthcoming support for artifact dependencies.
Closes #1346.
=> refactor(enarx): upgrade from StructOpt to Clap v3

.github/workflows/lint.yml, .github/workflows/sbom_manifest_action.yml, .github/workflows/test.yml, rust-toolchain.toml
This is required to address a bug in artifact dependencies.
=> build: update Rust toolchain to 2022-03-23

internal/shim-kvm/src/exec.rs, internal/shim-kvm/src/hostcall.rs
Previously unmapping of previously mapped brk pages was not handled.
This patch correctly unmaps anything mapped above the passed address.
=> fix(shim-kvm): correctly handle `brk()` unmap

.github/workflows/sbom_manifest_check.yml
Resolves bug/issue #1594 by removing `@main` (local GitHub actions cannot use version/branch tags)
=> fix(ci): correct workflow which generates SBOM

internal/shim-sgx/Cargo.lock, internal/shim-sgx/Cargo.toml, internal/shim-sgx/src/heap.rs
This will allow to replace it in `main()`. In addition, switch from
`jarkkojs/mmledger` to `enarx/mmledger`.
=> refactor(shim-sgx): put heap to a lazy container

Cargo.lock, src/bin/wasmldr/Cargo.toml
cargo deny:
```
error[A001]: Use after free with `externref`s and epoch interruption in Wasmtime
┌─ /github/workspace/Cargo.lock:221:1
│
221 │ wasmtime 0.35.1 registry+https://github.com/rust-lang/crates.io-index
│ --------------------------------------------------------------------- security vulnerability detected
```
=> build(deps): bump wasmtime to 0.35.2

src/bin/wasmldr/src/loader/compiled/tls.rs, src/bin/wasmldr/src/loader/requested.rs
How to test:
```
$ git clone https://github.com/haraldh/mini_http
$ cd mini_http
$ cargo +nightly build --target wasm32-wasi --example hello_enarx
$ <PATH_TO_THIS_PRS_ENARX_BIN> run \
--wasmcfgfile examples/Enarx.toml \
target/wasm32-wasi/debug/examples/hello_enarx.wasm
```
Then point your browser to [`https://127.0.0.1:3000`](https://127.0.0.1:3000)
=> fix: corrections for wasm tls

internal/shim-kvm/src/snp/attestation.rs, tests/sev_attestation/src/main.rs
Encode the length with a minimum number of octets as required by some
decoders.
> X.690 Section 10.1: DER lengths must be encoded with a minimum number of octets
=> fix(shim-snp): encode ASN.1 lengths with minimum number of octets

internal/shim-kvm/src/hostcall.rs, src/backend/sev/mod.rs
In the case, where the vcek could not be downloaded, fail early and also
safe guard inside the shim.
=> fix(shim-kvm): fail SNP attestation for vcek of length 0

internal/shim-kvm/src/snp/attestation.rs
The wrong sub-chunk length was used to calculate size of the combined
report + vcek chunk length.
This manifested in the rare case, where the vcek download failed and was
of size 0. This will be fixed in another PR.
=> fix(shim-kvm): correct ASN.1 encoding for SNP attestation

Cargo.toml, build.rs, internal/shim-kvm/Cargo.toml, internal/shim-sgx/Cargo.toml, internal/shim-sgx/src/handler/mod.rs, src/backend/sgx/data.rs
For sgx development, where the machine is offline or no proper aesmd/PCCS daemon setup is possible, the `disable-sgx-attestation` feature can be enabled.
The `get_attestation()` syscall will return (0, 0) in this case.
Closes: #1621
Closes: #1618
=> feat(sgx): add feature disable-sgx-attestation

Cargo.lock, internal/shim-sgx/Cargo.lock, internal/shim-sgx/Cargo.toml, internal/shim-sgx/layout.ld, internal/shim-sgx/src/handler/gdb.rs, internal/shim-sgx/src/handler/mod.rs, internal/shim-sgx/src/heap.rs, internal/shim-sgx/src/lib.rs, src/backend/sgx/builder.rs
=> feat(shim-sgx): mmap() with EACCEPTCOPY

Cargo.lock, Cargo.toml, src/backend/mod.rs, src/workldr/mod.rs
This pr replaces the uses of `spinning::Lazy` with `once_cell::sync::Lazy` in the main enarx binary. 
Closes #1517
=> refactor: switch to `once_cell`

.github/workflows/test.yml, Cargo.lock
Because there were some stale toolchain overrides from previous attempts, the cargo build failed with:
```
--- stderr
Unknown internal directory: shim-sgx
```
The culprit showed up as:
```
installed toolchains
--------------------
nightly-2022-03-23-x86_64-unknown-linux-gnu
nightly-2022-04-07-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
installed targets for active toolchain
--------------------------------------
wasm32-wasi
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl
active toolchain
----------------
nightly-2022-04-07-x86_64-unknown-linux-gnu (directory override for '/runner/_work/enarx/enarx')
rustc 1.62.0-nightly (8f36334ca 2022-04-06)
```
=> ci: remove stale toolchain overrides

build.rs
This works around the Cargo bug reported at https://github.com/rust-lang/cargo/issues/10527 .
=> fix: rebuild enarx bin when binary dependencies change

rust-toolchain.toml
@haraldh mentioned that he observed some test failures while previously attempting to bump the toolchain. Since we're going to need to bump the toolchain to get Tier 2 x86_64-unknown-none support, and since Tier 2 support unblocks bindeps for the shims, and since bindepping the shims is desirable for the next release, and since the next release is very soon, this PR is to get a head start on diagnosing any test failures.
This PR doesn't necessarily need to get merged, as it mostly exists just to exercise the CI on the new toolchain. However, if you wanted to merge it (assuming the tests pass) then that wouldn't hurt anything.
=> build: bump Rust toolchain to 2022-04-07

tests/c_integration_tests.rs
=> ci: disable sgx testing, if host can't test

Cargo.lock, Cargo.toml, internal/shim-kvm/Cargo.lock, internal/shim-kvm/Cargo.toml, internal/shim-sgx/Cargo.lock, internal/shim-sgx/Cargo.toml, tests/sev_attestation/Cargo.toml
via a sallyport update
Fixes: https://github.com/enarx/enarx/issues/1657
```
Running `target/release/enarx run /home/harald/Downloads/wasm_file.wasm`
Hello, World!
```
=> feat: add clock_getres syscall

Cargo.lock, src/bin/shim-kvm/src/hostcall.rs, src/bin/shim-sgx/src/handler/mod.rs, src/bin/wasmldr/Cargo.toml, src/bin/wasmldr/src/main.rs, tests/rust_exec_tests/Cargo.toml, tests/rust_exec_tests/src/cpuid.rs, tests/rust_exec_tests/src/echo.rs, tests/rust_exec_tests/src/lib.rs, tests/rust_exec_tests/src/memory_stress_test.rs, tests/rust_exec_tests/src/memspike.rs, tests/rust_exec_tests/src/unix_echo.rs, tests/sev_attestation/src/main.rs
Setting fsbase now even works in SGX.
=> feat: no more `arch_prctl` syscall

Cargo.lock, Cargo.toml
We removed these paths for the 0.4 release as an extremely conservative measure, due to being wary of potential bugs in Cargo's unstable bindeps support. Since no bugs were revealed during the publish, this adds those paths back. We don't need to worry about doing this again in future releases.
=> chore: put paths back for bindeps

BUILD.md, Cargo.lock, Cargo.toml, flake.nix, src/backend/sgx/builder.rs, src/backend/sgx/hasher.rs
This makes enarx easier to build. It also means we can hopefully provide
a binary that doesn't depend on system libraries besides libc. This is a
step towards an official release binary.
=> refactor: switch from openssl to rcrypto

.github/workflows/coverage.yml, crates/exec-wasmtime/src/loader/configured/platform.rs
In the podman container the enarx syscall returns EPERM.
=> fix(exec-wasmtime): handle EPERM for get_att() syscall

Cargo.toml, crates/exec-wasmtime/Cargo.toml, crates/shim-kvm/Cargo.toml
Fixup of commit 5639b589079563299211d23b919554e69a5becf6, which removed
all default features.
Fixes: #1780
=> fix: propagate features to bindeps

.github/workflows/cargo-update.yml, .github/workflows/rust-toolchain-update.yml, .github/workflows/test-docs.yml, Cargo.toml, docs/Install.md
- Fix `workflow_dispatch` to enable on-demand workflow execution
- Address bug caused by `examples/tcp_server` not excluded from workspace
- Enable tests for executing `enarx` using `nil` backend on workflows
=> ci(actions): assorted GH workflow related fixes

crates/sallyport/tests/integration_tests/syscall.rs, tests/rust_exec_tests/src/lib.rs
For [`nightly-2022-05-03`](https://github.com/enarx/enarx/actions/runs/2262784577):
```
19 | use std::ffi::{c_char, c_int, CString};
|                ^^^^^^  ^^^^^ no `c_int` in `ffi`
|                |
|                no `c_char` in `ffi`
```
=> fix: use `core::ffi` for `std::ffi::c_*`

crates/exec-wasmtime/Cargo.toml, crates/exec-wasmtime/src/loader/configured/mod.rs, crates/exec-wasmtime/src/loader/pki.rs, crates/exec-wasmtime/src/loader/requested.rs
and remove the package renaming in `Cargo.toml`.
While mocking crate registries, this cause problems.
Let's just name the crate by its real name.
=> fix(exec-wasmtime): rename `x509::` to `x509_cert::`

Cargo.lock, tests/rust_syscall_tests/Cargo.toml, tests/sev_attestation/Cargo.toml
The tests are not published to crates.io and don't need a version.
By removing the version, we also remove the burden to update the
version.
=> build(deps): remove sallyport version from internal tests

Cargo.lock, crates/shim-kvm/Cargo.toml, crates/shim-sgx/Cargo.toml, tests/rust_syscall_tests/Cargo.toml, tests/rust_syscall_tests/src/io.rs, tests/rust_syscall_tests/src/lib.rs, tests/rust_syscall_tests/src/macros.rs
and convert `main` return value with the `Termination` trait to an
`exit()` value.
Also add some convenience io macros like `dbg!()`, `println!()` and
`eprintln()!`.
Also `eprintln!()` the `panic()` `PanicInfo`.
=> feat(rust_syscall_tests): use the `rcrt1::x86_64_linux_startup!` macro

crates/exec-wasmtime/src/config.rs, crates/exec-wasmtime/src/loader/compiled/tls.rs
- Use `sum()` method for clarity and consistency (see L284)
- Rename `Name` to `FileName` to differentiate from other "names"
=> refactor(exec): a few minor improvements

Cargo.lock, Cargo.toml, crates/shim-sgx/Cargo.toml
=> chore(deps): update code to use sgx 0.5 and mmledger 0.3 crates

src/backend/kvm/mod.rs, src/backend/sgx/mod.rs, src/exec/exec_wasmtime/mod.rs
Add new unit tests to the Enarx crate to guard against regressions in binary size for the shims.
Tests are only run in release mode, and will fail if a shim exceeds 500 KB in size.
This also removes a useless test from exec-wasmtime.
Closes #1609.
=> test: enforce maximum shim size in release tests

.github/workflows/test-docs.yml, docs/Install.md
Please merge on the day of release.
With the 0.5 containing the nil backend, we no longer need to filter runtime tests depending on git or crate origin.
=> docs(release): update docs prior to 0.5 Release

.github/workflows/test.yml, flake.lock, flake.nix
Closes #1865 
Closes #1851 
Removed the https://github.com/nix-community/fenix fork, since https://github.com/nix-community/fenix/pull/68 was merged.
This PR is based upon brilliant work by @veehaitch in https://github.com/enarx/enarx/pull/1564 (thanks!)
We now have reproducible, static builds of Enarx via Nix, including an OCI image containing the binary.
We also now test the validity of Nix flake itself, the dev environment, the build of the binary and the build of the Docker image in CI.
For testing the Docker image:
```sh
$ nix build '.#enarx-docker'
$ docker load < result                               
ERRO[0000] Error refreshing container 505a8667e52c84d998c6af764705754000f2aa06357a8834194f34c8884fc19d: error retrieving temporary directory for container …
```
=> build(nix): provide static, reproducible builds

.github/workflows/test.yml, flake.nix
- Enable `nix run .`, i.e. users can now do `nix run github:enarx/enarx info` to build and test `enarx` compiled for the host target directly from `main` and run on success `enarx info` (or any other subcommand) with no other dependency than `nix` on any x86_64 Linux distribution supported by `nix`
- Refactor `enarx-docker` to provide an `enarx` binary in `PATH`
- Split the nix CI job to benefit from concurrent builds and get clearer output
- Filter the source to improve caching efficiency
- Test, whether the binary is indeed static as part of the build
- Execute the static binary on Ubuntu
For testing Docker image (will be added to CI):
```
docker run --rm $(docker load < ./result | sed 's/Loaded image(s): \(.*\)/\1/') enarx info
```
=> build(nix): various improvements

.github/workflows/test.yml
Closes #1875 
This will enable https://app.cachix.org/cache/enarx binary cache.
Already built artifacts will be pulled from the content-addressable cache by their hash, rather than being built.
On successful CI jobs from within this repo, artifacts will be pushed.
So we'll only see benefits of this once we merge the PR.
=> ci(nix): enable caching

crates/shim-kvm/src/exec.rs, crates/shim-kvm/src/gdt.rs, crates/shim-kvm/src/hostcall.rs, crates/shim-kvm/src/main.rs, crates/shim-kvm/src/random.rs, src/backend/kvm/data.rs
This reverts commit e20965b4ca78f6766cefa8a48869fc30e19485e1.
This reverts commit 0cd613c2ba1c302ad07098f02e474928f52d74e1.
We now have the `nil` backend for those users.
=> fix(shim-kvm): revert support old CPUs

src/main.rs
Add the `--version` argument:
```console
$ enarx --version
enarx 0.5.0
```
Extend the prologue of the `--help` output.
Before:
```console
$ enarx --help
enarx
`enarx` subcommands and their options/arguments
USAGE:
enarx [OPTIONS] <SUBCOMMAND>
[...]
```
After:
```console
$ enarx --help
enarx 0.5.0
Tool to deploy WebAssembly into Enarx Keeps
Enarx is a tool for running Webassembly inside an Enarx Keep - that is a hardware isolated
environment using technologies such as Intel SGX or AMD SEV.
For more information about the project and the technology used visit the Enarx Project home page
https://enarx.dev/.
USAGE:
enarx [OPTIONS] <SUBCOMMAND>
[...]
```
=> feat: add `--version` and extend `--help`

src/backend/kvm/mod.rs, src/backend/sgx/attestation.rs, src/backend/sgx/mod.rs, tests/exec/mod.rs, tests/syscall/mod.rs
Tell the tester why the test was ignored, so he can act, if the ignore
was not by purpose.
```
$ cargo test
Compiling enarx v0.5.0 (/home/harald/git/enarx/enarx)
Finished test [unoptimized + debuginfo] target(s) in 8.72s
Running unittests src/main.rs (target/debug/deps/enarx-0d48f622fe6aa2d1)
running 10 tests
test backend::kvm::tests::shim_kvm_binary_size ... ignored, debug_assertions active
test backend::sgx::attestation::tests::request_target_info ... ignored, CPU does not support SGX2 or attestation not possible
test backend::sgx::tests::shim_sgx_binary_size ... ignored, debug_assertions active
test backend::nil::test::coverage ... ok
test backend::sev::snp::firmware::test::test_vcek_url ... ok
```
=> feat: add ignore message

.codecov.yml
for the shims, which can't report full coverage
=> ci: lower expectations for code coverage

.github/workflows/coverage.yml
and distribute a little more on the runners
=> ci: use codecov-action v3

.github/workflows/test.yml, Cargo.lock, crates/exec-wasmtime/Cargo.toml, crates/exec-wasmtime/src/lib.rs, crates/exec-wasmtime/src/loader/compiled/tls.rs, crates/exec-wasmtime/src/loader/requested.rs, crates/exec-wasmtime/src/main.rs, crates/sallyport/src/lib.rs, crates/sallyport/tests/integration.rs, crates/shim-kvm/src/lib.rs, crates/shim-sgx/src/lib.rs, examples/tcp_server/Cargo.toml, examples/tcp_server/src/main.rs, src/backend/mod.rs, src/backend/nil.rs, src/cli/info.rs, src/main.rs, tests/integration.rs, tests/wasm/mod.rs
Also support `test --workspace` on MacOS and Windows.
=> feat: add Windows support with the `nil` backend

crates/shim-kvm/src/debug.rs, crates/shim-kvm/src/gdt.rs, crates/shim-kvm/src/interrupts.rs, crates/shim-kvm/src/lib.rs, crates/shim-kvm/src/main.rs, crates/shim-kvm/src/snp/ghcb.rs, crates/shim-kvm/src/snp/mod.rs, crates/shim-kvm/src/sse.rs, crates/shim-kvm/src/syscall.rs, crates/shim-kvm/src/usermode.rs
Since `#[no_coverage]` is unstable, it is recommended to use it together with `cfg(coverage)` or `cfg(coverage_nightly)` set by `cargo-llvm-cov`.
See https://github.com/taiki-e/cargo-llvm-cov/#exclude-function-from-coverage
=> chore(shim-kvm): mark coverage regions to exclude

.github/workflows/coverage.yml
This uses the new flag added in https://github.com/taiki-e/cargo-llvm-cov/pull/167
=> ci: update code coverage tool

.github/workflows/coverage.yml, .github/workflows/test.yml
After adding some ARM builders we have to specify x64 for jobs that require it, otherwise tests fail randomly.
=> ci: specify x64 runners for CI jobs

Cargo.toml, crates/sallyport/Cargo.toml, crates/shim-kvm/Cargo.toml, crates/shim-sgx/Cargo.toml
By default, making a crate into an optional dependency also makes it into a crate feature. Using a recent Cargo feature, we can disable this behavior and reduce the number of crate features to only those that are explicitly declared.
=> refactor: reduce crate feature surface area

README-DEBUG.md, crates/shim-sgx/src/handler/gdb.rs
=> docs(sgx): reburnish the SGX GDB documentation

.github/workflows/release.yml
=> ci: reenable mac and enable aarch64 builds

docs/Quickstart.mdx
Adding Quickstart installation guide with instructions for Windows, macOS, and Linux using the appropriates binaries.
Closes #1895 
Signed-off-by: Nick Vidal <nick@profian.com>
=> docs: add Quickstart installation guide

crates/shim-sgx/src/handler/mod.rs, src/backend/sgx/attestation.rs
With a freshly started PCCS daemon, the aesmd returns `AttKeyNotInitialized` and according to
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/fe200aa160bc159f92149f02e703f0b02e4348d2/QuoteGeneration/quote_wrapper/ql/sgx_dcap_ql_wrapper.cpp#L423-L424
> ATT_KEY_NOT_INITIALIZED The platform quoting infrastructure does not have the attestation key available to generate quotes. `sgx_qe_get_target_info()` must be called again.
So, calling `get_sgx_target_info()` before `get_sgx_quote_size()` prevents the problem.
Also translate the numeric errors from aesmd to names according to `psw/ae/inc/internal/aesm_error.h`
PCCS log in error case:
```
Jun 22 12:14:06 localhost pccs[538425]: 2022-06-22 12:14:06.100 [info]: Client Request-ID …
```
=> fix(sgx): prevent aesmd error 42 - ATT_KEY_NOT_INITIALIZED

.github/workflows/release.yml
The following job step is currently a no-op since none of the configured artifacts are actually present at the paths. By default `download-artifact` action downloads "all artifacts" into a directory.
Specify each artifact name explicitly to fail fast on missing artifacts and to make following step actually add assets to the draft release
Just like https://github.com/profianinc/drawbridge/blob/9f889cbadd0d066aee566f2ff44221aaa31c8c45/.github/workflows/release.yml#L85-L98
=> ci(release): add built assets to release draft

docs/Install.md
=> docs: fix docs to use new `enarx cpu info` command

.cargo/config
The registry is the list of crate versions from crates.io, which Cargo uses to resolve dependency versions. As originally implemented, this registry is stored as a Git repo, which is cloned on first use and pulled for updates. However, as crates.io has grown the size of the registry has become a bottleneck, and Cargo is preparing to address this by supporting "sparse registries", which involves only pulling dependency information for crates that are actually being used for the compilation. This promises to be somewhat faster for regular development and much faster for CI builds.
=> build: use new Cargo sparse registry support

examples/tcp_server/Cargo.toml, examples/tcp_server/src/main.rs
It's `target_os="wasi"` and not `target_os="wasm32-wasi"`.
=> fix(tcp_server): correct target_os

Cargo.toml
=> chore: exclude docs and tests dirs from published crate

helper/release_enarx.sh
- Add `enarx-config` crate to list of published packages as part of release
- Ensure `enarx platform info` is run instead of `enarx info` during sanity tests
=> build: ensure enarx-config crate is built and published

examples/tcp_server/Enarx.toml, examples/tcp_server/README.md, examples/tcp_server/src/main.rs
The README.md uses plain TCP to test the echo server.
What it does and how to connect to the server.
Don't panic out on unexpected errors, but print error messages.
Flush stdout here and there, so the user sees the messages.
=> fix(tcp_server): harden the server and fix proto tls vs tcp

.mailmap
To map email addresses of git authors.
Minimize the output of:
```
$ git shortlog  --numbered --summary -e |while read _ rest || [ -n "$rest" ]; do echo $rest;done | sort
```
=> chore: add .mailmap

Cargo.lock, crates/shim-kvm/Cargo.toml, crates/shim-kvm/src/allocator.rs, crates/shim-kvm/src/exec.rs, crates/shim-kvm/src/hostcall.rs, crates/shim-kvm/src/pagetables.rs, crates/shim-kvm/src/shim_stack.rs
This requires switching from `RwLock` to `Mutex`, because the inner Allocator is not `Sync`.
Supercedes: https://github.com/enarx/enarx/pull/1992
=> fix(deps): update linked_list_allocator requirement from 0.9.1 to 0.10.1

src/backend/sev/mod.rs
Turn the `unwrap()` for `register_enc_memory_region()` into a proper
`io::Error` and return it, rather than panic.
=> fix(sev): return proper io::Error for `register_enc_memory_region()`

src/backend/sev/snp/vcek.rs, src/cli/platform/snp/info.rs, src/cli/platform/snp/update.rs
If there is no vcek certificate cached in `/var/cache/amd-sev`, fail.
There must be a system service setting up the cache file.
`enarx platform snp update` does exactly that.
This removes all confusion about which file is used and when it should be created.
Fixes: https://github.com/enarx/enarx/issues/2045
=> feat(sev): remove vcek cache directory in `$HOME`

crates/shim-kvm/src/allocator.rs, crates/shim-kvm/src/hostcall.rs, crates/shim-kvm/src/main.rs
Disallow writing to write protected pages.
Clear the pages on raw allocation from the linked list allocator before
referencing them from the user space page table.
=> feat(shim-kvm): enable CR0 WRITE_PROTECT

Cargo.lock, src/backend/sgx/attestation.rs, src/backend/sgx/thread.rs, tests/crates/enarx_exec_tests/Cargo.toml, tests/crates/enarx_exec_tests/src/bin/sgx_attestation.rs, tests/exec/mod.rs
Closes https://github.com/enarx/enarx/issues/2050
Instead of:
```
thread 'backend::sgx::attestation::tests::request_target_info' panicked at '
error obtaining attestation key id:
Custom { kind: Other, error: "Unexpected number of key IDs: 3 != 1" }',
src/backend/sgx/attestation.rs:445:45
```
This PR now filters for the exact attestation key algorithm id `SGX_QL_ALG_ECDSA_P256`.
Additionally the error messages were extended to give a hint to the `aesmd` and `pccs` services.
Additionally the `rust_sgx_attestation` test was added, checking that the quote report contains a certificate chain.
=> fix(sgx): filter attestation keys

Cargo.lock, Cargo.toml, src/backend/sev/snp/firmware/linux.rs, src/backend/sev/snp/firmware/mod.rs
=> test(snp): add some testaso tests for the SEV-SNP backend

.github/workflows/coverage.yml, .github/workflows/test.yml
```
Run actions-rs/toolchain@v1
/runner/_work/_temp/5a8c1328-61cf-4c6e-8a44-0a2477ad5648 --default-toolchain none -y
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: skipping toolchain installation
Rust is installed now. Great!
To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).
To configure your current shell, run:
source "$HOME/.cargo/env"
/root/.cargo/bin/rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /root/.rustup
installed toolchains
--------------------
error: no default toolchain configured
Error: The process '/root/.cargo/bin/rustup' failed with exit code 1
```
Signed-off-by: Harald …
=> ci: fix toolchain

crates/enarx-config/Enarx_toml.md, crates/enarx-config/src/lib.rs, src/cli/config/init.rs, src/cli/config/mod.rs, src/cli/mod.rs, tests/client/mod.rs
Related: https://github.com/enarx/enarx/issues/1958
```
$ enarx config --help
enarx-config
Commands for working with users on an Enarx package host
USAGE:
enarx config <SUBCOMMAND>
OPTIONS:
-h, --help    Print help information
SUBCOMMANDS:
help    Print this message or the help of the given subcommand(s)
init    Generate an `Enarx.toml` template
$ enarx config init
$ cat Enarx.toml
[[files]]
kind = "stdin"
[[files]]
kind = "stdout"
[[files]]
kind = "stderr"
$ enarx config init
Error: "Enarx.toml" does already exist.
```
=> feat: add `enarx config init`

docs/Credentials.md, src/cli/package/info.rs, src/cli/package/publish.rs, src/cli/repo/info.rs, src/cli/repo/register.rs, src/cli/user/info.rs, src/cli/user/login.rs, src/cli/user/register.rs, src/drawbridge.rs
Closes #2019 
This should really be configured via CLI config #2021 
E.g. for https://github.com/gopasspw/gopass this can be used the following way:
`enarx-credential-helper-gopass`
```
#!/bin/sh
set -e
if [ "${1}" = "insert" ]; then
exec gopass insert -f misc/enarx
elif [ "${1}" = "show" ]; then
gopass find misc/enarx 2>/dev/null
exec gopass show -n -o misc/enarx
else
echo "Unknown command '${1}'"
exit 1
fi
```
`enarx user register myuser --credential-helper ./enarx-credential-helper-gopass`
Once we add the plugin system for `enarx`, this will can also be looked up from `PATH`, i.e. users could contribute and install custom `enarx-credential-helper-*` and these would be picked up from the path.
This is a standard approach used by a variety of other tools, e.g.:
- …
=> feat: support custom credential helpers

crates/sallyport/src/guest/alloc/phase_alloc.rs, crates/sallyport/src/lib.rs
This potential source of UB was discovered while upgrading the Rust toolchain, which upgrades us to a new version of Miri with stricter rules around raw pointers. Specifically, an expression like `addr_of_mut!((*(ptr))[offset..])` is deliberately attempting to operate only on raw pointers while avoiding any intermediate references, since references have invariants that raw pointers do not (e.g. aliasing). However, there is in fact an implicit reference here that is created as a result of the indexing operation. This is both surprising and not surprising, for interesting reasons.
First, it should not be surprising because indexing is governed by the Index traits, whose methods return references, so their presence here is natural.
On the other hand, it is surprising because Rust already …
=> fix(sallyport): avoid UB by removing implicit reference from indexing with range

Cargo.lock, Cargo.toml
Update to a version of drawbridge that contains https://github.com/profianinc/drawbridge/pull/241 , in order to fix building Enarx on certain platforms. In order to use this fix during the last release we were forced to temporarily depend on a fork of drawbridge; such workarounds should not be necessary in the future as long as the drawbridge crate permissions on crates.io are broadened appropriately.
=> chore: bump drawbridge to 0.2

.github/workflows/coverage.yml, .github/workflows/sbom_manifest_action.yml, .github/workflows/test.yml, crates/exec-wasmtime/src/lib.rs, crates/exec-wasmtime/src/main.rs, crates/sallyport/src/guest/alloc/phase_alloc.rs, crates/sallyport/src/guest/alloc/tests.rs, crates/sallyport/src/guest/call/syscall/alloc.rs, crates/sallyport/src/guest/call/syscall/passthrough.rs, crates/sallyport/src/guest/call/syscall/tests.rs, crates/sallyport/src/lib.rs, crates/sallyport/tests/integration.rs, crates/shim-kvm/src/lib.rs, crates/shim-sgx/src/lib.rs, docs/Install.md, flake.lock, rust-toolchain.toml, src/backend/sev/snp/vcek.rs, src/backend/sgx/builder.rs, src/backend/sgx/hasher.rs, tests/crates/enarx_exec_tests/src/bin/cpuid.rs, tests/crates/enarx_exec_tests/src/bin/echo.rs, tests/crates/enarx_exec_tests/src/bin/memory_stress_test.rs, tests/crates/enarx_exec_tests/src/bin/memspike.rs, tests/crates/enarx_exec_tests/src/bin/sev_attestation.rs, tests/crates/enarx_exec_tests/src/bin/sgx_attestation.rs, tests/crates/enarx_exec_tests/src/bin/unix_echo.rs
This gets a bugfix for Cargo's sparse registry feature, updates some code for some new clippy lints, removes a newly-unnecessary feature flag, and temporarily disables some tests under miri (see #2066).
Supersedes #2057.
=> chore: bump Rust toolchain to 2022-07-19

.github/workflows/release.yml
- Fix windows artifact locations prior to release
- Remove platform specific darwin binaries in favor of universal binaries
- Remove unnecessary whitespace
=> fix(release): rename windows artifact locations

Cargo.lock, crates/exec-wasmtime/Cargo.toml
=> chore(wasmtime): bump wasmtime related dependencies

crates/exec-wasmtime/src/loader/compiled/mod.rs
Closes #2090 
Typical POSIX executables expect the executable name to be passed in as
the first argument. Without this, executables using command-line arguments are not portable.
=> feat: set `main.wasm` in `argv[0]`

Cargo.lock, crates/exec-wasmtime/Cargo.toml, crates/exec-wasmtime/src/loader/configured/mod.rs, crates/exec-wasmtime/src/loader/pki.rs, crates/exec-wasmtime/src/loader/requested.rs
=> chore(exec-wasmtime): bump x509-cert to v0.1.0

Cargo.lock, crates/exec-wasmtime/Cargo.toml
This also gets rid of the `=` pinned dependencies for the wasmtime deps since it doesn't appear to succeed at silencing dependabot as we had hoped.
=> chore(exec-wasmtime): bump wasmtime deps to v0.39.1

docs/Install.md
Parentheses were not quoted resulting in:
```
KERNEL==sev, MODE=0666
```
=> docs: fix 50-sev.rules

Cargo.toml
The debug sections of the shims and exec are not loaded in the keep anyway.
=> feat: don't strip debug enarx binary

crates/exec-wasmtime/src/loader/requested.rs
Fixes Greenhouse monitor demo, which exceeds this size
=> fix: increase max wasm file size

.cargo/config, Cargo.lock, crates/shim-kvm/Cargo.toml, crates/shim-kvm/src/snp/ghcb.rs
Requires
```
[target.x86_64-unknown-none]
rustflags = [
"-C", "linker=gcc",
"--cfg", "polyval_force_soft",
"--cfg", "aes_force_soft",
]
```
otherwise it doesn't compile for the target and the build errors out with:
```
LLVM ERROR: Do not know how to split the result of this operator!
```
=> feat(shim-kvm): update aes-gcm requirement from 0.9 to 0.10.1

Cargo.toml
This is intended to mitigate theoretical attacks resulting from integer overflow. This mitigation only applies to the four crates specified, and not any of their dependents.
=> feat: panic on integer overflow for keep crates

src/cli/deploy.rs, src/drawbridge.rs
Closes https://github.com/enarx/enarx/issues/2111
`foo:bar` is a valid URL according to the spec:
https://url.spec.whatwg.org/#urls
Which means that there is no meaningful way to distinguish between a
colon-separated "slug" and a valid URL. To alleviate this, slugs now
have one, consistent, common OCI-like format: `owner/repo:tag`, which
means that the Enarx binary can unambiguously distinguish between a slug
and a URL.
Example:
```
$ enarx deploy examples/fibonacci-rust:0.2.0
Fibonacci sequence number at index 7 is 13
Fibonacci sequence number at index 21 is 10946
```
(Coming soon):
```
$ enarx deploy https://store.profian.com/api/v0.2.0/examples/fibonacci-rust/_tag/0.2.0
Fibonacci sequence number at index 7 is 13
Fibonacci sequence number at index 21 is 10946
```
```
$ enarx deploy …
```
=> feat!: enforce OCI-like `owner/repo:tag` slug format

Cargo.lock, crates/exec-wasmtime/Cargo.toml, crates/exec-wasmtime/src/loader/configured/platform.rs, crates/sallyport/src/item/enarxcall/mod.rs, crates/shim-kvm/src/hostcall.rs, crates/shim-kvm/src/lib.rs, crates/shim-kvm/src/main.rs, crates/shim-kvm/src/snp/attestation.rs, crates/shim-kvm/src/snp/ghcb.rs, crates/shim-kvm/src/snp/mod.rs, crates/shim-kvm/src/syscall.rs, crates/shim-sgx/Cargo.toml, crates/shim-sgx/src/handler/key.rs, crates/shim-sgx/src/handler/mod.rs, src/backend/mod.rs
Fixes: #2110 
Derives a key from the security attributes and the signing key for the SGX and SEV-SNP keeps.
=> feat: add `get_key` syscall

.github/workflows/lint.yml
All crates in the workspace use the same lockfile, so there should be no need to check each crate individually.
=> ci: consolidate deny checks

Cargo.lock
This is motivated by the need to get off of a yanked version of axum in order to do a release.
=> build: bump dependencies

docs/Install.md
We're passing more rustflags via .cargo/config, so we need to make sure the docs pass the rustflags manually, since `cargo install` doesn't use .cargo/config.
=> docs: update `cargo install` docs

Cargo.toml
In my experiments, while `opt-level="s"` does indeed make the Enarx binary itself smaller, it actually makes the shims slightly *larger*, and in practice the shims are the only binaries whose sizes we actually care about. There's no reason to pay the performance penalty of `opt-level="s"` if it isn't giving us size benefits. We can re-evaluate this in the future, as compiler developments tend to cause these metrics to fluctuate over time.
Also, we remove the `incremental=false` line because that's already the default for the release profile.
=> build: remove opt-level="s"

Cargo.toml, crates/shim-sgx/src/lib.rs, src/backend/sgx/config.rs
This reverts commit ed1f9b8bf28a92941b73500f6a260770aa05cd98.
Dynamically set the SGX features attributes according to the CPU
features.
Related: https://github.com/enarx/enarx/issues/2142
Works on the NUC, which has no AVX support.
```
[nix-shell:~/git/enarx/enarx]$ git show -s --pretty=oneline
046ae10a0a772f35b93b52b4f496aeaa9a4c7e87 (HEAD -> fix/sgx_avx_features, harald/fix/sgx_avx_features) fix(sgx): dynamically enable AVX and AVX512
[nix-shell:~/git/enarx/enarx]$ cargo run -- deploy examples/fibonacci-c:0.2.0 
[…]
Fibonacci sequence number at index 7 is 13
Fibonacci sequence number at index 21 is 10946
[nix-shell:~/git/enarx/enarx]$ cpuid -1 | fgrep AVX
AVX: advanced vector extensions         = false
AVX2: advanced vector extensions 2 …
```
=> fix(sgx): dynamically enable AVX and AVX512

src/backend/sev/data.rs, src/backend/sev/mod.rs
And also add an output for `platform info`:
```
✔ SEV-SNP VCEK key cache file: /var/cache/amd-sev/vcek-5cb260b9c24d8a9cbf1aab853d0eabae34dca787d876ae97f8d7a0e707d180ce07d4fdb2da7d6814b2f75b242a299dfd8181c157718c4b53a9ade79e82d24cbd-02-00-05-93
```
Related: https://github.com/enarx/enarx/issues/2142
=> fix(sev): check for the VCEK cache file

crates/shim-kvm/src/snp/cpuid_page.rs, crates/shim-kvm/src/sse.rs
and patch the osxsave feature flag for cpuid.
Directly modifying the CPUID page did not have any effect (as if it was read-only).
=> fix(shim-kvm): correctly set XCR0 according to cpuid

Cargo.lock
In order to pick up https://github.com/RustCrypto/signatures/pull/523
=> build: bump ecdsa crate to 0.14.5

crates/exec-wasmtime/src/loader/requested.rs
TLS certificate serial numbers must be at most 20 octet long according to https://www.rfc-editor.org/rfc/rfc5280#section-4.1.2.2
Use 16 octets to loosely match format used by the Steward.
Closes https://github.com/enarx/enarx/issues/2164
=> fix(exec-wasmtime): lower TLS cert serial number length

Cargo.lock
This address a rustsec advisory.
=> build: bump axum dep to 0.5.16

src/cli/mod.rs
correctly construct the filter from the provided string
```
$ ENARX_LOG=enarx::backend=trace enarx […]
```
```
$ enarx --log-filter="enarx::backend=trace" […]
```
=> fix(backend): log filter parsing

crates/enarx-config/Enarx_toml.md, crates/enarx-config/src/lib.rs
Default to a real, usable service rather than an example URL
=> refactor(config): default to Profian Steward

crates/enarx-config/src/lib.rs
The only reason the custom implementation was necessary was because of the struct field ordering, reorder and remove the custom implementation
=> fix(config): remove custom `Serialize` implementation

tests/wasm/mod.rs
Not sure why this was disabled, probably it was a workaround to make CI pass when the `deploy` URL access regression was introduced. The tests were there specifically to prevent that.
=> fix: reenable `enarx deploy` tests

crates/enarx-config/Enarx_toml.md, crates/enarx-config/src/lib.rs
Capitializing these does not really fit in with stdio names provided and does not reflect real-world use cases
=> refactor(config): avoid capitalizing file names

crates/enarx-config/src/lib.rs
Rather than silently ignoring config fields, fail if unknown fields are encountered
=> feat(config): error on unknown fields

tests/integration.rs
=> feat: print child stderr in tests

crates/enarx-config/src/lib.rs
TLS connections to raw IPs always fail (at least now)
#2187 
=> fix(config): use a domain name in TLS connect

crates/sallyport/src/guest/call/enarxcall/park.rs, crates/sallyport/src/guest/call/enarxcall/types/result.rs, crates/sallyport/src/guest/handler.rs, crates/sallyport/src/libc.rs, crates/sallyport/tests/enarxcall/mod.rs, crates/shim-sgx/layout.ld, crates/shim-sgx/src/handler/mod.rs, crates/shim-sgx/src/lib.rs, crates/shim-sgx/src/main.rs, crates/shim-sgx/src/thread.rs, src/backend/kvm/mod.rs, src/backend/mod.rs, src/backend/parking.rs, src/backend/sgx/builder.rs, src/backend/sgx/mod.rs, src/backend/sgx/thread.rs, src/cli/mod.rs, tests/crates/enarx_exec_tests/src/bin/futex.rs, tests/crates/enarx_exec_tests/src/bin/thread-channel.rs, tests/crates/enarx_exec_tests/src/bin/thread-exit-group.rs, tests/crates/enarx_exec_tests/src/bin/thread.rs, tests/exec/mod.rs
This patch series implements basic threading support for the SGX backend.
Currently only two additional threads can be started (and not restarted), because the TCS, SSA and stacks are statically allocated in the linker file. This will be turned into dynamic allocation in a followup PR.
Related https://github.com/enarx/enarx/issues/2160
=> feat: implement basic threading support for SGX

crates/shim-sgx/src/entry.rs
We already rely on the linux kernel to grant us to set fsbase. Reflect that in HWCAP2 to the executable and give it a cleared fsbase to work with.
=> fix(shim-sgx): set HWCAP2 and clear fsbase

tests/client/token
At first glance it looked like the file is misplaced and would have need to be put in `testdata` (or `data` in latest revision), but on closer inspection it turned out that it's not even used, hence remove
=> refactor(test): remove unused `token`

tests/wasm/mod.rs
This fixes up the "unused" warning and is generally a nicer way to handle it anyway
=> test(wasm): ignore Windows listener tests

Cargo.lock, crates/exec-wasmtime/Cargo.toml, crates/exec-wasmtime/src/runtime/net/tls.rs
Includes required changes in `exec-wasmtime` to adapt to breaking API changes
See https://github.com/bytecodealliance/wasmtime/commit/a68fa86aad7be732afbb9ec0960a6d3fdfee0c96 for reference of the changes
=> chore: update wasmtime

crates/shim-kvm/src/hostcall.rs, crates/shim-kvm/src/syscall.rs, crates/shim-sgx/src/handler/mod.rs
Don't print out unicode chars in debug mode. Multiple processes outputting stuff, can scramble the console easily.
=> fix(shim): replace unicode chars

tests/wasm/mod.rs
This reverts commit accc56571d45c9dd05e3c98c8496cee259af5225.
It is causing sporadic failure, most likely about memory locking ulimits.
Fixes https://github.com/enarx/enarx/issues/2237
=> fix: revert "test(wasm): avoid using `serial`"

crates/shim-sgx/src/handler/mod.rs, src/backend/sgx/thread.rs
=> fix(shim-sgx): don't output dbg for SYS_clock_gettime

crates/sallyport/src/guest/handler.rs, crates/shim-sgx/src/entry.rs, crates/shim-sgx/src/handler/mod.rs, crates/shim-sgx/src/main.rs, crates/shim-sgx/src/thread.rs, src/backend/sgx/thread.rs, tests/crates/enarx_exec_tests/src/bin/thread-exit-group.rs, tests/crates/enarx_exec_tests/src/bin/thread-many.rs, tests/crates/enarx_exec_tests/src/bin/thread.rs, tests/exec/mod.rs
This lets us reuse the SGX TCS after it's returned to the pool.
It also gets rid of global arrays for thread bookkeeping.
sallyport:
- don't be `attacked()` by return of `exit()`
it is correctly handled by the shim
shim-sgx:
- add Task Control Block (Tcb)
- load_registers() with exit_status
- return with exit_status in r8, especially CSSA=0
- remove MAX_THREADS restriction from `clone()`
- use the state in Tcb to return from `exit()` syscall
This will EEXIT CSSA=0 to the backend ready for re-use.
backend/sgx:
- requeue thread on CSSA=0 EEXIT
- panic on `exit()` syscall
- use exit status in r8 of CSSA=0 EEXIT
Related: https://github.com/enarx/enarx/issues/2160
=> feat(sgx): use CSSA level 0 EEXIT to return from `exit()` syscall

crates/exec-wasmtime/src/runtime/net/tls.rs
Sync with https://github.com/bytecodealliance/wasmtime/blob/ee2ef5bdd02ac75eff284e84dc9a8dcdf3d6e2c6/crates/wasi-common/cap-std-sync/src/net.rs
- Add missing method implementations from upstream
- Remove implementations, that are not present upstream
- Add TODOs and file issues for missing implementations
Refs #2241 #2242 #2243
=> fix(exec): sync TLS listener and stream applications with upstream

tests/crates/enarx_exec_tests/src/bin/thread-exit-group.rs, tests/exec/mod.rs
rather than the output. Increase the sleep of Thread 2 "should" eliminate all race conditions.
=> fix(test/exec::thread_exit_group): rely on exit code

crates/sallyport/src/guest/call/enarxcall/passthrough.rs, crates/sallyport/src/guest/handler.rs, crates/sallyport/src/item/enarxcall/mod.rs, crates/sallyport/tests/enarxcall/mod.rs, crates/shim-sgx/src/handler/mod.rs, src/backend/sgx/enarxcall.rs, src/backend/sgx/mod.rs, src/backend/sgx/thread.rs
and introduce a new `page_type` parameter. Now, this function can be used in general to set a page type.
Also factor out the sgx enarxcalls into a separate file.
=> feat(sgx): rename enarxcall `TrimSgxPages` to `ModifySgxPageType`

src/cli/user/register.rs, tests/client/mod.rs, tests/client/util.rs
This also:
* makes the OIDC mock server return 401 on unauthorized, rather than panicking, so we can test the authorization failure mode
* makes the mock OIDC server use our hardcoded OIDC client key, rather than a dummy token
* allows setting an option to `enarx user register` via an env var
* improves the integration test helper, by making it easier to use and read, and making the error output more useful and readable
=> test: check output during CLI integration tests

crates/sallyport/src/guest/call/enarxcall/passthrough.rs, crates/sallyport/src/guest/handler.rs, crates/sallyport/tests/enarxcall/mod.rs, crates/shim-sgx/layout.ld, crates/shim-sgx/src/handler/mod.rs, crates/shim-sgx/src/heap.rs, crates/shim-sgx/src/lib.rs, crates/shim-sgx/src/main.rs, crates/shim-sgx/src/thread.rs, src/backend/sgx/builder.rs, src/backend/sgx/enarxcall.rs, src/backend/sgx/ioctls.rs, src/backend/sgx/mod.rs, src/backend/sgx/thread.rs, tests/crates/enarx_exec_tests/src/bin/thread-many.rs
The SGX keep allocates memory and sets up the TCS for new threads, if the existing thread pool is drained.
The thread pool is not shrinked though. See https://github.com/enarx/enarx/issues/2251
Fixes: https://github.com/enarx/enarx/issues/2160
=> feat(sgx): implement dynamic thread allocation

tests/client/mod.rs, tests/client/util.rs
By comparing equality via JSON rather than via string representation, we guard against spurious failures that might result due to property order being unspecified in JSON objects.
This also includes a few other refactorings and cleanups to the CLI test runner.
=> test: parse JSON in CLI tests and refactor

.github/workflows/nix.yml, .github/workflows/release.yml, Cargo.toml, build.rs, flake.lock, flake.nix, rust-toolchain.toml, src/backend/sgx/attestation.rs, tests/client/mod.rs, tests/client/util.rs, tests/integration.rs, tests/wasm/mod.rs
- Git dependencies are now supported out-of-the-box
- The build is greatly simplified
- Caching performance should be improved
- `cargo clippy`, `cargo fmt` and `cargo nextest` are now run in release mode on `nix flake check`
- All binaries except for Windows are now cross-compiled via nix on Github default runners
=> build: use crane

.github/workflows/coverage.yml, .github/workflows/test.yml
Our self-hosted runners now have the tools installed, so apt is no longer required there.
=> chore: remove apt call on self-hosted runners

Cargo.toml, crates/enarx-config/Cargo.toml, crates/exec-wasmtime/Cargo.toml, crates/sallyport/Cargo.toml, crates/shim-kvm/Cargo.toml, crates/shim-sgx/Cargo.toml
This is a new feature of Cargo that allows us to avoid specifying version information in multiple places, making it easier to update versions across multiple crates and keep them all in sync.
Closes #2258 .
=> build: use workspace inheritance for dependencies

build.rs, flake.nix, tests/exec/mod.rs, tests/integration.rs, tests/syscall/mod.rs
Closes #2274 
When building for x86_64 Linux, shims should be built in the binary, but
that does not mean that the host can (or should) actually use them.
Introduce integration test helpers, which check `ENARX_BACKEND` within
the environment among other things at runtime
This means that `ENARX_BACKEND=nil cargo test` now succeeds even on systems
with e.g. SGX available
=> fix: support all platforms in tests

.github/workflows/update.yml, flake.lock
Run `nix flake update` once and automate it to run every night an 00.00
The PR will be filed similar to https://github.com/rvolosatovs/nixify/pull/22
If it's not merged until the action runs again, it should update again and update the PR. (https://github.com/peter-evans/create-pull-request/issues/1265#issuecomment-1264784900)
This is just the first step, most notably these PRs do not trigger `push` and `pull_request` workflows until manually closed and reopened. There are better workarounds https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
I think the right thing to do is to use @enarxbot for this, but I lack access to set it up
Maybe @puiterwijk can assist here with some solution, which would let us open PR from …
=> ci: automate flake update

.github/workflows/release.yml
Use the community key for main branch pushes and tags.
=> build: sign with community key only for main branch

src/cli/user/login.rs, src/cli/user/register.rs, src/drawbridge.rs
Specify OpenID Connect audience and scopes, so the tokens are properly restricted to the environment/API they are intended for.
=> feat(drawbridge): specify OIDC scopes and audience

tests/client/util.rs
=> test: fix tests when RUST_BACKTRACE is set

.github/workflows/release.yml
The ref name for the "main" branch had been incorrect: it had a prefix slash.
Correct this, and make sure the non-main-branch version of the code runs anytime the main version doesn't run.
=> fix: correct main ref name for sign

flake.lock, flake.nix
The upstream bug regarding workspace handling is now fixed, unpin
Closes #2306 
Closes #2345
=> build(nix): unpin `nixify`

.github/dependabot.yml
Dependabot is smart enough to automatically update all crates within the workspace. Note that `tests/crates/*` are not within the workspace and so those are left in.
=> ci: remove redundant dependabot directives

.github/workflows/cargo-update.yml, .github/workflows/release.yml, .github/workflows/rust-toolchain-update.yml
GitHub is deprecating the set-output command[1], so let's update to the new environment file syntax.
[1]: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
=> ci: update workflows to environment files

src/drawbridge.rs
Add a User-Agent to outgoing OpenID Connect requests, so we can track the source of authentication requests.
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
=> chore(drawbridge): add user-agent to OIDC requests

crates/exec-wasmtime/src/lib.rs
Closes #2352 
~Here's a minimized example of what's happening https://github.com/rvolosatovs/fd-leak~
Refs https://github.com/rust-lang/rust/issues/104734
=> fix(exec-wasmtime): prevent workload FD from being dropped

src/cli/package/info.rs, src/cli/package/publish.rs, src/cli/repo/info.rs, src/cli/repo/register.rs, src/cli/user/info.rs, src/cli/user/login.rs, src/cli/user/mod.rs, src/cli/user/register.rs, src/drawbridge.rs
This is based on top of and closes #2354 
Original description:
>This adds logging in with client credential grant for machine-2-machine interactions, like bots for uploading data to a Drawbridge instance.
Additionally, this adds an `oidc-flow` flag, which defaults to `device` and fixes few missed cases in #2354 (e.g. `enarx user register`)
- Support specifying a `client-secret-id` on `enarx user register`
- Reorganize code for clarity
- Remove redundant clones and borrows
=> feat(drawbridge): add client secrets login

Cargo.lock, crates/shim-sgx/Cargo.toml, crates/shim-sgx/src/thread.rs
especially the AEXNOTIFY `TcsFlags`.
"Intel Architecture Instruction Set Extensions and Future Features - Version 45" is out[2].  There is a new chapter:
Asynchronous Enclave Exit Notify and the EDECCSSA User Leaf Function.
Enclaves exit can be either synchronous and consensual (EEXIT for instance) or asynchronous (on an interrupt or fault).  The asynchronous ones can evidently be exploited to single step enclaves[1], on top of which other naughty things can be built.
AEX Notify will be made available both on upcoming processors and on some older processors through microcode updates.
1. https://github.com/jovanbulck/sgx-step
2. https://cdrdv2.intel.com/v1/dl/getContent/671368?explicitVersion=true
Related: …
=> feat(sgx): complete the TCS page struct and add the flags

crates/exec-wasmtime/src/runtime/net/mod.rs, src/exec/mod.rs
=> refactor: remove unnecessary usage of Lazy

crates/shim-kvm/src/main.rs, crates/shim-sgx/src/lib.rs
This will prevent, that these keeps will get an attestation validation.
Fixes: https://github.com/enarx/enarx/issues/1408
=> feat: set the keep's DEBUG flag on features dbg or gdb

src/backend/mod.rs, src/backend/sgx/enarxcall.rs, src/backend/sgx/thread.rs
Some cases are real errors and not normal exit stati.
Also catch panics in child threads and use `process:exit()` to terminate everything immediately.
=> fix: refine sgx error handling especially for threads

.github/workflows/labeler.yml
After changing the default permissions for the Actions tokens, this makes sure the labeler still has permissions to update issues.
=> ci: fix labeler github token permissions

src/cli/unstable/exec.rs
for `#[cfg(not(enarx_with_shim))]`.
=> fix: unused import: `std::process::ExitCode`

.github/workflows/commisery.yml
We have no need for this feature and it causes no end of annoyance.
=> build: make commissery no longer check PR titles

crates/shim-kvm/src/exec.rs, crates/shim-sgx/src/entry.rs
This also removes hard-coded `debug` level log in `exec-wasmtime`
=> fix: remove unused crt0 environment variables

crates/shim-sgx/layout.ld, crates/shim-sgx/src/handler/mod.rs, crates/shim-sgx/src/main.rs, src/backend/sgx/thread.rs
CSSA 1 and 2 get their own block.
CSSA 0 and 3 don't need a block.
Normal block usage looks like this:
* Enclave CSSA 0 fills in registers and executes syscall op.
* Host sees exception, calls CSSA 1 with sallyport block 0.
* Enclave CSSA 1 fills in sallyport block, executes syscall op.
* Host sees exception, handles sallyport block 0 and calls CSSA 2.
* Enclave CSSA 2 confirms CSSA 1 syscall op and increases instruction pointer of CSSA 1. Exits to the host.
* Host sees clean EEXIT of CSSA 2, calls CSSA 1.
* Enclave CSSA 1 continues after syscall op and handles sallyport block 0, then increases CSSA 0 instruction pointer and   exits to the host.
* Host sees clean EEXIT of CSSA 1, calls CSSA 0.
* Enclave CSSA 0 handles result of syscall.
Now, if there was lazy memory allocation for CSSA 0, …
=> feat(sgx): handle CSSA 0-3 with 2 sallyport blocks

Cargo.lock, Cargo.toml, src/cli/platform/caching.rs, src/cli/platform/sgx/crl.rs, src/cli/platform/snp/crl.rs
A few changes were made to how CRLs are fetched.
* Validate the CRL by deserializing it
* Make an array of the CRL structs
* Serialize to ASN1
* Save as a file in the correct directory (vs having multiple files).
Signed-off-by: Richard Zak <richard@profian.com>
=> chore: better CRL fetching and parsing

Cargo.lock, Cargo.toml, crates/shim-kvm/Cargo.toml, crates/shim-kvm/src/allocator.rs, crates/shim-kvm/src/debug.rs, crates/shim-kvm/src/exec.rs, crates/shim-kvm/src/gdt.rs, crates/shim-kvm/src/hostcall.rs, crates/shim-kvm/src/interrupts.rs, crates/shim-kvm/src/paging.rs, crates/shim-kvm/src/snp/ghcb.rs, crates/shim-kvm/src/snp/secrets_page.rs, crates/shim-kvm/src/spin.rs, crates/shim-kvm/src/syscall.rs, crates/shim-sgx/Cargo.toml, crates/shim-sgx/src/handler/mod.rs, crates/shim-sgx/src/thread.rs
`spinning` showed some instabilities while implementing threads on in the VM.
=> fix: use `spin` crate instead of `spinning`

crates/shim-sgx/src/handler/mod.rs, crates/shim-sgx/src/lib.rs, src/backend/sgx/enarxcall.rs, src/backend/sgx/thread.rs
This will allow to map the whole 2GB address range of the wasm application, which will speedup execution a lot.
=> feat(sgx): add page fault handling and lazy mmap

crates/sallyport/src/guest/alloc/tests.rs, crates/sallyport/src/host/mod.rs, crates/sallyport/src/item/mod.rs, crates/sallyport/tests/integration.rs, crates/sallyport/tests/syscall/mod.rs, crates/shim-kvm/src/interrupts.rs, crates/shim-kvm/src/main.rs, crates/shim-kvm/src/snp/ghcb.rs, crates/shim-sgx/src/main.rs, tests/crates/enarx_exec_tests/src/bin/memspike.rs, tests/crates/enarx_exec_tests/src/bin/sev_attestation.rs, tests/crates/enarx_exec_tests/src/bin/sgx_attestation.rs, tests/crates/enarx_syscall_tests/src/lib.rs, tests/crates/enarx_wasm_tests/src/bin/listen.rs, tests/crates/enarx_wasm_tests/src/bin/memspike.rs
=> build: fix `cargo clippy --workspace` and address warnings

src/backend/sev/snp/vcek.rs
According to AMD, the ReportedTcb is the one we need for the VCEK key.
Reported <= Committed <= Current
Further infos:
[Video]
(https://youtu.be/7R0rnQfi86I)
[Slides]
(https://developer.amd.com/wp-content/resources/LSS-SNP_Attestation-r4.pdf)
=> fix(snp): remove comment about SEV-SNP TCB

crates/sallyport/Cargo.toml
makes `cargo clippy --all-features --workspace` work.
Don't care about the documentation links possibly be broken, until we switch to gdbstub 0.6 in the future.
=> fix(sallyport): use workspace version of gdbstub

crates/sallyport/src/item/block.rs, crates/sallyport/src/lib.rs, tests/crates/enarx_exec_tests/src/bin/futex.rs, tests/crates/enarx_exec_tests/src/bin/sev_attestation.rs, tests/crates/enarx_exec_tests/src/bin/sgx_attestation.rs, tests/crates/enarx_exec_tests/src/bin/unix_echo.rs, tests/crates/enarx_exec_tests/src/lib.rs, tests/crates/enarx_syscall_tests/src/lib.rs, tests/crates/enarx_wasm_tests/src/bin/connect.rs, tests/crates/enarx_wasm_tests/src/bin/listen.rs
Fix-up Windows and Mac support broken by #2419
=> fix: cross-platform `--workspace` support

.codecov.yml, .github/dependabot.yml, .github/workflows/coverage.yml, .github/workflows/lint.yml, .github/workflows/test.yml
=> ci: various improvements in relation to `--workspace` support

.github/workflows/coverage.yml, .github/workflows/sbom_manifest_action.yml, .github/workflows/test.yml, rust-toolchain.toml, src/exec/mod.rs
This pulls in the Cargo bindeps bugfix that landed in https://github.com/rust-lang/cargo/pull/11478 .
=> build: bump Rust toolchain to 2023-01-02

.github/workflows/test.yml, .gitignore, Cargo.lock, Cargo.toml, crates/exec-wasmtime/Cargo.toml, crates/exec-wasmtime/src/lib.rs, crates/exec-wasmtime/src/log.rs, crates/exec-wasmtime/src/main.rs, crates/exec-wasmtime/src/runtime/identity/mod.rs, crates/exec-wasmtime/src/runtime/mod.rs, crates/exec-wasmtime/src/workload.rs, crates/shim-kvm/Cargo.toml, crates/shim-kvm/src/start.rs, crates/shim-sgx/Cargo.toml, crates/shim-sgx/src/lib.rs, src/backend/nil.rs, src/cli/deploy.rs, src/cli/mod.rs, src/cli/run.rs, src/exec/mod.rs
partially closes #2176 
Refs https://github.com/enarx/enarx/issues/1042 (the `log-filter` part, `log-target` is still TODO)
produce flame graph with (requires inferno crate)
`cat tracing.folded | inferno-flamegraph > tracing-flamegraph.svg;`
notes:
add more functions to flame graph?
logging might have been broken (enarx -v)
includes wiggle
=> feat: add flame graph

crates/shim-kvm/src/start.rs
Otherwise SSE/AVX does not work properly.
Before:
AMD KVM: 544 MFLOPS
After:
AMD KVM: 1140 MFLOPS
=> fix(kvm): set Cr0Flags::MONITOR_COPROCESSOR

.github/workflows/release.yml
This avoids the GitHub upload-artifact behaviour where if the name and path are not identical, the uploaded artifact is a zip file containing the original file.
=> fix(ci): rename the deb files before uploading

crates/exec-wasmtime/src/runtime/net/mod.rs
This makes the behaviour closer to wasmtime, and also unblocks .NET from running. .NET is expecting nonblocking sockets.
=> fix: set nonblocking on TCP

tests/crates/enarx_wasm_tests/src/bin/listen.rs
The test expects a blocking listen socket.
Because 9bd4de72d0e09c98f79614f03dea5cd4ac3dd45c sets nonblocking for the wasm preopened sockets, this test could fail.
=> test: fix wasm::listen_tcp

README.md
Since we no longer publish to crates.io
=> docs: remove crates.io version from readme

src/backend/kvm/thread.rs, src/backend/sgx/enarxcall.rs, tests/exec/mod.rs
This enables futex proxying for shim-kvm.
=> feat(backend/kvm): handle park/unpark enarxcalls

crates/shim-kvm/src/interrupts.rs, src/backend/sev/builder.rs, src/backend/sev/snp/launch/linux.rs, src/backend/sev/snp/launch/mod.rs
Because the current SEV-SNP linux kernel patchset does not allow to disable interrupt injection, mitigate against:
- #VMM with error_code 0x72 (VMEXIT_CPUID)
- page_fault handler without error_code or invalid error_code
=> fix(shim-kvm): protect against interrupt injection

crates/exec-wasmtime/src/runtime/identity/mod.rs, crates/exec-wasmtime/src/runtime/mod.rs
This prevents cryptic
```
Error: operation failed
```
failures from occuring, that were encountered during development
=> feat(exec-wasmtime): annotate identity generation errors

crates/shim-kvm/src/addr.rs, crates/shim-kvm/src/exec.rs, crates/shim-kvm/src/paging.rs
Taking an explicit `ShimPageTable` reference, instead of locking the global `SHIM_PAGETABLE` itself.
=> fix(shim-kvm): add TranslateFrom trait

Cargo.lock, Cargo.toml, crates/shim-kvm/Cargo.toml, crates/shim-kvm/src/debug.rs, crates/shim-kvm/src/gdb.rs, crates/shim-kvm/src/gdt.rs, crates/shim-kvm/src/hostcall.rs, crates/shim-kvm/src/interrupts.rs, crates/shim-kvm/src/lib.rs, crates/shim-kvm/src/start.rs, crates/shim-kvm/src/stdio.rs, crates/shim-kvm/src/syscall.rs
- use `write!` to enable inlining of arguments
- for `cfg(test)` use the `std` versions to enable the clippy linter
- inline all the arguments
- rename `print` module to differ from `print!` macro
=> feat(shim-kvm): cleanup print macros

crates/shim-kvm/src/allocator.rs, crates/shim-kvm/src/exec.rs, crates/shim-kvm/src/hostcall.rs, crates/shim-kvm/src/shim_stack.rs, crates/shim-kvm/src/start.rs
Create the `PageTableAllocatorLock` struct to acquire the locks of the page table and allocator in a defined order to avoid dead locks.
Move all methods needing both locks under this struct.
=> feat(shim-kvm): order lock of the page table and allocator

crates/shim-kvm/src/gdt.rs, crates/shim-kvm/src/interrupts.rs
As we disabled red zone in the shim, and we panic on double faults anyway, remove the unnecessary exception stacks.
=> feat(shim-kvm): remove exception stacks

crates/shim-kvm/src/lib.rs, crates/shim-kvm/src/start.rs
=> chore(shim-kvm): remove remenants of exception stacks

crates/shim-kvm/src/pagetables.rs
`pagetables::smash()` only needs read-only lock `SHIM_PAGETABLE`.
AlignedPageTable does not need a public inner.
=> fix(shim-kvm): pagetables fixups

crates/shim-kvm/src/exec.rs
=> fix(shim-kvm): no random exec addresses in `dbg`

crates/shim-kvm/src/allocator.rs, crates/shim-kvm/src/gdb.rs, crates/shim-kvm/src/gdt.rs, crates/shim-kvm/src/hostcall.rs, crates/shim-kvm/src/lib.rs, crates/shim-kvm/src/syscall.rs, crates/shim-kvm/src/thread.rs
Store the per cpu thread control block (Tcb) in the kernel GS register.
Introduce a `std::RefCell` like runtime borrow checker for the Tcb.
Do host syscall calls via the per cpu sallyport block and maintanence host calls via the global maintanence syscall block.
`HOST_CALL_ALLOC.try_alloc()` will also go away in follow up patches.
=> feat(shim-kvm): introduce thread control block Tcb

.cargo/config, .github/workflows/coverage.yml, .github/workflows/sbom_manifest_action.yml, .github/workflows/test.yml, rust-toolchain.toml
Just a regular update to coincide with the Rust 1.67 release.
=> build: bump Rust toolchain to 2023-01-27

.github/workflows/nix.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, crates/exec-wasmtime/src/runtime/mod.rs, crates/exec-wasmtime/src/runtime/net/tls.rs
Upgrade to Wasmtime 5.0.1 to address a security concern from `cargo deny`.
THe biggest change I see is that Wasmtime 5 made a lot of changes to how error types are handled, which made the bulk of the changes in `crates/exec-wasmtime/src/runtime/net/tls.rs`.
However, it seems that this has broken the `sgx` and `kvm` backends, in that output isn't shown on stdout. But `nil` backend works.
=> chore: upgrade to wasmtime 5.0.1

src/backend/sgx/data.rs
If enarx or the x86_64 crate does not keep up with CPU tech, using `from_bits` will prevent the usage of enarx on newer CPUs, because the checker will bailout here, although it's mostly used as an informative output.
Happens here with newer XEONs, which have the XTILECFG and XTILEDATA flags (bit 17 and 18) in Xfrm.
=> fix: use `from_bits_truncate()`

crates/exec-wasmtime/src/runtime/net/mod.rs, tests/crates/enarx_wasm_tests/src/bin/connect.rs, tests/crates/enarx_wasm_tests/src/bin/listen.rs, tests/crates/enarx_wasm_tests/src/lib.rs
=> test: pass nonblocking stat to further networking tests

src/backend/sgx/data.rs
shift edx by 32bit because:
ecx: contains bits 31:12 of size in the high bits
edx: contains bits 51:32 of size in the low bits
=> fix: calculate correct amount of EPC memory size
